### ISSUE TITLE
Wrong backgroupJob working on mutil server (dont use hangfire)

### ISSUE THREAD

**Issue by ngoc31031997** [abpframework/abp#10003]
I have issue with abp background Job.
I running bgj on mutil server and sometime it duplicate job, how to config my bgj, i want to bgj just running on one server in mutil server
someone help me pls

**Comment by ngoc31031997** [comment]
except hangfire, can i handle it with .netcore ?

**Comment by maliming** [comment]
If you're creating a bug/problem report, please include followings:

* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by leonkosak** [comment]
You should be running background jobs outside web application (in separated console applications) and only each console app (bg job) on one server at the time.
This is the safest approach for background jobs architecture.

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/issues/10032
