### ISSUE TITLE
Permission Manipulation for inter-communication between modules in a monolithic app

### ISSUE THREAD

**Issue by AbuDawood** [abpframework/abp#10239]
I am developing a monolithic app using ABP IO. However, I want to apply as much as I can the ethic of microservices for easy migration to that latter architectural structure.

I have respected almost all constraints including Aggregation, DDD, and so on.

For the scenario synchronous communication between services, I have used the Client proxy for the C# as it has documented and it worked perfectly except on the side of permissions. I want configurable permission that could I use to differ between internal requests that are performed between modules (future microservices) and the public requests that come from outside.

Any suggestions??

**Comment by maliming** [comment]
>  except on the side of permissions

Can you explain this?

**Comment by AbuDawood** [comment]
well, Thank you for ur interest 
I am trying to maximize the isolation between modules to ease the future migration to the microservice-based architecture.

- all modules has their own databases
- the main app (module) is directly dependent to modules.
- no module is dependent to other except the previous case.
- I am using client proxy to call necessary services in some other services. However, the request send over the service A to Service B requires the user to have permissions required in Service A and B where it should only requires the ServiceA permissions alone.

How can I pass permission validation for service B when this latter is called by his siblings not directly by the User?

**Comment by maliming** [comment]
You can refer to this design. The permission should be as infrastructure.
https://github.com/abpframework/eShopOnAbp
https://github.com/maliming/abp-ms-map

**Comment by AbuDawood** [comment]
Can I apply the multiple gateways design to my monolithic app??

**Comment by gterdem** [comment]
> Can I apply the multiple gateways design to my monolithic app??

I think there is a misconception in understanding here. 

Monolithic application is **a single application** containing all your functionality (from UI to data access) of your business. This application **is deployed as a single unit** to a web server. It has its own advantages and disadvantages. 

Microservice application **is a distributed approach** for your application; distributing functionality to many other applications with their own data store and functionality. This means you divide your application to mini self running applications and deploying each of them to their own web-servers.

Like pizza.
![pizza](https://user-images.githubusercontent.com/25867/136326864-84cc64f0-d89a-41bd-a491-5aae29f4ac2c.png)
 Your application is a whole **monolithic** pizza and all ingredients can communicate with each other with ease. Since they are on the same plate.

You decide to slice the pizza to 4 pieces and now each one of them contains a piece of your business logic and responsible for itself. If pieces need to communicate with each other, they need to find a way (message broker or http/rpc call) since they are all in different plates now.
 
Now, about gateways.. Think about the sliced pizza and you want a slice with mushrooms **but** you can't see the whole pizza, it is covered (_microservices running on internal network_). So you make a request, asking for a slice of pizza with mushrooms; this request goes to **API Gateway** and it redirects to wherever the mushroom piece is located inside.
 
Maybe too simple analogy but I hope it helps to understand the main concept.

PS: _Image is from www.williams-sonoma.com_

**Comment by afresh** [comment]
> You decide to slice the pizza to 4 pieces and now each one of them contains a piece of your business logic and responsible for itself. If pieces need to communicate with each other, they need to find a way (message broker or http/rpc call) since they are all in different plates now.

@gterdem How to use the rpc call in "abp-MicroserviceDemo"?

**Comment by gterdem** [comment]
@afresh You can check [rpc sample](https://github.com/abpframework/abp-samples/tree/master/GrpcDemo) about it. Also, please create a new issue if you have questions about it.
