### ISSUE TITLE
Update Angular version to 13

### ISSUE THREAD

**Issue by muhammedaltug** [abpframework/abp#10517]
- [x] app template
- [x] module template
- [ ] sample apps

**Comment by davidzwa** [comment]
@mehmet-erim Im running Angular v13 and have two tips on how to make it work with v4.4.4 of ABP and v5 if it helps.

### Locale error
I had to downgrade @angular/common v12 because of the locale webpack trick
```
export function registerLocale(locale: string) {
    return import(
        /* webpackChunkName: "_locale-[request]"*/
        /* webpackInclude: /[/\\](en|nl|de|fr).js/ */
        /* webpackExclude: /[/\\]global|extra/ */
        `@angular/common/locales/${differentLocales[locale] || locale}.js`
        );
}
```
It states that `./locales` is not exported. I also notice that this node_module subfolder contains `.mjs` and `.ts` files now for v13 which is not the case for v12 (.js and .ts). Maybe we have to figure out a way around it or maybe we can skip loading locales altogether?

### New Ivy format (Angular Package Format or APF)
The output of compiling with ABP's angular packages results in the tip meant for you guys:
```
- angular-oauth2-oidc [es2015/esm2015] (manfredsteyer/angular-oauth2-oidc)
- @ngxs/store [es2015/esm2015] (git+https://github.com/ngxs/store.git)
- @ng-bootstrap/ng-bootstrap [es2015/esm2015] (git+https://github.com/ng-bootstrap/ng-bootstrap.git)
- @swimlane/ngx-datatable [es2015/esm2015] (git+https://github.com/swimlane/ngx-datatable.git)
- @abp/ng.core [es2015/esm2015] (https://github.com/abpframework/abp.git)
- @ngx-validate/core [es2015/esm2015] (git+https://github.com/ng-turkey/ngx-validate.git)
- @ngxs/store/operators [es2015/esm2015] (git+https://github.com/ngxs/store.git)
- @abp/ng.theme.shared [es2015/esm2015] (https://github.com/abpframework/abp.git)
- @abp/ng.permission-management [es2015/esm2015] (https://github.com/abpframework/abp.git)
- @abp/ng.theme.shared/extensions [es2015/esm2015] (https://github.com/abpframework/abp.git)
- @abp/ng.feature-management [es2015/esm2015] (https://github.com/abpframework/abp.git)
- @abp/ng.tenant-management [es2015/esm2015] (https://github.com/abpframework/abp.git)
- @abp/ng.identity [es2015/esm2015] (https://github.com/abpframework/abp.git)
Encourage the library authors to publish an Ivy distribution.
√ Browser application bundle generation complete.
```
I've removed all packages which are irrelevant to your work here (NGXS, angular flex-layout, etc).
Wish you the best of luck with the upgrade path! Here you go in case it's missed
https://angular.io/guide/angular-package-format#:~:text=Packages%20in%20the%20Angular%20Package%20Format%20contain%20one%20primary%20entrypoint,angular%2Fcore%2Ftesting%20).

**Comment by mehmet-erim** [comment]
Hello @davidzwa,

Angular v13 breaks many integrations, we will wait for the next versions for fixing the problems.
We cannot upgrade to Angular v13 until this issue is resolved:
https://github.com/angular/angular/issues/43833
On the other hand, we will wait for the next versions of other dependent packages like the `angular-oauth2-oidc`.

I hope the problems will be resolved till the ABP v5.1 is released.

Thanks for sharing your thoughts.

**Comment by davidzwa** [comment]
I agree its quite a tough transition. Wish you the best and I'll keep testing once you're ready for it!

**Comment by mehmet-erim** [comment]
We're waiting for https://github.com/angular/angular-cli/issues/22088 to be resolved to update templates to Angular v13.

**Comment by davidzwa** [comment]
https://github.com/angular/angular-cli/issues/22088#issuecomment-977254100
Would this work? The .mjs files are most probably the problem here, right?

**Comment by mehmet-erim** [comment]
No, it does not work. We tried many ways to resolve it, but we cannot. The problem is actually related to exports in @angular/common's package.json file. 

```diff
 "exports": {
+    "./*": {
+      "default": "./*"
+   },
```

When I added the export above to the package.json file manually. It works.
