### ISSUE TITLE
EntityHistory - AbpDbContext don't save changes

### ISSUE THREAD

**Issue by totpero** [abpframework/abp#10527]
* Your **ABP Framework version**.
* 4.4.3
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Blazor Server
* Your database provider(EF Core/MongoDB)
* EF Core

Hi,
I fallow the documentation steps (https://docs.abp.io/en/abp/4.4/Audit-Logging) to activate EntityHistory for all my entities `options.EntityHistorySelectors.AddAllEntities();`  but when I try to save some changes nothing happens. 
After few debug scenarios i found that the "AuditingManager.Current" is null [here](https://github.com/abpframework/abp/blob/fe519e3a12ad424d154e0cae83b58285d35a3411/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L158) 

I have set the [UseAuditing()](https://docs.abp.io/en/abp/4.4/Audit-Logging#useauditing) in my blazor module and 
Configure<AbpAuditingOptions>(options =>
{
    options.IsEnabled = true;
    options.EntityHistorySelectors.AddAllEntities();
});

Why [AuditingManager.Current](https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/framework/src/Volo.Abp.Auditing/Volo/Abp/Auditing/IAuditingManager.cs#L8) is null?

**Comment by maliming** [comment]
Are you using blazor wasm or blazor server?

**Comment by totpero** [comment]
blazor server

**Comment by coskunkula** [comment]
I am using abp framework 5.2.1 version. I am running an application as a Blazor server. I need to use audit features. When I update any record, log and audit log are not kept. As a result of my long research, I ran the SaveChangesAsync method in DbContext.cs class by overrride and
var auditLog = AuditingManager?.Current?.Log; On line Current comes as null. I'm guessing it might be because of that. How can I do it?

**Comment by maliming** [comment]
For Blazor server: https://github.com/abpframework/abp/issues/11682#issuecomment-1066064249
