### ISSUE TITLE
This line In ApiDescriptionFinder deserialize result both Modules and Types is null

### ISSUE THREAD

**Issue by xsoutline** [abpframework/abp#10590]
https://github.com/abpframework/abp/blob/6051fd4e3886ea05f7f6a04e17d6c0d3fe8471e8/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/DynamicProxying/ApiDescriptionFinder.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L116

This line In ApiDescriptionFinder deserialize result both Modules and Types is null.

I has try,Use Newtonsoft.Json.JsonConvert.DeserializeObject is OK.

My dotnet version: .NET5.0

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by zhaozhen-king** [comment]
Hello! Please take a look at this problem！！！ I use ABP--version  4.4.4 My dotnet version: .NET5.0.   angularjs and Abp applation. This is what happens when YOU update the Modules package today。 The permissions and basic Settings screen are gone after login。My swagger and IdentityServer can work properly.Thank you
![image](https://user-images.githubusercontent.com/57710517/141073624-8925a50a-cd82-4e8e-bdfb-452a23a8e4f2.png)

**Comment by zhaozhen-king** [comment]
@maliming
