### ISSUE TITLE
TenantManagement permission should be hidden if MultiTenancyOptions.IsEnabled = false is set

### ISSUE THREAD

**Issue by Nokecy** [abpframework/abp#1061]

**Comment by Nokecy** [comment]
https://github.com/abpframework/abp/blob/4206528ff90dea98c80080523d65c7030c4394d4/framework/src/Volo.Abp.MultiTenancy/System/Security/Principal/AbpClaimsIdentityExtensions.cs#L20-L22
Maybe here you should check the MultiTenancyOptions.IsEnabled property

**Comment by hikalkan** [comment]
I didn't understand why we check but anyway checking MultiTenancyOptions.IsEnabled is not possible there because it is a static method. 

Will check what we can do about this. We should probably do that something here: https://github.com/abpframework/abp/blob/master/framework/src/Volo.Abp.Authorization/Volo/Abp/Authorization/Permissions/PermissionChecker.cs#L55

BTW, if your application is not multi-tenant, just don't use the TenantManagement module.

**Comment by Nokecy** [comment]
Sorry, I don't understand the use case of MultiTenancyOptions.IsEnabled，Can you tell me?

**Comment by hikalkan** [comment]
MultiTenancyOptions.IsEnabled is actually for modules those can work in a multi-tenant or single-tenant application. They can just check the current setting and work based on it.

For the final application, just don't include (or remove) tenant management to your solution if your application is not multitenant, because you already know it.

**Comment by hikalkan** [comment]
Nothing to do about that, closing.
