### ISSUE TITLE
No valid error message when no organization found in abp login

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#10610]
Try to login with a non-existing organization name

```
abp login <username> -p <password> -o DummyOrganization
```

It sends an error HTML.  But it should write `There is no organization with the name "DummyOrganization"`
![image](https://user-images.githubusercontent.com/9526587/141301008-632a7691-b892-44eb-9e3a-a908ee8e340b.png)

**Comment by EngincanV** [comment]
It seems, this problem was resolved with version **5.0.0-beta.3**.

**Version 4.4.4**

![444](https://user-images.githubusercontent.com/43685404/141306863-936207e3-8e42-4f70-b3d4-9f0da10b745e.png)

**Version 5.0.0-beta.3**

![500](https://user-images.githubusercontent.com/43685404/141306888-bf846c6a-8291-4bfd-9ece-0ee51fa29f42.png)
