### ISSUE TITLE
How to use extended field query in EF query？

### ISSUE THREAD

**Issue by feigaogit** [abpframework/abp#10662]
![image](https://user-images.githubusercontent.com/18181270/142372493-47f39f74-c087-4a18-8b3c-94790b82d49d.png)

**Comment by berkansasmaz** [comment]
If you're trying to do this for the `ExtraProperties` field in the database, you can't. Because the properties set in the `ExtraProperties` field are stored as a single JSON object.

<hr>

However, you can refer to [this document](https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Extending-Entities#entity-extensions-ef-core) which explains the more natural way to do it.

If you have already mapped the property to ef core as stated in the document, you can use the query, below. Because the property you add is kept as a separate column in the database table.

```
var query = (await GetQueryableAsync()).Where(u => EF.Property<string>(u, "SocialSecurityNumber") == "123");
```

### References:

1. https://github.com/abpframework/abp/blob/dev/docs/en/Community-Articles/2021-05-24-Removing-EfCore-Migrations/POST.md#querying-based-on-a-custom-property
2. https://github.com/abpframework/abp/blob/dev/docs/en/Community-Articles/2021-05-24-Removing-EfCore-Migrations/POST.md#mapping-to-the-database-table
