### ISSUE TITLE
How to pass HttpStatusCode for remote service call

### ISSUE THREAD

**Issue by Goxiaoy** [abpframework/abp#1072]
I have read [Exception-Handling document](https://github.com/abpframework/abp/blob/1755ff75a5443a36206b4d000a08b72ece2f66f5/docs/en/Exception-Handling.md), but I still have some questions.

Service A call remote service B, and if B throw Bussiness exception and return 403, A should pass this exception with 403 instead of 500?

**Comment by hikalkan** [comment]
This may be in some cases, but may not be in some other cases.

>The HTTP 403 Forbidden client error status response code indicates that the server understood the request but refuses to authorize it.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

403 means this is an error of the client. It should change the request or cancel it.

If service A calls the server B, and B returns 403, this error can be because of the actual client (that calls A) or the service A (as the client of B). How can ABP understand the difference?

We can think that it is A's responsibility to handle B's exceptions and return a proper response to the client.

Anyway, I am adding this to backlog to think later.

**Comment by Goxiaoy** [comment]
And the error code B generated will pass to service A caller directly but the message will be masked as "An internal error occurred during your request!" because A treat this as remoteServiceError and return 500 http status code

**Comment by abdumostafa** [comment]
I have the same issue my remote service returns 401 UnAuthorized but I can't handle it on my Error page instead HttpStatusCode of AbpErrorViewModel returns 500 and RemoteServiceErrorInfo is empty except the message

**Comment by markfilan** [comment]
This error indicates that the server has determined that you are not allowed access to the thing you've requested, either on purpose or due to a misconfiguration . It's probably because the site owner has limited access to it and you don't have permission to view it. The vast majority of the time, there's not much you can do to fix things on your (*client) end. There are four common causes for [403 Forbidden](http://net-informations.com/q/mis/403.html) error (server side) . Here they are listed from most likely to least likely:

- An empty website directory
- No index page
- Incorrect settings in the .htaccess file
- Permission / Ownership error

If authentication credentials were provided in the request, the server considers them insufficient to grant access. The client SHOULD NOT automatically repeat the request with the same credentials. The client MAY repeat the request with new or different credentials. However, a request might be forbidden for reasons unrelated to the credentials.
