### ISSUE TITLE
Libs folder is in source control?

### ISSUE THREAD

**Issue by bbakermmc** [abpframework/abp#1075]
Downloaded template, looks like lib folder has file that are in source control?

**Comment by hikalkan** [comment]
Yes, this is by design decision taken after discussions and considerations (but surely it doesn't mean that it is totally true, it has advantages & disadvantages). Notice that we don't put whole node_modules and also try to eliminate unrelated files.

You can easily ignore it for your solution. In that case, every developer should run 'yarn' and 'gulp' after getting code from GitHub and also you should do that in CI/CD pipeline.
