### ISSUE TITLE
L Method to String Extension?

### ISSUE THREAD

**Issue by bbakermmc** [abpframework/abp#1077]
When looking at the code L("TextToBeLocalized"); doesn't always read well.
Possibly use a string extension like: "TextToBeLocalized".ToLocalization();  Then when reading the code you can understand whats happening.

**Comment by bbakermmc** [comment]
ref:
![image](https://user-images.githubusercontent.com/30090055/56919046-97ba1b00-6a8d-11e9-8af8-69d3100e1f73.png)

**Comment by hikalkan** [comment]
"TextToBeLocalized".ToLocalization(); is not good because of two reasons;

1. Creating a localization extension to very command string class is not a good practice, because for most of strings in an application, it will not be meaningful.
2. Creating such an extension method will be static and can not resolve dependencies (IStringLocalizer in this case). So, it is technically impossible.

A `localizer["Menu:Home"]` would be more easy to understand and possible to implement. I don't go against it. You can do it like that in your code and it is OK and good.
However, `l` is more practical in my opinion and it is an old tradition/convention of ABP framework.

So, this is not a framework thing, but just a local variable, anyone can name it however they like.
