### ISSUE TITLE
Landing page for each tenant and custom domain names

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1092]
Is there a feature where each tenant can have its own custom domain name and a custom landing page which they can edit and update?

**Comment by hikalkan** [comment]
>where each tenant can have its own custom domain

Sure, that's possible, subdomain or domain.

>custom landing page 

This is your implementation point, just check current tenant and show a customized page.

**Comment by vnetonline** [comment]
@hikalkan I would like to implement this and send a pull request can you please let me know how to implement it in the best way?

Also I have just registered a domain name abpcentral.com where I plan to have video tutorials and other resources for the abp framework and technologies like Xamarin, Ionic, ReactNative using abp framework as the backend for apps deployed on Azure AppServices.

I would like to use abp framework to build this website are we any closer to a version 1.0. There seems to be a lot of work which needs to be done.

**Comment by hikalkan** [comment]
> are we any closer to a version 1.0. There seems to be a lot of work which needs to be done.

For such a big project, it is hard to say a date. We had planned to release 1.0 in this June. We are working to accomplish it. But it may be marked as beta, because asp.net core 3.0 will bring a lot of breaking changes and we want to launch 1.0 stable release with .net core 3.0.

>I would like to implement this and send a pull request can you please let me know how to implement it in the best way?

It depends on your case. If you want to manually (statically) create pages for each tenant, it will be different than creating a single page shows different title, logo and content for each tenant.
In any way, ICurrentTenant gives you the tenant id and name.
But, I don't think that is something suitable to be a part of the framework. That is application specific, so instead of sending a PR, writing a tutorial/article would be better.

**Comment by vnetonline** [comment]
@hikalkan

Can you point me to the file where I can add the redirects please ?

Vineet Belani
+61 402 263 321

On 8 May 2019, at 4:46 pm, Halil İbrahim Kalkan <notifications@github.com<mailto:notifications@github.com>> wrote:


are we any closer to a version 1.0. There seems to be a lot of work which needs to be done.

For such a big project, it is hard to say a date. We had planned to release 1.0 in this June. We are working to accomplish it. But it may be marked as beta, because asp.net<http://asp.net> core 3.0 will bring a lot of breaking changes and we want to launch 1.0 stable release with .net core 3.0.

I would like to implement this and send a pull request can you please let me know how to implement it in the best way?

It depends on your case. If you want to manually (statically) create pages for each tenant, it will be different than creating a single page shows different title, logo and content for each tenant.
In any way, ICurrentTenant gives you the tenant id and name.
But, I don't think that is something suitable to be a part of the framework. That is application specific, so instead of sending a PR, writing a tutorial/article would be better.

**Comment by hikalkan** [comment]
Are you asking a custom landing page? I don't know, easiest way to have an Index page which reads current tenant id and redirects to a dedicated page. This is your application, not related to the framework.

**Comment by vnetonline** [comment]
Yeah I am asking where do you suggest I put the redirect to a custom page for the tenant before they get to the login page?

Vineet Belani
+61 402 263 321

________________________________

**Comment by hikalkan** [comment]
>before they get to the login page

If you use domain based tenant detection, you can know the current tenant before they login.

**Comment by vnetonline** [comment]
@hikalkan in my .web project I can’t seem to find the login controller to intercept the request and check the domain. Can you suggest where I can do this check and redirect

It would be great if there was a architecture diagram to explain how things are working and how all the prices hang together

Any help you can provide would be appreciated.

I plan to put up video tutorial as you suggested.

I wanted to ask if I can used the abp logo on my website because I plan to call the site abpCentral. The logo concept is the abp logo with the Center next to it.

Let me know if you would like me to email you the concept image.

**Comment by hikalkan** [comment]
>It would be great if there was a architecture diagram to explain how things are working and how all the prices hang together

This framework is preview, has no much documents yet. By the time, it will have rich docs.

>can’t seem to find the login controller

it is in the Account module. You can replace override controllers via DI and views via [Virtual File system](https://abp.io/documents/abp/latest/Virtual-File-System) (see Views & Pages section). But, I don't have time to explain everything. Since this is preview, you should dig into the code to understand it.

>I wanted to ask if I can used the abp logo on my website because I plan to call the site abpCentral. The logo concept is the abp logo with the Center next to it.

No, sorry, if you put ABP logo like that, it seems it is an official web site of ABP. What is and where is abpCentral?
