### ISSUE TITLE
old target framework in libraries?

### ISSUE THREAD

**Issue by bedrierol** [abpframework/abp#11345]
Hi, 
What is the reason for using .net 2.0 in the shared libraries? One of them is listed below:

eShopOnAbp/shared/EShopOnAbp.Shared.Hosting/EShopOnAbp.Shared.Hosting.csproj

**Comment by EngincanV** [comment]
Hi @bedrierol, we use .net 2.0 for the shared packages/libraries because it is the formal specification (recommended way) that helps to share code between multiple .NET project types.

> If you want to share code between .NET Framework and any other .NET implementation, such as .NET Core, your library should target .NET Standard 2.0
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

> We recommend you target .NET Standard 2.0, unless you need to support an earlier version. Most general-purpose libraries should not need APIs outside of .NET Standard 2.0. .NET Standard 2.0 is supported by all modern platforms and is the recommended way to support multiple platforms with one target.
https://docs.microsoft.com/en-us/dotnet/standard/net-standard#which-net-standard-version-to-target
