### ISSUE TITLE
eShopOnAbp: Convert public web gateway to Envoy

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#11424]
We can discard the swagger UI for this gateway.

**Comment by gterdem** [comment]
Envoy uses dns adress resolving hence we need to pass valid dns for upstream instead of `localhost:someport`.

This will prevent tye development environment and force us to use docker development. 

We can use YARP with isolated config file since we don't need any loadbalancing etc in development and use `envoy` on k8s staging and docker-compose.
