### ISSUE TITLE
eShopOnAbp: Unexpected (code) dependence between services

### ISSUE THREAD

**Issue by xirius** [abpframework/abp#11547]
I was looking into the [eShopOnAbp](https://github.com/abpframework/eShopOnAbp) solution and I was surprised to see many inter-dependencies between solutions.

For example I would expect [identity](https://github.com/abpframework/eShopOnAbp/tree/main/services/identity)[server] solution to be self-contained. Meaning I would be able to take it, compile and run it.

1.  Unfortunately, its appsettings.json points to 2 databases: [self and administration](https://github.com/abpframework/eShopOnAbp/blob/main/services/identity/src/EShopOnAbp.IdentityService.HttpApi.Host/appsettings.json#L21-L22) databases.
Which is weird in itself and doesn't follow a µ-service architecture (each service has its own db and communicates with other services through an API/Bus).

2. It is OK to have shared projects but than they should truly be shared and independent. Meaning that one can package them as nuget packages and use in other services.
Unfortunately, even the [shared components ](https://github.com/abpframework/eShopOnAbp/tree/main/shared) have dependencies to other services.
An example of [EShopOnAbp.Shared.Hosting.Microservices](https://github.com/abpframework/eShopOnAbp/tree/main/shared/EShopOnAbp.Shared.Hosting.Microservices) which is dependent on [EShopOnAbp.AdministrationService.EntityFrameworkCore](https://github.com/abpframework/eShopOnAbp/blob/main/shared/EShopOnAbp.Shared.Hosting.Microservices/EShopOnAbp.Shared.Hosting.Microservices.csproj#L26)

It would be better to have a reference implementation of the µ-service solution which is truly flexible with fully self contained µ-services.
One would be able to pick only the services needed for their project and build upon them. Later on other services can be added if the need arises. 

![11a5f527dbdfc75f3ef139fd971e5269](https://user-images.githubusercontent.com/417876/153088244-c2f1849c-5e59-4708-8c88-9136c74bae95.png)

**Comment by gterdem** [comment]
> For example I would expect [identity](https://github.com/abpframework/eShopOnAbp/tree/main/services/identity)[server] solution to be self-contained. Meaning I would be able to take it, compile and run it.

Actually, IdentityServer is hosted at [auth-server](https://github.com/abpframework/eShopOnAbp/tree/main/apps/auth-server), [identity](https://github.com/abpframework/eShopOnAbp/tree/main/services/identity) microservice hosts the database and api endpoints for **identity** and **identityserver**.

> 1. Unfortunately, its appsettings.json points to 2 databases: [self and administration](https://github.com/abpframework/eShopOnAbp/blob/main/services/identity/src/EShopOnAbp.IdentityService.HttpApi.Host/appsettings.json#L21-L22) databases.
> Which is weird in itself and doesn't follow a µ-service architecture (each service has its own db and communicates with other services through an API/Bus).

It doesn't **have to** follow a µ-service architecture. We embraced a pragmatical approach here. ABP already provides extensive modules that can be transformed into microservices individually.

When you run the default microservice solution, you are provided with identity, permission, setting, feature etc managements. These **managements** must be hosted in **somewhere**. Like lego pieces, we decided to merge them logically as we see fit.  Instead of separating all the management modules into different microservices; we merged identity and identityserver modules into **identityService**, [other management modules](https://github.com/abpframework/eShopOnAbp/blob/fb3e3c4ba826adec05dffbb46eb1baeee7ea7731/services/administration/src/EShopOnAbp.AdministrationService.HttpApi/AdministrationServiceHttpApiModule.cs#L10-L12) into **administrationService**.  And we called them **infrastructural services**.

About having **multiple connectionstrings** (like identityservice), that's a choice to make direct call to database instead of making http call because of performance considerations. You may have noticed **administrationService connection string** is located in every microservice. That's because each microservice permissions are stored in administrationService database. Instead of making http calls, direct database calls are made when caching (or invalidating) permissions on redis. 
Currently, only way to make **central permission management work** in distributed systems **efficiently** is to make it available and reachable for other services using direct database calls.

> 2. It is OK to have shared projects but than they should truly be shared and independent. Meaning that one can package them as nuget packages and use in other services.
> Unfortunately, even the [shared components ](https://github.com/abpframework/eShopOnAbp/tree/main/shared)have dependencies to other services.
> An example of [EShopOnAbp.Shared.Hosting.Microservices](https://github.com/abpframework/eShopOnAbp/tree/main/shared/EShopOnAbp.Shared.Hosting.Microservices) which is dependent on [EShopOnAbp.AdministrationService.EntityFrameworkCore](https://github.com/abpframework/eShopOnAbp/blob/main/shared/EShopOnAbp.Shared.Hosting.Microservices/EShopOnAbp.Shared.Hosting.Microservices.csproj#L26)

It's dependency is because of **on the fly database migration and seeding** but I agree with you; shared projects shouldn't be dependent on any microservice. I'll try to find a better way.

> It would be better to have a reference implementation of the µ-service solution which is truly flexible with fully self contained µ-services.

Our goal was not creating a reference implementation of the µ-service solution. eShopOnAbp is a showcase for building a **microservice application using ABP framework**, using existing ABP modules and features. This is also what your monolith application can look like when you decide to update to microservices.
**However**, I see your point. We can have a reference implementation of the µ-service solution using single-layer template and CQRS! (That is what i have in mind)

Thank you for your interest, I hope I was able to answer your questions.
