### ISSUE TITLE
EventBus publish / subscribe between isolated mudules

### ISSUE THREAD

**Issue by Klainer** [abpframework/abp#1166]
Hello.

I have one question about eventBus and project organization.¨

I looked on microservice demo project where is this event published: `ProductStockCountChangedEto` this event type live in `ProductManagement.Domain` project.

You are saying: 

> _Any subscriber can receive this event and perform an action based on that knowledge._

What is the right way to subscibe this event in another idependent Project / Module ? For example BasketModule where `ProductStockCountChangedEto` type is not living. I must create some shared Assembly between theese modules ? What is the best practice for thrully independend Microservices / Modules ? ..

Thanks for any advice!
And thanks for your work!

**Comment by hikalkan** [comment]
> I must create some shared Assembly between theese modules ?

`ProductStockCountChangedEto` should be moved to ProductManagement.Domain.Shared. I will do that. So, other module can reference it and use.

Other solution can be duplicating the class inside the basket module. Since ABP is using Json serialization, it can deserialize to a different type as long as the property names match.

**Comment by hikalkan** [comment]
@maliming can you move `ProductStockCountChangedEto` to ProductManagement.Domain.Shared? Thanks.

**Comment by maliming** [comment]
Already moved to the Domain.Shared layer. https://github.com/abpframework/abp/commit/439ec0624e759b6bb9a624bbc95eea32b9fa8149
