### ISSUE TITLE
Test - ABP Free Templates

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#11742]
Test the following ABP templates

To update CLI tools to the latest version:

**Update CLI :**
```
dotnet tool update -g Volo.Abp.Cli
```
 
---

- [x] App: Angular UI (MongoDB)

```bash 
abp new Angular.MoongoSeperated220301  -t app -u angular -m none --separate-identity-server --database-provider mongodb -csf 
```

- [x] App: Blazor-Server (EF Core)

```bash
abp new BlazoorServer.EfCore220301 -t app -u blazor-server --mobile none -csf 
```

- [x] App: Blazor-WASM (PostgreSQL)

```bash
abp new BlazoorWasm.EfCore220301 -u blazor --separate-identity-server --database-management-system PostgreSQL -csf -t app
```

- [x] App: MVC  (EF Core)

```bash
abp new Mvc.EfCoreNonTier220301 -t app -u mvc --mobile none --database-provider ef -csf 
```

- [x] Console

```bash
abp new MyConsoleApp220301-t console --csf 
```

- [x] Module

```bash
abp new MyModule220301 -t module --csf 
```

Related docs: 

- [Application template](https://docs.abp.io/en/abp/latest/Startup-Templates/Application)
- [Module template](https://docs.abp.io/en/abp/latest/Startup-Templates/Module)

**Comment by gizemmutukurt** [comment]
****App: Angular UI (MongoDB)** About:**

- ~~In case of errors in the username field, as in other mandatory fields, a warning label should be displayed.~~
![afbef28a-0518-4e6e-88e9-3bc974b64885](https://user-images.githubusercontent.com/99716457/156318705-6cc9bd47-1838-4d53-954e-34ef7dbcf025.gif)

- ~~Language conversions should be improved on all templates.~~

- Permissions is working incorrectly. See, #11768 
- Returns meaningless value in permission setting on User management page in ABP Free Templates, see #11772 
- ~~No characters should be allowed in the phone number field.~~ ([Cancel](https://github.com/abpframework/abp/issues/11742#issuecomment-1058364142))
![image](https://user-images.githubusercontent.com/99716457/156349363-5822c4db-290e-42c0-bf0d-78602217c498.png)

- ~~I cannot delete my own user in user management. Therefore, delete should not appear in the action options.~~
![image](https://user-images.githubusercontent.com/99716457/156362065-f0de8397-ed53-4457-9751-a5fb491af09d.png)

- Tenant user is unable to view the Settings tab. #11775

- ~~Mandatory fields can be specified with "*"~~
![image](https://user-images.githubusercontent.com/99716457/156367225-a8f3b80d-0464-4d67-a11a-abacea4bf69f.png)


**App: Blazor-Server (EF Core) About and  **App: Blazor-WASM (PostgreSQL) About:**** 

- ~~Delete action should not be opened for its own role and user in user and role management. Because they cannot be deleted.~~
![image](https://user-images.githubusercontent.com/99716457/156370167-f25e8664-b3c6-4b0e-951d-942610500adf.png)

![image](https://user-images.githubusercontent.com/99716457/156370277-740aa335-13b8-4149-9c40-35de993fbae7.png)

- ~~Warning message should be given when user removes all permissions for their role  or warning message may be given when removing all admin user roles~~

- ~~Emailing area could be wider, it looks like a button.~~
![image](https://user-images.githubusercontent.com/99716457/156397387-a0cc8a2a-ec8b-44ac-a6b7-26501945fb90.png)

- "Authorization failed!" error observed when clicking "Manage host properties" button. See, #11779 
- ~~User page does not have "search" field.~~
![image](https://user-images.githubusercontent.com/99716457/156501987-ab44544a-c653-4460-855b-6b42fcd4286f.png)


**App: MVC (EF Core) About:**

- "Search" field not working. See,  #11784 
- Unable to view all role names #11785
- ~~No characters should be allowed in the phone number field.~~
![image](https://user-images.githubusercontent.com/99716457/156506991-169330ad-e971-405c-a144-60aeda5551d9.png)


 **Module About:**

- About permissions see, #11793

- ~~MVC and Blazor Server module,The login screen should be improved. It should contain meaningful expressions for the end user.~~
![image](https://user-images.githubusercontent.com/99716457/156587126-59128b4e-8e58-415b-b4be-1298e4bd3671.png)

- Setting tab not displayed in MVC module. See, #11801 

- ~~There is no tenant entry on the login page in modules.~~ (**Cancel**)
![image](https://user-images.githubusercontent.com/99716457/156702800-e3e2023c-8c7d-4b9e-9253-bb11ecc94cad.png)

- Getting permissions error message in blazor-server module. See, #11802

- ~~Language conversions should be improved.~~
![image](https://user-images.githubusercontent.com/99716457/156705621-ebf59298-6b30-4692-8382-204dfd62db63.png)

- ~~Cannot test with a tenant user because the tenant user cannot log in.~~ (**Cancel**)

**Comment by DonVliet** [comment]
_**Emailing area could be wider, it looks like a button.**_

The width of the text will depend on the language. For example in Spanish it may be:

Envío de correo electrónico 

_**No characters should be allowed in the phone number field.**_

The phone number field should be allowed to contain characters. For example it may contain the user's extension:

+1 (505) 434-2322 Ext. 12

**Comment by berkansasmaz** [comment]
Thanks for the information @DonVliet.

---

I'm closing this issue as the actions to be taken have been moved to separate issues.
