### ISSUE TITLE
MVC Startup Template

### ISSUE THREAD

**Issue by Vayth** [abpframework/abp#1182]
Any startup template with normal MVC instead of Razor Pages? I'm still new to Razor and, embarrassingly, have difficulty to change even the default (and hidden?) Login Page..

**Comment by hikalkan** [comment]
MVC approach already works in the startup template. Did you try?

Login page is not hidden, but used as a library. What changes do you need on the login page?

**Comment by Vayth** [comment]
Something like branding or editing the html.
It's the same when I create MVC default template in VS (non-ABP), account management is there in pages folder, but hidden and I had to use `dotnet aspnet-codegenerator` to make them appear so I can edit them. I can't just create a view and controller to the same url /account/login.

Is it the same with ABP? Because I don't see the pages either.
Maybe I'm just not used to UI library (and overriding them) yet.

**Comment by hikalkan** [comment]
You can override any razor page view using [the virtual file system](https://abp.io/documents/abp/latest/Virtual-File-System).
You can see account module files in the repository. For example, Login page is like that: https://github.com/abpframework/abp/blob/master/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml

If you want, you can completely copy the account module into your solution (and remove nuget packages) to edit it: https://github.com/abpframework/abp/tree/master/modules/account
But I don't suggest it since then you can not get updates.

**Comment by Vayth** [comment]
Thanks, it's not as straightforward as creating a physical file as it says, but I'll look for virtual file system more and find some sample.
In the worst case, I'll just create a new project for the frontend.

**Comment by wayneboyles** [comment]
It can be a little daunting but like mentioned the template is an MVC project it's just using razor pages. Delete the pages folder and create a Views and Controllers folder and create the appropriate controllers for the views and it'll work. Inherit your controller from AbpController to get all the goodness that comes with that (current user etc.)
