### ISSUE TITLE
Is the independent module carrying dbcontext transactional?

### ISSUE THREAD

**Issue by bxjg1987** [abpframework/abp#11948]
abp vNext version：5.1.4

Use the CLI command: "abp net xxx - t module -- no-ui"  to create a module. By default, it requires two databases: XXX_ Module and XXX_ Main, is it transactional when the entity in the module and a table in the main database are updated at the same transaction? How is it guaranteed? Or do I have to use distributed events to implement transactions?

**Comment by gterdem** [comment]
Module runs **in-process**, it is not a distributed application. It just uses two different databases.

**Comment by bxjg1987** [comment]
@gterdem Isn't a module a microservice that can be deployed independently?

**Comment by gterdem** [comment]
Module and microservice are different concepts.
You can slice your application into modules; that will end up running on your **host application** because modules do not have runnable application. 
Microservice is an **independently** hosted application itself with its own datastore (database).

You can develop a **monolith application** by dividing your business into modules and later on you can evolve your modules into microservices. This is a different story.

About your question; <s>using multiple databases in a monolith application is still a subject of **in-progress transaction** which is already handled by unit of work. </s>
Edited: Check https://github.com/abpframework/abp/issues/11948#issuecomment-1071162824

**Comment by bxjg1987** [comment]
@gterdem Thank you very much for your patience

when use the CLI command: "abp net xxx - t module -- no-ui" to create a module. It will create a XXX.Host project, which can run, and the interfaces exposed by this module can be called.  Does the host project only facilitate the use of development modules in the development stage?

If the module in the application contains its own independent database, how does UOW implement transactions? As far as I know, in Net core, transactionscope does not support cross database transactions.

**Comment by gterdem** [comment]
> when use the CLI command: "abp net xxx - t module -- no-ui" to create a module. It will create a XXX.Host project, which can run, and the interfaces exposed by this module can be called. Does the host project only facilitate the use of development modules in the development stage?

Exactly. _Host folder_ contains sample runnable application for you to run and test. 

> If the module in the application contains its own independent database, how does UOW implement transactions? As far as I know, in Net core, transactionscope does not support cross database transactions.

I had to check this explicitly and you are right. **Making a single transaction using multiple databases** is a different subject that is related with DBMS. Since ABP UnitOfWork is not coupled with db providers, it doesn't quarantee transaction between multiple and/or various db providers.

As a sample, consider the code piece that represents repositories related with different databases:
```csharp
using(var ouw = _unitOfWorkManager.Begin()){
  await myRepository.DoSomethingAsync(); 
  await myOtherRepository.DoSomethingElseAsync();
  await uow.CompleteAsync()
}
``` 
`uow.CompleteAsync()` **commits one by one** but they are still independent transactions. If any of them fails, it throws exception and that's it. It can not know how to roll-back the previous transaction because it can be a completely different provider. So, there is no quarantee here. 
Best way to handle transaction using multiple databases is to handle manually by the developer since it relies on the db providers.

**Comment by bxjg1987** [comment]
So, if I want to develop a micro service, I should use the ABP application project template instead of the module project template, right? If so, each microservice has independent basic information, such as user role settings, etc, This does not seem to be a good way.

In addition, in an application, establishing an independent database for the module makes the transaction processing difficult because it has to deal with complex cross database transactions.

For using ABP for microservice development, I became confused!

Thank you again!
