### ISSUE TITLE
[eShopOnAbp] Use `Logger` injected object instead of static `Log` method

### ISSUE THREAD

**Issue by rqx110** [abpframework/abp#11958]
In all `xxxEventHandler` classes, I saw that it denpend on `Serilog` and use it's static method to log logs, e.g.

https://github.com/abpframework/eShopOnAbp/blob/2978b8870a89f89399e12145cd9187a88c9d7dd8/shared/EShopOnAbp.Shared.Hosting.Microservices/DbMigrations/EfCore/DatabaseEfCoreMigrationEventHandler.cs#L79

It works, but why not use the `Logger` object just like:

https://github.com/abpframework/eShopOnAbp/blob/2978b8870a89f89399e12145cd9187a88c9d7dd8/shared/EShopOnAbp.Shared.Hosting.Microservices/DbMigrations/MongoDb/DatabaseMongoDbMigrationEventHandler.cs#L112

**Comment by gterdem** [comment]
Probably because of not to bother with replacing [NullLogger instance](https://github.com/abpframework/eShopOnAbp/blob/2978b8870a89f89399e12145cd9187a88c9d7dd8/shared/EShopOnAbp.Shared.Hosting.Microservices/DbMigrations/MongoDb/DatabaseMongoDbMigrationEventHandler.cs#L53) :)

Didn't think much over it though as long as it [write logs async](https://github.com/abpframework/eShopOnAbp/blob/2978b8870a89f89399e12145cd9187a88c9d7dd8/shared/EShopOnAbp.Shared.Hosting.AspNetCore/SerilogConfigurationHelper.cs#L27) and we are using Serilog anyways.

Do you think it is important? Do you think ILogger should be injected? Please discuss.

> Not: Not a generic discussion like [Should I use Microsoft.Extensions.Logging.ILogger<T> or Serilog.ILogger?](https://github.com/serilog/serilog-aspnetcore/issues/104) but related to event handlers specific.

**Comment by rqx110** [comment]
For design, we always say "depend on abstraction (interface), not on details" [DIP(Dependence Inversion Principle)], here eventhandle depend upon Serilog (details). 
Of course it works, but as an official example we can do better. from example we want not just learn how to create a microservice application, but also want to learn your best practices and your best design

This is my opinion, if there is an error, please correct it. Thanks

**Comment by enisn** [comment]
Hi @rqx110 
Of course, we don't approve this approach, but there were some different and more important things to do, that's why we just used it like that. Eventually, we'll update everything as it should be as a best practice. 

If you want to see these changes as soon as possible, PR is always welcome 😉 

I absolutely agree with you but there were some special cases that prevents us to use `Microsoft.Extensions.Logging.ILogger`.

All the database queries while migrating are shown up in the logs & console and it was impossible to understand what was going on. So we replaced it as NullLogger once but it's not a final decision even it's not a decision, we'll work on it later.

**Comment by gterdem** [comment]
In my opinion, practically, you can not always build an application with best practices especially when the future of that code piece (say it a module or a feature) is uncertain. So, you aim for the functional PoC and postpone the _long but correct way_. In an iterative way, continuously refactoring the code-base for scalability and maintenance.

I fully agree with @rqx110 about that as an official example, we should apply the `Dependency Inversion Principle` however in this case we are removing these handlers: https://github.com/abpframework/abp/issues/12080.

Thank you @rqx110, please continue with your feedbacks! We should always improve our code-base.

**Comment by rqx110** [comment]
since https://github.com/abpframework/abp/issues/12080 removes these handlers. I close this issue.
