### ISSUE TITLE
How to get the `ApplicationMenu` from `WebApi`

### ISSUE THREAD

**Issue by akinix** [abpframework/abp#1260]
i use the `SPA` web app.
need to get json data from `IMenuManager` `IBrandingProvider` `IToolbarManager`.
i did not find the appservice or webapi which can get the json in the source .

can be added  `IMenuManager` ... into `AbpApplicationConfigurationAppService`?

like this:
``` csharp
// in ApplicationConfigurationDto.cs
[Serializable]
public class ApplicationConfigurationDto
{
    public ApplicationLocalizationConfigurationDto Localization { get; set; }
    // ...

    // add
    public ApplicationMenuDto MainNavbarMenu { get; set; }
    public ApplicationMenuDto UserMenu { get; set; }
    public ApplicationMenuDto MainNavbarToolbar { get; set; }

    public ApplicationBrandDto Brand { get; set; }
}

// in AbpApplicationConfigurationAppService.cs
public virtual async Task<ApplicationConfigurationDto> GetAsync()
{

    return new ApplicationConfigurationDto
    {
        Localization = await GetLocalizationConfigAsync(),
        // ...
        MainNavbarMenu = await GetMainNavbarMenuAsync(),
        UserMenu = await GetUserMenuAsync(),
        MainNavbarToolbar = await GetMainNavbarToolbarAsync(),
        Brand = GetBrand().
    };
}

protected virtual Task<MainNavbarMenuDto> GetMainNavbarMenuAsync()
{
    var menu = await _menuManager.GetAsync(StandardMenus.Main);
    // map to MainNavbarMenuDto and return
}

// ...

```
i can open a new branch to implement it, and then submit the pull request.

**Comment by hikalkan** [comment]
Hi @akinix 

We don't intent to bring these stuff to API, because;

First of all, these are UI-related things and not good to be in API. I mean an API should not provide UI specific things. This is not the most strong reason and there may always some exceptions, but a good reason.

These were implemented for Mvc UI. We think to re-implement these per UI-framework. For example, when we create a SPA UI, it is not proper to get menu from server. The menu should be a part of the UI. Why we want to add a new menu item to server from backend developers when we need add a new menu item as frontend developer? In addition, a single application may have multiple UIs (SPA, MVC, mobile...) each have different set of functionalities and menu elements. So, each application should manage its UI itself.
