### ISSUE TITLE
OpenIddict integration improvements

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#12662]
When I was working on https://github.com/abpframework/abp/pull/12624 I had some notes as improvement points.

- [x] Should we add `OpenIddict.Validation.AspNetCore` and `OpenIddict.Validation.ServerIntegration` NuGet package dependencies to our `Volo.Abp.OpenIddict.AspNetCore` package. I normally like minimal dependencies. But, in this case, I see no way to properly use our package without these. Also, `Volo.Abp.OpenIddict.AspNetCore` package is only needed for the application that serves the OpenIddict, none of our other packages depending on it. What do you think? https://github.com/abpframework/abp/pull/12678/commits/6bb9514a1a775bfdcd1063be48c7e6e9c63ddb9d
- [x] Rename `IdentityServer` project to `AuthServer` in the startup template (also consider changes needed on solution creation in ABP CLI, updating documentation screenshots, etc).
- [x] _I needed to make a change in swagger configuration for HttpApiWithIds project: `Swagger workaround: options.ResolveConflictingActions(x => x.First());`. Otherwise, we are getting errors since there are multiple endpoints with the same name. Is there a way to overcome this custom config. Otherwise, everyone installing our OpenIddict module and using swagger will need to do that._ https://github.com/abpframework/abp/pull/12624/commits/b8b8431124bcbf55d0ddafab66eaf9c2b91cbdb6
- [x] Our internal applications should not ask for consent (clients should use Implicit consent). I made it for the app template, check if there is another place that uses explicit consent.
- [x] We are [adding clientid as sub](https://github.com/abpframework/abp/blob/32c588e9b5e4bfd7f0dec133fdf9df2add818844/modules/openiddict/src/Volo.Abp.OpenIddict.AspNetCore/Volo/Abp/OpenIddict/Controllers/TokenController.ClientCredentials.cs#L32) in the client credentials flow. Isn't that dangerous. Because, `sub` (interpreted as user id) is the only way that we know if the request is related to a user. But, in this case, it is not an id of a user. At least, it will break our audit log logic, or we will get error when we try to get the user from database. I am not sure if IdentityServer was doing the same. I remember that IDS was not setting `sub` (and also username) for client credentials flow.

**Comment by hikalkan** [comment]
@kevinchalet what do you think about this:

>We are [adding clientid as sub](https://github.com/abpframework/abp/blob/32c588e9b5e4bfd7f0dec133fdf9df2add818844/modules/openiddict/src/Volo.Abp.OpenIddict.AspNetCore/Volo/Abp/OpenIddict/Controllers/TokenController.ClientCredentials.cs#L32) in the client credentials flow. Isn't that dangerous. Because, `sub` (interpreted as user id) is the only way that we know if the request is related to a user. But, in this case, it is not an id of a user. At least, it will break our audit log logic, or we will get error when we try to get the user from database. I am not sure if IdentityServer was doing the same. I remember that IDS was not setting `sub` (and also username) for client credentials flow.

Thanks.

**Comment by kevinchalet** [comment]
OpenIddict itself - even the very first release - has always used `sub` as a way to represent the entity ID, no matter if the represented entity is a user, an application (e.g when using the client credentials grant) or anything else. I guess it was the right thing to do that at the time because it's the approach that was formally adopted by RFC9068 in October 2021 😃 

![image](https://user-images.githubusercontent.com/6998306/169296412-9f0e9cb2-5e66-404f-a3ee-4ba94e70ba0f.png)

https://datatracker.ietf.org/doc/html/rfc9068#section-2.2

But as you said, it definitely has security implications and they were correctly identified in RFC9068, as it recommends preventing clients from choosing their own `client_id` to avoid collisions:

![image](https://user-images.githubusercontent.com/6998306/169297137-e6c528e9-6291-4f57-b38f-f1b9b6d85050.png)

https://datatracker.ietf.org/doc/html/rfc9068#section-5

If you allow choosing an arbitrary `client_id`, I'd recommend using a separate/ABP-specific claim to convey the type of the represented entity. It's the approach we used in Orchard:
  - https://github.com/OrchardCMS/OrchardCore/blob/b8af0067d315db9517a34ec34aeb0c3476f9e9b7/src/OrchardCore/OrchardCore.OpenId.Core/OpenIdConstants.cs#L7
  - https://github.com/OrchardCMS/OrchardCore/blob/b8af0067d315db9517a34ec34aeb0c3476f9e9b7/src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/AccessController.cs#L453-L454
  - https://github.com/OrchardCMS/OrchardCore/blob/b8af0067d315db9517a34ec34aeb0c3476f9e9b7/src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/UserInfoController.cs#L52-L62

**Comment by maliming** [comment]
>  Should we add OpenIddict.Validation.AspNetCore and OpenIddict.Validation.ServerIntegration NuGet package

OK, I will add it.


> I needed to make a change in swagger configuration for HttpApiWithIds project: Swagger workaround: options.ResolveConflictingActions(x => x.First());

Fixed by https://github.com/abpframework/abp/commit/b8b8431124bcbf55d0ddafab66eaf9c2b91cbdb6

> We are [adding clientid as sub](https://github.com/abpframework/abp/blob/32c588e9b5e4bfd7f0dec133fdf9df2add818844/modules/openiddict/src/Volo.Abp.OpenIddict.AspNetCore/Volo/Abp/OpenIddict/Controllers/TokenController.ClientCredentials.cs#L32) in the client credentials flow.

I removed the `sub` claim from `ClaimsIdentity` and added `client_id` as the default claim to be compatible with the previous design. 
https://github.com/IdentityServer/IdentityServer4/issues/2362#issuecomment-395213591
https://github.com/abpframework/abp/pull/12678/commits/faee4bce950bc5be971d4718e954edcc1b5786bf

> Rename IdentityServer project to AuthServer in the startup template (also consider changes needed on solution creation in ABP CLI, updating documentation screenshots, etc).

I rename the `separate-identity-server` parameter to `separate-auth-server` but still support the `separate-identity-server`.

**Comment by hikalkan** [comment]
Thanks @kevinchalet and @maliming for your comments.
