### ISSUE TITLE
Angular UI project - @swimlane/ngx-datatable incompatible to rxjs version

### ISSUE THREAD

**Issue by BeckerTim** [abpframework/abp#13025]
ABP Framework version 5.3.0
Angular UI
Database provider: EF Core
An unhandled exception occurred: ENOENT: no such file or directory, lstat 'C:\abp\angular\node_modules\@swimlane'

1. abp new someProject -u angular
2. Npm Install
3. Ng serve

Hello, I had some issues with the Angular UI. I created a new Project and followed the instructions of the tutorial https://docs.abp.io/en/abp/latest/Getting-Started-Running-Solution?UI=NG&DB=EF&Tiered=No

I tried to start the angular app and got the mentioned error.
I found a solution by updating the rxjs version. Afterwards i had to install the module with the  legacy peer deps command.

Can anyone recreate this issue?

Kind regards, 
Tim B.

**Comment by mahmut-gundogdu** [comment]
I have tried "yarn" and it works without issue.  When I use npm, CLI throws warnings. but still, the app is working. Also, I didn't get a warning or an error related to Rxjs.  
I couldn't produce your case.
<img width="765" alt="image" src="https://user-images.githubusercontent.com/2217899/174259148-06b740bb-8232-4389-bd50-17e4c0429f67.png">


Not: I've closed accidentally

**Comment by BeckerTim** [comment]
Thank you very much. 

I tried it again today and ran into the same issue. Maybe its about the node / npm version:

I use npm on version 8.3.1. On npm install i received the same warnings as you but it ran trough. On ng serve still the same error. 
![image](https://user-images.githubusercontent.com/84566189/174266127-76bd08b5-6b39-4195-b985-61e376cb82fa.png)

Once installed the missing module it started compiling resulting  in a bunch of errors like this:
![image](https://user-images.githubusercontent.com/84566189/174268420-b1c442a6-d3b3-4895-97cf-649a5af0c823.png)

I saw there was an issue due to that error at the swimlane repo aswell this february.
(https://github.com/swimlane/ngx-datatable/issues/2073)

the local rxjs version is currently 6.6.0 it should be 7.4.0 or higher.

**Comment by mahmut-gundogdu** [comment]
What is your node and npm version ?
I am a little bit confused about the issue. I have checked  ng-theme-shared uses simlane/ngx-datatable version is 19.
https://github.com/abpframework/abp/blob/rel-5.3/npm/ng-packs/packages/theme-shared/package.json

and ngx-datatable v19 uses rxjs 6.6
https://github.com/swimlane/ngx-datatable/blob/release/19.0.0/package.json

<img width="647" alt="image" src="https://user-images.githubusercontent.com/2217899/174284450-7b39b711-5c22-4df4-a3eb-b05a99cbb983.png">

Can you share your project or can you create a empty new project and upload them ? Because I couldn't produce yet.

**Comment by BeckerTim** [comment]
npm version - 8.3.1

node version - 16.14.0

In compairsion to your image 
i am missing two packages while npm install.


![image](https://user-images.githubusercontent.com/84566189/174285557-aabf4f31-239c-4718-a84e-1d11f7698a16.png)

the two packages missing are those who raised as npm warnings.

**Comment by BeckerTim** [comment]
yarn worked fine but also mentioned warings with ng-bootstrap and ngx-datatables.
![image](https://user-images.githubusercontent.com/84566189/174294890-0e4a77fd-d2dd-4c6d-9603-01ca3b0b18b6.png)

**Comment by BeckerTim** [comment]
> yarn worked fine but also mentioned warings with ng-bootstrap and ngx-datatables. ![image](https://user-images.githubusercontent.com/84566189/174294890-0e4a77fd-d2dd-4c6d-9603-01ca3b0b18b6.png)

I took a deeper look inside the ng-packs folder and wittnessed ng.theme.shared and ng.components both refer to the dependancies in ng.core which refers to packs/utils

it seems it is in angular v10

![image](https://user-images.githubusercontent.com/84566189/174303112-778de323-fb75-4878-a1bc-49af2519c6fe.png)

maybe this is causing the issue

**Comment by nguyenhmtriet** [comment]
It seems to me that the error is coming from the following: 
- @abp/ng.account (v5.3.0) has dependency on -> @abp/ng.account.core (v.5.3.0) & @abp/ng.theme.shared(v.5.3.0)

- @abp/ng.account.core (v.5.3.0) has dependency on -> @angular/core & @angular/common >= v12.0.0 (*)

=> **This is important that** @abp/ng.theme.shared depends on @swimlane/ngx-datatable (@v.19.0.0)
=> Due to using @swimlane@ngx-datatable@19.0.0 has dependencies on @angular (~11.0.2) (**).

From (*) & (**) so that there is the conflict with @abp/ng.account.core (in use @angular v12) and @swimlane is in use @angular v11.

![image](https://user-images.githubusercontent.com/24971905/174352721-5045ec21-2645-4e13-acb7-630054934673.png)


The solution is to migrate @swimlane/ngx-datatable to v20.0.0

**Comment by BeckerTim** [comment]
> It seems to me that the error is coming from the following:
> 
> * @abp/ng.account (v5.3.0) has dependency on -> @abp/ng.account.core (v.5.3.0) & @abp/ng.theme.shared(v.5.3.0)
> * @abp/ng.account.core (v.5.3.0) has dependency on -> @angular/core & @angular/common >= v12.0.0 (*)
> 
> => **This is important that** @abp/ng.theme.shared depends on @swimlane/ngx-datatable (@v.19.0.0) => Due to using @swimlane@ngx-datatable@19.0.0 has dependencies on @angular (~11.0.2) (**).
> 
> From (*) & (**) so that there is the conflict with @abp/ng.account.core (in use @angular v12) and @swimlane is in use @angular v11.
> 
> ![image](https://user-images.githubusercontent.com/24971905/174352721-5045ec21-2645-4e13-acb7-630054934673.png)
> 
> The solution is to migrate @swimlane/ngx-datatable to v20.0.0

Indeed, but this wont do it at all. 

1. abp/ng.theme.shared -> @ng-bootstrap/ng-bootstrap v12.0.2 -> angular 13
2. abp/ng.theme.shared -> @swimlane/ngx-datatable 19.0.0 -> angular 11 / 20.0.0 angular 12
3. abp/ng.theme.shared -> @abp/ng.core ~5.3.0 -> @abp/utils-> angular ~ 10

Even if we migrate ngx-datatables to v 20.0.0 we will have issues because the version of ng-bootstrap depends on another angular version.

**Comment by nguyenhmtriet** [comment]
Yes, I see so, which is the best version on @abpframewok I can use with the angular app version 12?
