### ISSUE TITLE
Investigate OpenIddict 4.0.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#13089]
https://kevinchalet.com/2022/06/22/openiddict-4-0-preview1-is-out/

**Comment by kevinchalet** [comment]
FYI, there'll be a breaking change in 4.0: the `AddClaim` overloads taking a `destinations` parameter will be removed. A quick search shows that 2 places seem to use these extensions:
  - https://github.com/abpframework/abp/blob/60e55d6e86235ab0ba2b8a4a6c0faac32a1f9114/modules/openiddict/src/Volo.Abp.OpenIddict.AspNetCore/Volo/Abp/OpenIddict/Controllers/TokenController.ClientCredentials.cs#L34-L38

  - https://github.com/abpframework/abp/blob/60e55d6e86235ab0ba2b8a4a6c0faac32a1f9114/modules/openiddict/src/Volo.Abp.OpenIddict.AspNetCore/Volo/Abp/OpenIddict/OpenIddictClaimsPrincipalContributor.cs#L39

In the first case, the destinations can be safely removed because they are always set later anyway in the `foreach` block (and `claim.SetDestinations()` will still be present in 4.0):

https://github.com/abpframework/abp/blob/60e55d6e86235ab0ba2b8a4a6c0faac32a1f9114/modules/openiddict/src/Volo.Abp.OpenIddict.AspNetCore/Volo/Abp/OpenIddict/Controllers/TokenController.ClientCredentials.cs#L54-L57

In the second case, I'm not sure why this code exists as OpenIddict always adds a `client_id` claim to all the access tokens it creates: https://github.com/openiddict/openiddict-core/blob/3.1.1/src/OpenIddict.Server/OpenIddictServerHandlers.cs#L2011-L2013. It's likely this part could be removed too.

**Comment by maliming** [comment]
Thanks @kevinchalet I will check your comments. 👍

**Comment by leonkosak** [comment]
@maliming, is "valid issuers" property still relevant in OpenIddict?
IDS4 theme for valid issuers: https://github.com/abpframework/abp/issues/5589

**Comment by maliming** [comment]
hi @leonkosak 

I think you can configue the `TokenValidationParameters` of `OpenIddictValidationOptions`.

It's same logic.

**Comment by hikalkan** [comment]
Moved to https://github.com/abpframework/abp/issues/14483
