### ISSUE TITLE
"Mvc --tiered" should be a independent Startup-Template

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#1319]
If we make the following three templates:

> Mvc-Simplified
> Mvc-Tiered (Recommended)
> Mvc-Module

It will be better understood by document readers.
And it also highlights that "Mvc-Tiered is less complex and suitable for most scenarios".

**Comment by hikalkan** [comment]
I thought that before, but managing multiple templates are harder to maintain. Not only maintain, but also when we write tutorials. When we have multiple startup templates, we should duplicate all tutorials based on different kind of startup projects.

Also, I think no problem now because template generator (ABP CLI) already cleans projects if you don't want tiered solution.
