### ISSUE TITLE
How do I change the DataSeedContributor Database context/connection string?

### ISSUE THREAD

**Issue by tinonetic** [abpframework/abp#13347]
Hi,

I would like to [seed](https://docs.abp.io/en/abp/latest/Data-Seeding) an existing, none-ABP database that we are integrating to.

I've noticed that the default database for ABP DataSeedContributor is the ABP database.

How do I select a custom database context/connection string for a given DataSeedContributor

I haven't found anything in the DbMigrator module or [the documentation ](https://docs.abp.io/en/abp/latest/Data-Seeding)where I can do this.

Any idea how I can do this?

**Comment by realLiangshiwei** [comment]
See: https://docs.abp.io/en/abp/latest/Connection-Strings

**Comment by tinonetic** [comment]
> See: https://docs.abp.io/en/abp/latest/Connection-Strings

I don't see where and how to apply it with regards to the DataSeedContributor

Would you mind explaining?

**Comment by realLiangshiwei** [comment]
> How do I select a custom database context/connection string for a given DataSeedContributor

The [Connection-Strings](https://docs.abp.io/en/abp/latest/Connection-Strings) document explains how to custom connection strings for a DB context.

**Comment by tinonetic** [comment]
> > How do I select a custom database context/connection string for a given DataSeedContributor
> 
> The [Connection-Strings](https://docs.abp.io/en/abp/latest/Connection-Strings) document explains how to custom connection strings for a DB context.

You posted the same link as above. I don't know if that's intentional. 

Anyway, will resort to manually running a script to seed the other DB for now until I get better help

**Comment by realLiangshiwei** [comment]
> How do I select a custom database context/connection string for a given DataSeedContributor

Because you ask how to custom database context/connection string.

Here explains how to create  a DbContext and set its connection name:
https://docs.abp.io/en/abp/latest/Connection-Strings#set-the-connection-string-name

And here explains how to set a connection string for a DbContext:
https://docs.abp.io/en/abp/latest/Connection-Strings#configure-the-connection-strings

I noticed you mentioned a non-ABP database, but I don't know what it means, I'm assuming it's a database independent of the ABP framework:

First step: https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli#create-the-model

```csharp
public class BookStoreDataSeedContributor : IDataSeedContributor, ITransientDependency
{
    
    public async Task SeedAsync(DataSeedContext context)
    {
        using var db = new BloggingContext();
        ......
    }
}
```
