### ISSUE TITLE
Can't receive DateTime parameter

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#13404]
**I can't receive DateTime parameter while use yyyy-MM-dd HH:mm:ss format**

**ABP V5.3**

![y2GZxHd1pH](https://user-images.githubusercontent.com/24971860/180741917-75880577-e4e5-44ef-b12b-5a3d60f9ac9e.jpg)
![image](https://user-images.githubusercontent.com/24971860/180742622-17007997-6e94-4559-98fc-e59a48791d8d.png)

**Comment by berkansasmaz** [comment]
You can specify the format you want to use in the `ConfigureService` method of your module file as follows.

 ```csharp
        Configure<AbpJsonOptions>(options =>
        {
            options.DefaultDateTimeFormat = "yyyy-MM-dd HH:mm:ss";
        });
```

_ref: https://docs.abp.io/en/abp/latest/JSON#configuration_

Or you can use `Newtonsoft` instead of `System.Text.Json` for the relevant input dto.
```csharp
       Configure<AbpSystemTextJsonSerializerOptions>(options =>
        {
            options.UnsupportedTypes.Add<TestInput>();
        });
```

_ref: https://docs.abp.io/en/abp/4.0/Migration-Guides/Abp-4_0#moved-to-system-text-json_
