### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by thanzen** [abpframework/abp#1352]
I have created a new app through CLI(0.18) and regenerated the migration files to use PostgreSQL.

Test 1:
Run the app without debugging, and the process(IIS Express Worker Process) memory was ~340mb.
Refresh the home page, and the memory increased ~3mb. And keep refreshing the same page, the memory went up steadily(3mb/refresh).

Test 2:
Start the app, and the memory was ~340mb. Do nothing for 15 minutes and the memory went up to 390mb.

**Comment by hikalkan** [comment]
Thanks for reporting. Debug mode may not reflect the real memory usage. We are using ABP framework in some live web sites (abp.io, for example) and didn't see such a continuously increasing memory usage.

However, your case can be true, so we will also check it. If you find anything about that, please share.

Thanks for reporting.

**Comment by thanzen** [comment]
Thanks for your quick response!  I will let you know if I find anything new. Thanks.

**Comment by geffzhang** [comment]
AbpAspNetCoreMvcUiBasicThemeModule  may be memory leak

**Comment by maliming** [comment]
> AbpAspNetCoreMvcUiBasicThemeModule may be memory leak

For example?

**Comment by geffzhang** [comment]
Layout ThemeManager.CurrentTheme.GetAccountLayout() Changed to   ThemeManager.CurrentTheme.GetEmptyLayout();  Memory boom and cpu frenzy

**Comment by geffzhang** [comment]
These four files are log files for the dump analysis process
[coredump.2.dumpheap.xlsx](https://github.com/abpframework/abp/files/3430580/coredump.2.dumpheap.xlsx)
[coredump2_heapobject_analysis(1).log](https://github.com/abpframework/abp/files/3430581/coredump2_heapobject_analysis.1.log)
[coredump2_heapobject_analysis(2).log](https://github.com/abpframework/abp/files/3430582/coredump2_heapobject_analysis.2.log)
[coredump2_object_count_stat.xlsx](https://github.com/abpframework/abp/files/3430583/coredump2_object_count_stat.xlsx)

**Comment by lonwern** [comment]
`BackgroundJobWorker.DoWork()` gets `BackgroundJobStore` instance every 5000ms cause memory leak, because `BackgroundJobStore` will get a `DbContext` instance every time.

https://github.com/abpframework/abp/blob/ad739124c2a87af008a3c0664fdc7c1e741fec87/framework/src/Volo.Abp.BackgroundJobs/Volo/Abp/BackgroundJobs/BackgroundJobWorker.cs#L33-L39

This code will allocate about 200MB of memory per hour, the temporary solution is disable `BackgroundJobs` completely, or use `InMemoryBackgroundJobStore` (also allocate memory but much less than `BackgroundJobStore`).

---

- memory profile with `BackgroundJobStore` (mongodb):

![image](https://user-images.githubusercontent.com/5079364/63565956-c492c080-c59d-11e9-802a-a38d54c6ee88.png)

- memory profile with `InMemoryBackgroundJobStore`:

![image](https://user-images.githubusercontent.com/5079364/63565971-d4aaa000-c59d-11e9-85f0-670ab418266e.png)

**Comment by hikalkan** [comment]
Thanks @lonwern for the additional info. I will check the background job problem & fix.

**Comment by hikalkan** [comment]
@lonwern 

I tried background job worker in a console application and can't see a memory leak.

* Inserted 100.000+ jobs to the database.
* Changed job poll period to 1ms.
* Runned ~5 minutes.
* Memory size remains 35M to 40 MB (when it increased to 40MB, automatically decreases to ~35MB by GC).
* I run the application with CTRL+F5.

As you can see in the code, we are using ServiceScopeFactory.CreateScope() to create & dispose a scope, so allocated memory (including DbContext) is being cleared by the end of the using statement.

Can it be different in a web application? I don't suppose.

**Comment by thanzen** [comment]
I tried version 0.21, and the memory looks stable. Maybe I should close this issue. @hikalkan, how do you think?

**Comment by maliming** [comment]
Abp recently solved some problems and also upgraded to net core 3.0. Perhaps the memory leak problem no longer exists. :)
