### ISSUE TITLE
abp/microservice Cannot resolve parameter 'Volo.Abp.Identity.Identity "UserManager'"

### ISSUE THREAD

**Issue by thihoa0719** [abpframework/abp#13598]
I tried to use IdentityUserManager in the Application layer, but the error said: "Cannot resolve parameter 'Volo.Abp.Identity.Identity "UserManager'""

How to fix it? Am I missing the configuration in the ConfigureServices?

Thanks

**Comment by enisn** [comment]
Hi @thihoa0719 

Can you please share some information about your project that you face the issue


* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by thihoa0719** [comment]
> Hi @thihoa0719
> 
> Can you please share some information about your project that you face the issue
> 
> * Your **ABP Framework version**.
> * Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
> * Your database provider(EF Core/MongoDB)
> * Exception message and **stack trace** if available (check the logs).
> * Steps needed to **reproduce** the problem.
I'm using the ABP 5.1.4. Use Application to build API.
The issue is the contructor cannot resolve. I have no where to configure.
App service like this:
```
public class UserAppService : ApplicationService, IUserAppService    {
IdentityUserManager _userManager;
public TestAppService(IdentityUserManager userManager) 
{
_userManager = userManager;
}
}
```

**Comment by maliming** [comment]
hi @thihoa0719 

Check your depends modules. 

https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpIdentityDomainModule.cs#L24
