### ISSUE TITLE
There are too many 130 sub-folders in the "framework" .

### ISSUE THREAD

**Issue by vioKamran** [abpframework/abp#13658]
Hello dear teams

I have a few questions for you .

There are too many sub-folders in the "framework" folder, and in my opinion, the solution is to summarize four folders:
Like Framework N-o-p C-ommerce 

Core
Data
Http
Service

and each of the csproj files of the project classes:

```
<TargetFramework>net6.0</TargetFramework>
<TargetFramework>netstandard2.0</TargetFramework>
```

Classify and separate in csproj files

And I ask you why there are so many classes and folders in the "framework" folder and what is the reason?

I drew this picture and gave an example so that oop can create folders and files like this.
👇👇👇👇

Core
![image](https://user-images.githubusercontent.com/6240530/184163825-8f06ecb6-21a7-4669-8de2-73510201b6a8.png)

Data
![image](https://user-images.githubusercontent.com/6240530/184163959-4df5a56f-672b-4754-a383-a04200e869cd.png)

Http
![image](https://user-images.githubusercontent.com/6240530/184164026-df328fb2-c06c-4a63-a141-de1ecd379ece.png)

**Comment by vioKamran** [comment]
Hello ???
is there no one

**Comment by vioKamran** [comment]
Hello
@hikalkan
@gterdem

**Comment by vioKamran** [comment]
If I wrote the sentences in bad English.
Tell me, so that I can correct the English sentence again.

**Comment by gterdem** [comment]
Each folder corresponds to a different nuget packages. These are framework modules, mainly used to **abstract** some functionality. Also, I don't think it will be a good understanding to summerize them in numerous categories.

It is better to explain in samples:
**Volo.Abp.EventBus.Abstractions** contains interfaces for event handling etc, as name implies; it is an abstraction to be implemented.

**Volo.Abp.EventBus** is the local and distributed event bus implementations hence references to **Volo.Abp.EventBus.Abstractions**.

**Volo.Abp.RabbitMQ** references to RabbitMQ.Client package and contains the configuration and implementations for channel/queue, seralization/deserialization so that you don't need to do manually.  

**Volo.Abp.EventBus.RabbitMQ** is a combination package for both `Volo.Abp.RabbitMQ` and `Volo.Abp.EventBus` which allows using RabbitMQ as an eventbus seamlessly. Same goes with Kafa, Azure or an other 3rd party library.

If we don't abstract and use Volo.Abp.EventBus merged with all RabbitMQ, Kafka, Azure etc configurations; it would be a mess since why to keep RabbitMQ and Azure configurations if you want to use Kafka for eventbus, right?

Each abstractions are done based on **requirement** for the dependencies at the time.

It may be a bit hard to visualize and understand but if you follow dependency graph in-between the layers of an abp application, that should help you to understand better.

**Comment by vioKamran** [comment]
Thank you😊🙏 And I have a few questions for you .

Does this framework support the implementation architecture for the future of ERP?

**Comment by gterdem** [comment]
> Does this framework support the implementation architecture for the future of ERP?

I am not sure what do you mean by `implementation architecture for the future of ERP`. If there is a term for `implementation architecture`, I do not know.

But ERP is a resource planning **application** at the end. Each application can be developed based on different software architectures, doesn't matter how complex or simple the application is. Software architecture depends on team decisions, capability, experience, feasibility etc.

Today, you can write an ERP application as a monolithic, single layer application as it is written in the past if you want to.

The ABP framework supports modular application development. You can build applications from single-layered to DDD-based layered applications. We also provide microservice template for commercial and a microservice demonstration as [eShopOnAbp](https://github.com/abpframework/eShopOnAbp).
