### ISSUE TITLE
Is CreationAuditedAggregateRootWithUser an antipattern?

### ISSUE THREAD

**Issue by wocar** [abpframework/abp#1410]
Why is CreationAuditedAggregateRootWithUser implemented like this? Because supposedly aggregateroot should only reference other aggregateroot via id?

Thank you

**Comment by hikalkan** [comment]
>aggregateroot should only reference other aggregateroot via id

Definitely, if you want to follow DDD rules or want to be able to work with a NoSQL database. But, to be realistic, many EF core developers will not follow this suggestion and will create navigation properties between agregate roots. It is fine as soon as they stick in EF Core. All Microsoft documentation shows samples and suggests it as default.

So, we don't force developers to follow all DDD rules. If they want to have a User property in their aggroot, they can use this one (otherwise they will create their own or will send a PR :)
