### ISSUE TITLE
Blazor.LeptonXLiteTheme.Global

### ISSUE THREAD

**Issue by hippocampeocean** [abpframework/abp#14578]
![Capture d’écran 2022-11-08 090646](https://user-images.githubusercontent.com/113675430/200509362-8e3ae5e6-96f0-4f2e-ace5-6ec149af2bbf.png)
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hello, I have a problem when i generate an app with Blazor-server. The error is below.
AbpException: Could not find the bundle file '/libs/bootstrap/css/bootstrap.css' for the bundle 'Blazor.LeptonXLiteTheme.Global'!

Can you help me please ?

### Describe the solution you'd like

Generate the blazor-server app without problem

**Comment by hippocampeocean** [comment]
I dowloaded the website to blazor-server.
I have add migration + update database to sql server.
I have this error.
Thank you for your help

**Comment by realLiangshiwei** [comment]
Run `abp install-libs` command

**Comment by LovelyWei** [comment]
Same problem for me, tried to run `abp install-libs` but it didn't work

**Comment by tchivs** [comment]
> Same problem for me, tried to run `abp install-libs` but it didn't work

Need to switch to the directory of Blazor.Host to execute `abp install-libs`

If it doesn't work, you can download the source code of this project and find this directory: `abp-6.0.0\modules\setting-management\app\Volo.Abp.SettingManagement.DemoApp\wwwroot` Copy it to the wwwroot of your own Host

**Comment by LovelyWei** [comment]
> > Same problem for me, tried to run `abp install-libs` but it didn't work
> 
> Need to switch to the directory of Blazor.Host to execute `abp install-libs`
> 
> If it doesn't work, you can download the source code of this project and find this directory: `abp-6.0.0\modules\setting-management\app\Volo.Abp.SettingManagement.DemoApp\wwwroot` Copy it to the wwwroot of your own Host

`abp install-libs` still doesn't work. But after copying and pasting the wwwroot folder, it worked. Good solution

**Comment by realLiangshiwei** [comment]
> abp install-libs still doesn't work

What is the output when you run `abp install-libs`

**Comment by LovelyWei** [comment]
I constructed the project following the official Getting Started tutorial but had the same problem, here are the logs.

---
PS C:\Users\LovelyWei\Desktop\test> abp new Test -u blazor-server --tiered -dbms PostgreSQL
[10:57:57 INF] ABP CLI (https://abp.io)
[10:57:57 INF] Creating your project...
[10:57:57 INF] Project name: Test
[10:57:57 INF] Tiered: yes
[10:57:57 INF] DBMS: PostgreSQL
[10:57:57 INF] UI Framework: BlazorServer
[10:57:57 INF] Output folder: C:\Users\LovelyWei\Desktop\test
[10:57:59 INF] Using cached template: app, version: 6.0.1
[10:57:59 INF] Theme: LeptonXLite
[10:57:59 INF] Check out the documents at https://docs.abp.io/en/abp/latest/Startup-Templates/Application
[10:58:00 INF] 'Test' has been successfully created to 'C:\Users\LovelyWei\Desktop\test'
[10:58:00 INF] Creating initial migrations...
[10:58:08 INF] Initial migrations are created.
[10:58:08 INF] Installing client-side packages...
[10:58:09 WRN] YARN is not installed, which may cause package inconsistency, please use YARN instead of NPM. visit https://classic.yarnpkg.com/lang/en/docs/install/ and install YARN
[10:58:09 INF] Found 2 projects.
[10:58:09 INF] C:\Users\LovelyWei\Desktop\test\src\Test.AuthServer
[10:58:09 INF] C:\Users\LovelyWei\Desktop\test\src\Test.Blazor
[10:58:09 INF] Running npm install on C:\Users\LovelyWei\Desktop\test\src\Test.AuthServer
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated

> @fortawesome/fontawesome-free@5.15.4 postinstall C:\Users\LovelyWei\Desktop\test\src\Test.AuthServer\node_modules\@fortawesome\fontawesome-free
> node attribution.js

Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)


> es5-ext@0.10.62 postinstall C:\Users\LovelyWei\Desktop\test\src\Test.AuthServer\node_modules\es5-ext
>  node -e "try{require('./_postinstall')}catch(e){}" || exit 0

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN bootstrap@5.2.2 requires a peer of @popperjs/core@^2.11.6 but none is installed. You must install peer dependencies yourself.

added 379 packages from 265 contributors and audited 380 packages in 16.672s

14 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
[10:58:29 INF] Running npm install on C:\Users\LovelyWei\Desktop\test\src\Test.Blazor

> @fortawesome/fontawesome-free@5.15.4 postinstall C:\Users\LovelyWei\Desktop\test\src\Test.Blazor\node_modules\@abp\asp
Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)


> @fortawesome/fontawesome-free@5.15.4 postinstall C:\Users\LovelyWei\Desktop\test\src\Test.Blazor\node_modules\@abp\aspnetcore.mvc.ui.theme.leptonxlite\node_modules\@fortawesome\fontawesome-free
> node attribution.js

Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

npm WARN bootstrap@5.2.2 requires a peer of @popperjs/core@^2.11.6 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@5.2.2 requires a peer of @popperjs/core@^2.11.6 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 387 packages from 258 contributors and audited 391 packages in 13.182s

10 packages are looking for funding
  run `npm fund` for details

found 10 vulnerabilities (1 low, 4 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\Users\LovelyWei\Desktop\test> cd .\src\Test.Blazor\
PS C:\Users\LovelyWei\Desktop\test\src\Test.Blazor> abp install-libs
[11:27:38 INF] ABP CLI (https://abp.io)
[11:27:39 WRN] YARN is not installed, which may cause package inconsistency, please use YARN instead of NPM. visit https://classic.yarnpkg.com/lang/en/docs/install/ and install YARN
[11:27:39 INF] Found 1 projects.
[11:27:39 INF] C:\Users\LovelyWei\Desktop\test\src\Test.Blazor
[11:27:39 INF] Running npm install on C:\Users\LovelyWei\Desktop\test\src\Test.Blazor
npm WARN bootstrap@5.2.2 requires a peer of @popperjs/core@^2.11.6 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@5.2.2 requires a peer of @popperjs/core@^2.11.6 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 391 packages in 2.333s

10 packages are looking for funding
  run `npm fund` for details

found 10 vulnerabilities (1 low, 4 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by maliming** [comment]
**YARN is not installed, which may cause package inconsistency, please use YARN instead of NPM. visit https://classic.yarnpkg.com/lang/en/docs/install/ and install YARN**
