### ISSUE TITLE
[Discussion] Supporting multiple UI frameworks

### ISSUE THREAD

**Issue by ahmednfwela** [abpframework/abp#14761]
This issue is to discuss possible ways for ABP to handle Integration of UI frameworks in different languages.
related: https://github.com/abpframework/abp/issues/1168

## Splitting the framework
1. ABP framework itself shouldn't actively support UI frameworks and should only focus on the backend side written in c#
2. a new repo called `abp_ui` should be created within the `abpframework` organization, which will be split into multiple folders, each representing a specific UI framework (e.g. mvc, blazor, angular, vue, flutter, etc...) which will then be split into multiple folders (or git modules) for each official module that ABP framework includes.
e.g.
    - `mvc`
      - `core` - represents generic reusable components and helpers for that specific framework
      - `app` - represents the UI displayed for the main app module (a.k.a. `.HttpApi.Host`)
      - `account` - represents the UI displayed for the account module (a.k.a. `.AuthServer`), [this removes the dependency on MVC for the Account module](https://github.com/abpframework/abp/tree/dev/modules/account/src/Volo.Abp.Account.Web/Pages/Account)
      - `template` - represents the startup template which combines UI from other packages
      - `Volo.Abp.SettingsManagement` - represents the UI components for the SettingsManagement module
      - etc...
    - `blazor`
      - same ....
    - `angular`
    - `vue`
    - `flutter`

3. the community can then contribute to the `abp_ui` repo and away from the main `abp` repo, in a style similar to https://github.com/OpenAPITools/openapi-generator where a contributor is elected to be in the technical committee of a language/framework after they made 3+ PRs for that language (the technical committee then gets mentioned in any future PRs or issues related to that language/framework)
4. for any framework to be endorsed, it should at least provide the `core` + `app` + `template` packages AND have at least 2 contributors in the technical committee
5. for a web framework to be endorsed it should also include ui for the `account` module

## Package hosting

- Framework pages should be hosted on their respectable package repository, e.g.
    -  `js`/`ts` on `npmjs.com`
    - `dart` on `pub.dev`
    - `c#` on `nuget.org`
    - etc...
- I suggest a naming convention of `abp[.-_][{framework}[.-_]]{module}`
so a flutter package handling the core module will be named `abp.core` and hosted on https://pub.dev
but a vue package should be named `abp.vue.core` and hosted on npm

## Release cycle

Instead of having all packages follow a specific version convention, I suggest that each package should follow an independent version track.

e.g. `abp.core` on pub.dev can be v1.2.3 while `abp.account`  is v2.5.6

CI/CD tooling should be implemented for new versions of packages to be automatically pushed once a PR is merged onto a `production` branch, while the main development for packages should be in `main`  branch

I also suggest that a PR into the `production` branch should have 2 reviews at least.

---
I have great hopes that ABP will take over the backend development stack in the future, and I would love to know the contributors opinion on this, as well as anyone else.

**Comment by leonkosak** [comment]
I am not a frontend developer, but in 2018-mid 2020 my team developed some Angular applications (using ASP.NET Zero and some prototypes in abp Commercia) and I am really not a fan of npm/yarn.
So many compiler errors, a really long process of frontend application for Docker image, huge list of warnings,....

Of course, Nuget also has it's own "quirks", but the overall experience (at least for my team and me) is far more convenient and pleasant.
Would you at least try [Deno](https://deno.land/) for React/Angular/Vue frontend?

Regarding different versioning values for different abp modules I don't have the best feelings.
If the version for all modules is strictly aligned, then you have minimal potential-compatibility issues.
In the case of different versioning for each module, you get better time-to-deploy (because of far less compilation), but tracking compatibility could be a potential (big) issue.

**Comment by ahmednfwela** [comment]
Deno is an interesting alternative, might be a good idea to use that too.
@leonkosak if versioning follows [Semantic Versioning Specification](https://semver.org/) we can avoid dependency compatibility issues
