### ISSUE TITLE
Why Don`t Have IMustHaveTenant 

### ISSUE THREAD

**Issue by IslamEldeeb** [abpframework/abp#14933]
Dears , 
I have a question why we don`t have IMustHaveTenant in Abp.io (Tenant Id Not Null) ?

**Comment by maliming** [comment]
## IMustHaveTenant & IMayHaveTenant vs IMultiTenant
ASP.NET Boilerplate defines IMustHaveTenant and IMayHaveTenant interfaces to implement them for your entities. In this way, your entities are automatically filtered according to the current tenant. Because of the design, there was a problem: You had to create a "Default" tenant in the database with "1" as the Id if you want to create a non multi-tenant application (this "Default" tenant was used as the single tenant).

ABP Framework has a single interface for multi-tenant entities: IMultiTenant which defines a nullable TenantId property of type Guid. If your application is not multi-tenant, then your entities will have null TenantId (instead of a default one).
