### ISSUE TITLE
abp cli command new: Should prevent user from using special chars in project name.

### ISSUE THREAD

**Issue by seanalford** [abpframework/abp#1508]
I noticed this morning that the `abp new`  command does not prevent users from using special chars in the project name. (i.e. `abp new Acme.Book-Store`)

![image](https://user-images.githubusercontent.com/8544833/61545067-9a853600-aa14-11e9-99cd-e73c73413596.png)

**Comment by seanalford** [comment]
I'm working on this issue.  How should this be handled?  MS project templates seem to replace special chars with an "_" (i.e. Project: `Acme.Book-Store` -> `Acme.Book_Store`)

Any suggestions or objections to this implementation?

**Comment by Xeevis** [comment]
Ideally this should follow same pattern as dotnet cli with it's `dotnet new mvc --name {name}`, since that is also creating .NET Core project. Code for that will most likely be in [templating engine](https://github.com/dotnet/templating/) or maybe even the [cli itself](https://github.com/dotnet/cli) *shrug*.

**Comment by seanalford** [comment]
I think, I'm getting close, but still haven't found the code that processes the project name.  I send Phil at MS an email to see if could point me in the rigth direction.

https://github.com/dotnet/cli/tree/master/src/dotnet/commands
https://github.com/dotnet/cli/tree/master/src/dotnet/commands/dotnet-new

**Comment by hikalkan** [comment]
Thank you guys. Any PR welcome :)
