### ISSUE TITLE
Could have ABP startup template for Avalonia ？

### ISSUE THREAD

**Issue by aihui109** [abpframework/abp#15159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Could have ABP startup template for Avalonia ？

**Comment by berkansasmaz** [comment]
Hi, currently we don't have a plan for supporting `AvaloniaUI`. However, I'm moving this issue to the backlog.

By the way, you can customize one of ABP's startup templates and do it yourself(avaloniaui + reactiveui = 🫶). This process is not as difficult as it seems. If it is not difficult, you might say why ABP does not support it? Because, once official support is provided, the template does not end with the only preparation of the startup template. As you know, we have many modules and their support for a new UI type and the maintenance costs thereafter are quite high.
