### ISSUE TITLE
custom login page - angular

### ISSUE THREAD

**Issue by poplevente** [abpframework/abp#15186]
### Is there an existing article or article request for this?

- [X] I have searched the existing resources

### Describe the article you'd like

Hi All,

is there a new version for creating a custom login page within the angular app?
i followed this article, but does not seem to work. there were multiple issues, which i managed to correct, but still does not seems to work. i got errors like  (more of them)
node_modules/@volo/abp.ng.account/public/components/profile-picture/profile-picture.component.d.ts:30:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

thanks!

**Comment by poplevente** [comment]
or a link or something which helps? note, i'm using the new 7 version

**Comment by cloud0259** [comment]
Hello,
I have the same problem on the base theme.
However, I followed the documentation as well.
I'm using version 6

**Comment by poplevente** [comment]
@cloud0259 and it worked? I'm using the lepton theme.

**Comment by cloud0259** [comment]
@poplevente  No, the page is never replaced despite using ReplaceableComponentService

**Comment by cloud0259** [comment]
@poplevente For information, the login page must be implemented in the back-end.
See this:
https://support.abp.io/QA/Questions/446/How-do-I-customize-login-pages-for-Angular-when-using-new-Authorization-Work-Flow-in-version-31

and
https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface

**Comment by mahmut-gundogdu** [comment]
If your app is angular 14 or older, The error could appear. What is version of your app ?
Node, Abp, an angular versions.

**Comment by mahmut-gundogdu** [comment]
If you want to change login page,  You need use use  ABP Replacable System. https://docs.abp.io/en/abp/latest/UI/Angular/Component-Replacement
If you want to implement your own authentication flow, That is different. But if you want to change login IU , it is easier.  I can write an article.

**Comment by cloud0259** [comment]
@mahmut-gundogdu Yes that could be handy please

**Comment by moiscye** [comment]
Any update on this? ReplaceableComponentsService does not replace the Login component.
![image](https://user-images.githubusercontent.com/22961250/212197840-e3611ce3-9adb-42eb-8244-bba50ce6b16c.png)

**Comment by knoppies999** [comment]
> Any update on this? ReplaceableComponentsService does not replace the Login component. ![image](https://user-images.githubusercontent.com/22961250/212197840-e3611ce3-9adb-42eb-8244-bba50ce6b16c.png)

**Comment by knoppies999** [comment]
> Any update on this? ReplaceableComponentsService does not replace the Login component. ![image](https://user-images.githubusercontent.com/22961250/212197840-e3611ce3-9adb-42eb-8244-bba50ce6b16c.png)

If you get this working please let me know, I am experiencing the same issues.

**Comment by guizmo** [comment]
> Any update on this? ReplaceableComponentsService does not replace the Login component. ![image](https://user-images.githubusercontent.com/22961250/212197840-e3611ce3-9adb-42eb-8244-bba50ce6b16c.png)

I can confirm that Replacement does not work for Login

PS: ok i got it working
[https://docs.abp.io/en/abp/latest/UI/Angular/Authorization#resource-owner-password-flow](https://docs.abp.io/en/abp/latest/UI/Angular/Authorization?&_ga=2.260704589.1583603108.1675718841-898123630.1675033954#resource-owner-password-flow)

the doc says to "Resource Owner Password Flow" which means , in the environment file, remove the "responseType" property.
the login will then happen on the same URL (http://localhost:4200 in DEV instead of the oAuthConfig.issuer "https://localhost:44305")

A couple links that got me there
- [https://gist.github.com/mehmet-erim/dac82931935a465a48802447de501032  (comment https://gist.github.com/mehmet-erim/dac82931935a465a48802447de501032?permalink_comment_id=4167551#gistcomment-4167551)](https://gist.github.com/mehmet-erim/dac82931935a465a48802447de501032?permalink_comment_id=4167551#gistcomment-4167551)
- https://support.abp.io/QA/Questions/2582/Replacement-of-Login-Page-in-angular-is-not-working--i-have-follow-the-replacement-documentation-after-replacement-still-the-page-is-redirect-to-Backend-login-page#answer-976ea0e4-0028-60bf-881a-3a020de2fee2
