### ISSUE TITLE
Application Design & Layout

### ISSUE THREAD

**Issue by seanalford** [abpframework/abp#1522]
How should a real world applcation and it's respective modules be orgainzed?  I'll use the Acme.BookStore as an example for this discussion.

# Acme.BookStore
### Use Cases:
-`Acme.BookStore.Book`
-`Acme.BookStore.Inventory`
-`Acme.BookStore.ShoppingCart`
-`Acme.BookStore.Purchase`
-`Acem.BookStore.Return`

# Questions/Discussion

1. Should the main application `use cases` reside within the main application solution/projects?  

- I would vote **_no_**, as it's my understanding that these should reside in one or more service modules, and then be added into the main `Acme.BookStore` application. **_i.e. apb add-module  Acme.BookStore.OperationServices_** 

2. Should each of these use cases be defined in a _**single**_ module since they are all directly related to Book Store operations, or an **_individual_** modules for each use case?

- The purist is me says that each use case would reside within an individual module; however, in a production system I might be tempted to group them in a single module `Acme.BookStore.OperationServices`.

3. How should the service module(s) be organized within the file system?

- `Acme.BookStore` - (repo\Acme.BookStore)
- `Acme.BookStore.OperationServices` - (repo\Acme.BookStore.OperationServices)
- **or**
- `Acme.BookStore.OperationServices` - (repo\Acme.BookStore\Modules\Acme.BookStore.OperationServices

**Comment by hikalkan** [comment]
Hi,

If you want to create your application completely modular;

* You shouldn't have a `Acme.BookStore.Application` project, but you should have `Acme.BookStore.Inventory.Application`, "Acme.BookStore.Purchase.Application"... and so on.
* If each module is developed by a separate team, you can have a separated solution file per module. If you have a single team, a single solution with foldered modules will be more practical.

For example, look at the https://github.com/abpframework/abp/tree/dev/modules/identity module. This is an independent module.

In addition to these modules, you will finally have an application, typically a web application that can consists of a single web project and references to all modules (no need to make this final app layered since it will not have a real code). The only responsibility of this web app to bring all modules together, configure them if needed and setup the asp.net core pipeline.

apb add-module is for [standard modules](https://github.com/abpframework/abp/tree/dev/modules) distributed on NuGet. It is not for your modules (because it can not know where your module project files are located, are they following module standards... etc.), at least for now.

Startup MVC template is not directly suitable for your needs, you should manually fine tune it based on your requirements. Once you understand the module and layering system, you can handle it and create different combination of module configurations.

I hope this explanation helps you.

**Comment by seanalford** [comment]
Thanks @hikalkan!

**Comment by vnetonline** [comment]
@hikalkan 

Surely if we are using the mvc-module template created using the ABP CLI

And follow the conventions we should make the add-module command to add the module to a MVC tiered or default ABP web application

This will be a big plus for ABP .... This usecase I think is very important for companies to use ABP framework don't you think?

**Comment by seanalford** [comment]
I assumed add-module was for adding mvc module templates, and add-package would add standard NuGet module.  So I’m still a little confused.

**Comment by vnetonline** [comment]
That's exactly my thinking too @seanalford

**Comment by seanalford** [comment]
Obviously my assumptions are incorrect accounting to @hikalka. 

Is the abp cli add-module and add-package only for adding ABP developed modules, and packages?

If so how would you go about adding a non ABP developed module that was created with abp new Acme.MoudleName -t mvc-module?

1. abp new Acme.Module1 -t mvc-module
2. abp new Acme.Moduel2 -t mvc-module
3. abp new Acme.ModuelN -t mvc-module
4. How do you create the main app?  Vs mvc template, or abp new Acme.ApplicationName
5. How would you add Acme.Module1-N into Acme.ApplicationName?

**Comment by vnetonline** [comment]
@hikalkan I would be happy to create a video to create modules and then load them using ABP CLI if you are able to share how this can be done

**Comment by seanalford** [comment]
@vnetonline, after reading @hikalkan’s original response I think the abp cli add-module and add-package are only for adding abp developed modules and package. 

I noticed the other day abp cli does not work offline. So it is actually making http calls back to abp host api. I originally thought it was a stand alone project scaffolding cli.

**Comment by vnetonline** [comment]
When you say "ABP developed modules" do you mean modules developed by the ABP team who are working on the framework who then publish them on NuGet ??

If so then why have a mvc-module template ??? I like you would like to develop modules and make them available to my clients. for this to happen, ABP CLI needs to work offline and should look for flies whithin the  folder you are in and read the solution flies and the *.csproj flies and add them to an existing ABP tiered or default MVC application generated using the ABP CLI

What is the difference between add-package and add-module 

My underataing is that:

add-package adds a component like ACME.BookStore.Application which is the project in the MVC template 

add-module adds the mvc-module and all related components or in other words projects like Domain, Domain.Shared, EntityFraneworkCore, Application, Application.Contracts, HttpApI To an MVC (default or tiered solution strictute) web application generated using a ABP CLI 

Is my underataing correct?

**Comment by seanalford** [comment]
@vnetonline, I may be wrong, but yes I believe what @hikalkan was saying in his response to me was that add-module is for adding those standard abp developed modules. I believe they are also planning to provide a premium set of modules later on. 

I’ll let @hikalkan address the rest of your question and I’m just as confused as you are. I’m fact, I’m probably doing more harm than good. 🤣

**Comment by hikalkan** [comment]
I suppose this is related to https://github.com/abpframework/abp/issues/1514#issuecomment-517697367

If not, please write the question as a short text so I can reply it :)
