### ISSUE TITLE
Volo.Abp.EventBus.RabbitMq just support direct mode?

### ISSUE THREAD

**Issue by jiahengaa** [abpframework/abp#1528]
Volo.Abp.EventBus.RabbitMq just support direct mode?
Will more models be supported in the future?

**Comment by hikalkan** [comment]
I think this model works fine for a distributed event bus implementation. I am not a RabbitMq expert, can you explain why we need to support other models and how can we do it?
Thanks.

**Comment by leonkosak** [comment]
@hikalkan RabbitMq is required for EventBus and DistributedEventBus, right?

**Comment by hikalkan** [comment]
>@hikalkan RabbitMq is required for EventBus and DistributedEventBus, right?

It is naturally required if your system is distributed.

However, it not required by the ABP Framework. Default `DistributedEventBus` implementation is in-process and works out of the box. But if your system is distributed, in-process bus will not work as you expect.

**Comment by Enissay** [comment]
> I think this model works fine for a distributed event bus implementation. I am not a RabbitMq expert, can you explain why we need to support other models and how can we do it?
> Thanks.

@hikalkan It is needed because other modes gives more/different advantages over direct mode (read more [**here**](https://www.rabbitmq.com/tutorials/amqp-concepts.html)).

I see in your source code that "direct" is hardcoded (see sample source code below). Up to you to decide how to modify it, here are some suggestions:

- Add as a parameter to `EventNameAttribute`  e.g.: `[EventName("test.exchange", ExchangeType.Fanout)]`

- Add an additional attribute `ExchangeTypeAttribute` e.g.:  `[ExchangeType("fanout")]`

- ...

[**Current implementation**](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EventBus.RabbitMQ/Volo/Abp/EventBus/RabbitMq/RabbitMqDistributedEventBus.cs):
```c#
        public override Task PublishAsync(Type eventType, object eventData)
        {
            var eventName = EventNameAttribute.GetNameOrDefault(eventType);
            var body = Serializer.Serialize(eventData);

            using (var channel = ConnectionPool.Get(AbpRabbitMqEventBusOptions.ConnectionName).CreateModel())
            {
                channel.ExchangeDeclare(
                    AbpRabbitMqEventBusOptions.ExchangeName,
                    "direct",
                    durable: true
                );

                var properties = channel.CreateBasicProperties();
                properties.DeliveryMode = RabbitMqConsts.DeliveryModes.Persistent;

                channel.BasicPublish(
                   exchange: AbpRabbitMqEventBusOptions.ExchangeName,
                    routingKey: eventName,
                    mandatory: true,
                    basicProperties: properties,
                    body: body
                );
            }

            return Task.CompletedTask;
        }
```

**Comment by xirius** [comment]
It is not enough:
https://www.erlang-solutions.com/blog/rabbitmq-quorum-queues-explained-what-you-need-to-know.html

**Comment by 344089386** [comment]
I want to use two communication modes at the same time. I think  @Enissay  suggestion is very good.

**Comment by 344089386** [comment]
I know that mode switching is supported in version 5.3.3, but this does not work with both modes of communication.
