### ISSUE TITLE
Please provide the application layer the custom code needs to be placed in when overriding ABP functionality

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#15564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When you describe how to override the specific functionality in the documentation - there is no indication, where this code needs to be placed. For instance, I want to override `RolePermissionValueProvider`. Where do I need to place my class? Applications? Application Contracts? HttpApi? Usually I'm figuring this out from your class names or the source code. Because the namespace is the same everywhere, in the given case it is `Volo.Abp.PermissionManagement;`.

### Describe the solution you'd like

 Could you please always indicate, which layer the code needs to be placed in?

**Comment by berkansasmaz** [comment]
Hi @alexandis, first of all, sorry for the late reply.

To address your question in general without evaluating it on the basis of `RolePermissionValueProvider`, the short answer to your question actually depends on the situation. In order to understand where to put something, that is, to determine it according to your requirements, you must first understand the dependency tree of the application you are developing. For example, if we take the [application startup template](https://docs.abp.io/en/abp/latest/Startup-Templates/Application), putting something in `**.Domain.Shared` means it can be accessed from every layer, while something you put in the `**.EntityFrameworkCore` layer means that only the `**.EntityFrameworkCore` layer will be valid. As a result, what you add only affects itself and the layers that depend on it.
**Disclaimer:** The access modifier of the added thing is assumed to be `public`.

![layered-project-dependencies](https://user-images.githubusercontent.com/31216880/220569377-6f3dbc9e-e2a6-4edb-ba96-f68d50c5e4fd.png)

 
Also, the ABP Framework itself is independent of our startup templates. Moreover, besides the application startup template, we also have templates such as application no-layers. Therefore, it is not possible to make a recommendation that meets all the requirements and is independent of the use cases of the developed application. However, we try to give as many examples as we can for things that fall outside of such situations.

--- 

Closing the issue. Feel free to re-open or create a new issue if you have further questions.
