### ISSUE TITLE
Do we have something like Abp.Web.SignalR in this version?

### ISSUE THREAD

**Issue by forgotten-warrior** [abpframework/abp#1571]
I would like to implement SignalR in abp.io applications, do we have something like Abp.Web.SignalR in the previous version?

Ref: https://aspnetboilerplate.com/Pages/Documents/SignalR-Integration

**Comment by hikalkan** [comment]
Probably, in some future version, we will see how we add value on top of SignalR by integrating to ABP.

However, you can use it today as you're using in a regular asp.net application.

**Comment by leonkosak** [comment]
Suggestion for adding value on top of SignalR.

Prepare for cluster environments (scale**out**)
https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-with-sql-server

So that in the background, the "state" of real-time communication is "stored" on persistent storage.
Make setting where to store such information (SQL or Redis - SQL is default option).

Redis is used for more intense production environments.
https://dzone.com/articles/signalr-scaleout-with-redis-backplane

abp.io should be ready as much as possible for cluster (scaleout) environments (especially because it is microservice oriented).

I am pretty sure that ANZ chat could have issues if it is distributed via multiple cluster nodes because SignalR does not store connected clients on persistent and shared storage.

**Comment by leonkosak** [comment]
Another adding value (on client-side) - Circuit-Breaker: https://github.com/aspnetzero/aspnet-zero-core/pull/2661

**Comment by leonkosak** [comment]
@hikalkan Any updates on this topic?

**Comment by hikalkan** [comment]
We haven't worked on any specific SignalR integration yet. I think it can already be usable, so this has not a high priority for now. Created an issue to follow: https://github.com/abpframework/abp/issues/2747
