### ISSUE TITLE
With multi tenancy enabled there is a performance issue

### ISSUE THREAD

**Issue by yuvarajass06** [abpframework/abp#15768]
### Enabling Multi tenancy there is a performance issue 
I have called same API with and without Enabling Multi tenancy. Normal call takes around 200ms. Whereas once enabled the multi-tenancy, the same API call takes 13500+ms time. 

### Configuration

 Configure<AbpMultiTenancyOptions>(options =>
            {
                options.IsEnabled = true;
                options.DatabaseStyle = MultiTenancyDatabaseStyle.Hybrid;
            });

Please help me on this, is there a way to increase the performance. Thank you.

**Comment by berkansasmaz** [comment]
Thank you for the information you provided. This problem sounds interesting. I will test this. Before testing, can you download a startup template and try again, by default, multi-tenancy is active in startup templates. Starting from here, we will understand whether the problem is related to the configurations of your current application. Afterwards, if the problem is also exist in an empty startup template, I think we will get faster results if you tell me the template you downloaded with the version information and so on.

**Comment by yuvarajass06** [comment]
Thank you. Not sure. But removing these from DependsOn has resolved the issue. Now any api call takes less than 50ms. 
```
typeof(AbpCachingStackExchangeRedisModule),
typeof(AbpEventBusRabbitMqModule),
```

**Comment by berkansasmaz** [comment]
Actually, removing them means you are now using in-memory cache instead of Redis cache and using local event bus instead of RabbitMQ as event bus.

See: 
- https://docs.abp.io/en/abp/latest/Module-Development-Basics#module-dependencies
- https://docs.abp.io/en/abp/latest/Distributed-Event-Bus-RabbitMQ-Integration
- https://docs.abp.io/en/abp/latest/Redis-Cache

I guess your issue is that the Redis server is not working. Further information can be found at https://stackoverflow.com/a/69371513/9922629.

**Comment by yuvarajass06** [comment]
Thank you. Actually, those are added without even used in the project. The startup template did not have a slowness in API calls, so when I cross checked the libraries used, found these two not required for now. So removed it.
