### ISSUE TITLE
Filtering not working

### ISSUE THREAD

**Issue by jlgarcia-vs** [abpframework/abp#15793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm trying to get filtering a list like this document [https://docs.abp.io/en/abp/latest/UI/Angular/List-Service#how-to-implement-server-side-search-in-a-table](https://docs.abp.io/en/abp/latest/UI/Angular/List-Service#how-to-implement-server-side-search-in-a-table) explain.

I've found two problems:

1) Filter parameter is not in request. "getList()" method of service is called with filter value, but "PagedAndSortedResultRequestDto" type does not contain the filter property and the request is sent without the filter expression.
2) If I change "PagedAndSortedResultRequestDto" to any, filter is sent like another parameter to the backend, but the backend is ignoring it.

It's this a limitation with community framework? If this is so, please update documentation.
If not, what is the problem? Could you give me some advise?

Regards

### Reproduction Steps

Create an abp project with Angular ui.
Follow tutorial and add an input like docs explain [https://docs.abp.io/en/abp/latest/UI/Angular/List-Service#how-to-implement-server-side-search-in-a-table](https://docs.abp.io/en/abp/latest/UI/Angular/List-Service#how-to-implement-server-side-search-in-a-table)

### Expected behavior

Filter sent with request and applied in backend.

### Actual behavior

Filter is ignored.

### Version

7.0.2

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by bariscanyilmaz** [comment]
Hi @jlgarcia-vs, abp framework doesn't support built-in filtering because we can't know how many fields you have and which fields you want to filter. You need to implement your own filter in backend. I will update document. There is a community article how you can [implement filtering](https://community.abp.io/posts/how-to-filter-a-standard-paged-list-in-the-abp-framework-bl31rsn6) in your backend. It is based on blazor app but server-side is same. If you want to filter your results with `list.filter` you need to add `Filter` property in your `PagedAndSortedResultRequestDto`. You can achieve this by creating a new Dto class with `Filter` property and this Dto class inherits from `PagedAndSortedResultRequestDto`. Then, use this Dto in `BookAppService` instead of `PagedAndSortedResultRequestDto`. 

Example code how you can handle `filter` in request.

Create your Dto
 
```cs

//Under the  Application.Contracts/Books  

public class BookRequestDto : PagedAndSortedResultRequestDto
{
  public string Filter { get; set; }
}
```
Update IBookAppService
```cs

//Under the  Application.Contracts/Books  

public interface IBookAppService :
    ICrudAppService< //Defines CRUD methods
        BookDto, //Used to show books
        Guid, //Primary key of the book entity
        BookRequestDto, //Used for paging/sorting
        CreateUpdateBookDto> //Used to create/update a book
{

}
```
Update BookAppService
```cs
//Under the Application/Books

public class BookAppService :
    CrudAppService<
        Book, //The Book entity
        BookDto, //Used to show books
        Guid, //Primary key of the book entity
        BookRequestDto, //Used for paging/sorting
        CreateUpdateBookDto>, //Used to create/update a book
    IBookAppService //implement the IBookAppService
{
    public BookAppService(IRepository<Book, Guid> repository)
        : base(repository)
    {

    }

}

```
