### ISSUE TITLE
Unable to run Angular UI on module

### ISSUE THREAD

**Issue by andmattia** [abpframework/abp#16068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi

create a new module via ABP-CLI
```
abp new MyNewModule -t module-pro -csf -sib
```
I run the Auth+API+UI  and Angular not start

![image](https://user-images.githubusercontent.com/8192217/227463279-7dde725c-66a3-4342-9e33-fce0451fd311.png)

I do a downgrade and check Angular UI it works fine (UI 7.0.3 // API 7.1.0)
```
abp new MyNewModule -t module-pro -csf -sib -version 7.0.3
```

### Reproduction Steps

Create new solution and start

### Version

7.1.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by bariscanyilmaz** [comment]
In the error log, it prints out `item_r1.visible is not a function`. [There is](https://support.abp.io/QA/Questions/4907/BUG-Profile-menu-disappeared-in-711-angular-Lepton-project) a similar bug occured in 7.1.0 and it will be fixed with new patch.  You can solve it using [this approach](https://support.abp.io/QA/Questions/4907/BUG-Profile-menu-disappeared-in-711-angular-Lepton-project#answer-3a0aa74c-773d-98f8-7072-7fd0950968ba) until the new patch released.
