### ISSUE TITLE
ABP CLI should check the latest version from `latest-versions.json`

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#16257]
Currently, it gets the new version from NuGet as seen [here](https://github.com/abpframework/abp/blob/1e21e0f756f60fda1865b2323403323641f85400/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/ProjectModification/VoloNugetPackagesVersionUpdater.cs#L40 ).

Keep this logic and add a new version fetch procedure. The new one will check from the [latest-versions.json](https://github.com/abpframework/abp/blob/dev/latest-versions.json) file.

Other locations using this logic:

- https://github.com/abpframework/abp/blob/07d9e961ccc3d1add1046cb3ef886f65b356d7eb/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Version/PackageVersionCheckerService.cs#L77
- https://github.com/abpframework/abp/blob/07d9e961ccc3d1add1046cb3ef886f65b356d7eb/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Version/PackageVersionCheckerService.cs#L118
- https://github.com/abpframework/abp/blob/07d9e961ccc3d1add1046cb3ef886f65b356d7eb/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Version/PackageVersionCheckerService.cs#L136

Related to https://github.com/volosoft/vs-internal/issues/1469

**Comment by EngincanV** [comment]
If the specified version is not a *release candidate* or *nightly build*, it gets the version from `latest-versions.json` (stable).

https://github.com/abpframework/abp/blob/16345d71a125ce209cd570db59954a68e4b6de2d/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Version/PackageVersionCheckerService.cs#L64

https://github.com/abpframework/abp/blob/16345d71a125ce209cd570db59954a68e4b6de2d/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Version/PackageVersionCheckerService.cs#L195-L208

**Comment by EngincanV** [comment]
If it checks the latest **stable** version, it checks from the `latest-versions.json` file, otherwise, it checks from NuGet and MyGet:

https://github.com/abpframework/abp/blob/07d9e961ccc3d1add1046cb3ef886f65b356d7eb/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Version/PackageVersionCheckerService.cs#L64-L75

https://github.com/abpframework/abp/blob/07d9e961ccc3d1add1046cb3ef886f65b356d7eb/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Version/PackageVersionCheckerService.cs#L191-L215

So, it works as expected. I'm closing the issue.
