### ISSUE TITLE
abp generate-proxy param not worked

### ISSUE THREAD

**Issue by wxyer** [abpframework/abp#16314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

abp generate-proxy -t ng -s dcp  --target shmdPush -m shmdPush --service-type application 
abp generate-proxy -t ng -s dcp  --target shmdPush -m shmdPush --service-type all
tow commands above has no difference. 

### Reproduction Steps

i updage cli version from 5.3.4 to 7.1.1
the cli prompt me @abp/ng.schematics is lower
then i update @abp/ng.schematics version
the wrong result still appear.

### Expected behavior

it should generate all proxy model and api 
but i just get some enum actually

### Version

7.1.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by mahmut-gundogdu** [comment]
Abp cli has issue. It works with application or integration. All didn't supported. it fixed. it will be fixed in v7.2.1
But i have tested with directly abp schematics. it works.

I have marked the service `[IntegrationService]` it didn't create with schematic. (skipped by default)
<img width="621" alt="image" src="https://user-images.githubusercontent.com/2217899/235624272-1b3073ab-e433-46a2-9c2c-318021ce70f6.png">


`npx ng g @abp/ng.schematics:proxy-add`

<img width="885" alt="image" src="https://user-images.githubusercontent.com/2217899/235657924-2ea95f39-0b44-4686-91d7-75deb66d4551.png">
