### ISSUE TITLE
Create a `Volo.Abp.Ddd.Domain.Shared` package.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#16495]

**Comment by hikalkan** [comment]
@maliming can you plaese explain why we need it and what that package will include?

**Comment by maliming** [comment]
Similar to `Volo.Abp.Ddd.Application.Contracts`, It will include the `interfaces` and `constants`.

Someone told me the `Volo.Abp.Ddd.Domain` package is too heavy.

**Comment by hikalkan** [comment]
Which interfaces? Which consts? Can you be more specific?

**Comment by hikalkan** [comment]
If you mean `IRepository`, `IDomainService`... for example, it is impossible to move there. Domain.Shared project's responsibility is not that. These interfaces can not be shared with clients (remember domain.shared package's purpose).

**Comment by gdlcf88** [comment]
Hi all. I think this package can be made for the ETO abstractions.

I was trying to revise [UserEto](https://github.com/abpframework/abp/blob/c8199a2582f9e5302047b9c4360174e30e2e62a2/modules/users/src/Volo.Abp.Users.Abstractions/Volo/Abp/Users/UserEto.cs#L9) and wanted it to support the new entity synchronizer feature (since ABP v7.1). However, the [IEntityEto&lt;Key&gt;](https://github.com/abpframework/abp/blob/c8199a2582f9e5302047b9c4360174e30e2e62a2/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/Events/Distributed/IEntityEto.cs#LL3C1-L3C1) interface is in the `Volo.Abp.Ddd.Domain` package, which contains a lot of infrastructure that doesn't belong to the shared layer (such as the `DomainService` class).

![image](https://user-images.githubusercontent.com/30018771/236671917-487f4de9-37b5-4509-924c-092da226cd5b.png)

If we have a new shared package like @maliming mentioned, domain-shared layer projects can no longer depend on `Volo.Abp.Ddd.Domain`.

**Comment by hikalkan** [comment]
Good point. ETO classes and interfaces can go to that new package. So, @maliming go ahead. Domain package should depend on Domain.Shared. In this way, it won't be a breaking change. Also, please add this new package to Domain.Shared project in layered templates.
