### ISSUE TITLE
Organization units for the Identity module

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#1666]

**Comment by leonkosak** [comment]
Consider using SqlHierarchyId if possible (**if it works also on non-MSSQL databases like PostgreSQL - otherwise not**).
https://entityframeworkcore.com/en/knowledge-base/50594409/entity-framework-core-hierarchyid

https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.types.sqlhierarchyid?view=sql-smo-140.17283.0
With this type you also get "nice helper" methods like GetRoot(), GetLevel() and others.

The representation oh HierarchyId if you make .ToSting
() is "similar" what is in current ABP Code: https://aspnetboilerplate.com/Pages/Documents/Zero/Organization-Units#ou-code


Consider also that one entity could be "located" inside multiple "not connected" levels inside hierarchy.

**Comment by crashsol** [comment]
In many cases, the organization needs sorting. Can you provide a sorting field to enrich its functions

**Comment by maliming** [comment]
hi @crashsol  @mperk is implementing this feature, you can discuss related issues in https://github.com/abpframework/abp/pull/2563.
