### ISSUE TITLE
Set Current Tenant

### ISSUE THREAD

**Issue by tiktb8** [abpframework/abp#1686]
We used to be able to use the UnitOfWorkManager to set the tenant id.

I have a use case where unauthenticated requests need to to querydata and because the entities implement IMultiTenant the query results are always null.

Is there currently a way to disable the implied multitenant filter query a table for an entity that does implement IMultiTenant in order to obtain the TenantID and then set that for use in the session?

**Comment by gdlcf88** [comment]
You should try:
```
            using (_dataFilter.Disable<IMultiTenant>())
            {
                // ...
            }
            CurrentTenant.Change(targetTenantId);
```

**Comment by dicksonkimeu** [comment]
Also, how can I set the current user for such a use case ?

**Comment by gdlcf88** [comment]
> Also, how can I set the current user for such a use case ?

I didn't find a way.

**Comment by maliming** [comment]
Related https://github.com/abpframework/abp/issues/1082

**Comment by hikalkan** [comment]
This is not related to changing the current user. You need to change the current tenant. Use the `ICurrentTenant.Change` method (inject `ICurrentTenant` to your service - it is already available for app services).

There is not `ICurrentUser.Change` because we thought it was not needed. If you think opposite, implement it yourself or convince us that it is needed :)

**Comment by dicksonkimeu** [comment]
The main use is for background services. Where you need run integration events accessed application layer services that are permission protected.

Its has been there on old framework. And we've used it heavily.

**Comment by hikalkan** [comment]
>The main use is for background services. Where you need run integration events accessed application layer services that are permission protected.

Don't use application services from the background jobs. If you use them, you will need to make workarounds for authorization and other aspects. It will also write audit log for the user but actually user has not executed the code.

Application service methods are created to implement use cases of the presentation layer. For background jobs, use the domain layer directly. If you want to reuse some logic in an app service, make the logic reusable (extrace to a service class or move to the domain layer if appropriate).

While re-creating the ABP framework, we are re-thinking on the AspNet Boilerplate features and don't want to add some features leading to wrong code design, generating problems and inconsistencies.
For example, now `ICurrentUser` design is closely related to the current claims and it has some properties like Roles. You also need to change all these properties together in order to make it consistent.

**Comment by dicksonkimeu** [comment]
In real world solutions. There are many cases on running application services for in authenticated users.

We can't avoid them. If you were in the shoes of the developers developing the actual solutions you would see things you can't see at framework level.

It makes it hard to migrate to new framework.

Am curious to see how other developers will migrate existing projects.

**Comment by hikalkan** [comment]
>We can't avoid them.

I just explained how you can easily avoid it and make your code base more clear. I don't say "we never add it", but I should understand if it is really needed. Because if we add it now, it requires a lot of design change and we should understand if it worths. If we copy all AspNet Boilerplate features, why we've re-designed it? Please write me if you have any other problem that can not be solved without this feature.

BTW, ABP is very extensible. You can just re-implement the `ICurrentUser` for your application (by extending the default implementation) and add your `Change` method. You can implement it by using the ambient context pattern as just like [implemented in the AspNet Boilerplate](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp/Runtime/Session/ClaimsAbpSession.cs).
