### ISSUE TITLE
Standalone servers do not support transactions for mongodb

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#16949]
**App:** Angular - MongoDb  `7.3-rc.2`
**Command:** `abp new Angular.MoongoSeperate210623Free   -t app -u angular -m none --separate-identity-server --database-provider mongodb -csf  --version 7.3.0-rc.2`

![image](https://github.com/abpframework/abp/assets/99716457/29448ce9-00e0-40aa-853c-89c31b1b3016)
![image](https://github.com/abpframework/abp/assets/99716457/181727ab-5190-446e-b839-d3c0b67b5f3e)

**Comment by EngincanV** [comment]
Standalone servers do not support transactions in Mongo DB and this is actually a warning message rather than an error. 

> In order to perform multi-document transactions, your MongoDB deployment needs to be either a [replica set](https://docs.mongodb.com/manual/replication/) or a [sharded cluster](https://docs.mongodb.com/manual/sharding/). - From https://www.mongodb.com/community/forums/t/getting-error-mongodb-transactions-with-c-and-the-net-framework/11359

https://github.com/abpframework/abp/blob/fe1ae68b9c07ccf56c3f10bdb4ebf3455b759317/framework/src/Volo.Abp.MongoDB/Volo/Abp/Uow/MongoDB/UnitOfWorkMongoDbContextProvider.cs#L191-L198

It's related to whether the database server supported transactions or not and it seems we can't do anything for that. (we are already catching the exception and show a proper message) @maliming what do you think, should we ignore this exception and close the issue?

**Comment by ebicoglu** [comment]
We should prevent writing these logs. Otherwise customers will open support questions for this

**Comment by gizemmutukurt** [comment]
[logs.txt](https://github.com/abpframework/abp/files/11847395/logs.txt)

**Comment by ebicoglu** [comment]
Check if the server supports this feature.  İf not supported write 1 time warning and do not write multiple logs

**Comment by EngincanV** [comment]
> Check if the server supports this feature. İf not supported write 1 time warning and do not write multiple logs

Okay, I will bypass the actual error log and write the `TransactionsNotSupportedErrorMessage` as a warning message.
