### ISSUE TITLE
How modules supposed to communicate with each other?

### ISSUE THREAD

**Issue by mkmita** [abpframework/abp#1698]
For example i do have one module and i have second module.

Second module has to create entity using function which exists in module one.

How modules supposed to communicate with each other so they not get coupled together?

Local event bus?

There are no docs for that yet maybe somebody could provide a sample if possible?

Thank you for your help in advance.

**Comment by hikalkan** [comment]
There are many different scenarios and most of them are very general software design principles.
Will write documents/tutorials/articles by time for different use cases.

We designed application modules so that every application module (identity, tenant-management... etc) can be developed & deployed independent from each other. They can be parts of a monolith app or they can act as "microservices".

Module A doesn't need to create an entity of module B if you want to make them loose coupled. Module A can not know B's entities at all. Module A can trigger a distributed event that can be meaningful for B, so B can create an entity if necessary.

In another scenario, A can call B's application services or REST APIs, based on your system.

But, that doesn't mean that A can not directly depend on B in any case. That's fairly reasonable for some scenarios. For example, a SaaS module can depend on a Payment module to get payment from tenants. If your app is monolith, SaaS can reference to Payment module and call its services.
One problem with this design is that SaaS module can not use another Payment module because of hard-dependency. To solve this problem, you can create an abstract payment module that is used by SaaS and implemented by the Payment module.

It is not possible to go more details in a GitHub issue. As I said, we will create some articles about this topic.

**Comment by hikalkan** [comment]
BTW, application modules like bounded contexts in DDD. So, you can find many documents on the web about bounded contexts.

**Comment by mkmita** [comment]
One more sample here.

For example i'm building addresses module, and i want address to have relationship with user module (AddressUserRelationship).

I created addresses module and implemented AddressUserRelationship entity and repository in addresses module. 

As i understand acording ddd there is no possibility to have proper joins because scopes of user and addresses module designed to be separate, separate dbcontexts. 

Just want to make sure i'm going into right direction with this.

In this case i should add user module reference to address module. Register abp user module dependency in Addresses module. Use abp user module application services to retrieve users data and make data join with addresses in memory? After join i provide data using dto for front end.

Thank you for your input @hikalkan really appreciate it. I spending a lot of time understanding framework and building modules i'm really big fan of the framework since early aspnetboilerplate. If you need help with something i'm happy to contribute and write some code.

**Comment by xyfy** [comment]
I am looking for some sample codes using abp  for the topic about how a SaaS module used another module.

where can I get it .
