### ISSUE TITLE
CmsKit - BlogPost Content can't be saved on MongoDB

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#17286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

BlogPost `Content` property is saved as `NULL` always in mongodb

### Reproduction Steps

1. Create a new project with MongoDB
2. Add Volo.CmsKit module
3. Add Volo.BlobStoring module
4. Run the project,
5. Add a **Blog** first
6. Add a **BlogPost** and see content is `null`

![image](https://github.com/abpframework/abp/assets/23705418/a73f08e9-7f43-4bec-b5e6-bd02a693ff45)

7. Try to update the same entity, content is still saved as `null`

### Version

7.3.1

### User Interface

MVC

### Database Provider

MongoDB

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by JadynWong** [comment]
After switching to `Form` from `DynamicForm`, `CoverImageMediaId` is also missing.

Update page `ConcurrencyStamp` label is not hidden.

**Comment by enisn** [comment]
Since PR #17287 is merged, I'm closing this issue,

 We'll take a look for this problem separately;

> After switching to `Form` from `DynamicForm`, `CoverImageMediaId` is also missing.
> 
> Update page `ConcurrencyStamp` label is not hidden.

In the source code, it seems there is form, not DynamicForm by default. Did you override the page in your project?

**Comment by JadynWong** [comment]
No, I am not override it. I think it was caused by a change in [56c8590](https://github.com/abpframework/abp/commit/56c85904191af7828bbaef2a5fb6730049dddfba#diff-fa2984bbc917fc05e5df6db159de53411e936868baed0288e37070543f5e7d80R77). Until then use `DynamicForm`.

```razor
<abp-input asp-for="ViewModel.ConcurrencyStamp" hidden />
```

`hidden` attribute is only apply to input element. The label tag is still showing. 

Use `type="hidden"` 
or
Remove `hidden` attribute and add `[HiddenInput]` attribute to `ConcurrencyStamp` 
That will work normal.

**Comment by enisn** [comment]
I've created a new issue for that. Thank you @JadynWong
