### ISSUE TITLE
AngularUI: Prevent to disable account authenticated user self

### ISSUE THREAD

**Issue by masum-ulu** [abpframework/abp#17506]
## The Problem
- **Current user should not disable self**

![image](https://github.com/abpframework/abp/assets/49063256/06c9df9b-cd67-4999-920e-769c42f589d0)

## Todo
- **Remove IsActive property if current user edit self**

**Comment by maliming** [comment]
Also hide the `lock` from the user's actions

<img width="505" alt="image" src="https://github.com/abpframework/abp/assets/6908465/48096d45-89a9-494f-a353-0c90cc24e1b7">

**Comment by gigaiis** [comment]
Hi @masumulu28 
Have you considered handling cases where someone else has disabled an account with an active session?
I mean what happens when user 1 deactivates user 2 while actively using the system? what happens when the token for user 2 expires? (because I think user2 will try to refresh the token at the end of the token expiration, it will end up with an infinite reboot because the authentication server session will still be active, but will throw an exception because the user is deactivated, and this process will happen indefinitely)
