### ISSUE TITLE
ObjectMapper considers adding ProjectTo function.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#1777]
https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4875

**Comment by leonkosak** [comment]
Completely agree! :)

**Comment by hikalkan** [comment]
### About ProjectTo

I am not sure about this feature. I think no meaning to create an abstraction that one to one maps with AutoMapper.

Current `IObjectMapper` interface is simple and easy to implement using different object mappers. But, ProjectTo is a unique feature of AutoMapper. When we add this, it will be hard or impossible to implement IObjectMapper with another library.

So, if we assume that we will always use AutoMapper, why not directly use its own API in the code depends on it? You can inject `IMapperAccessor` and use its full API.

### Design Issue

But... actually there is a bigger design issue with current IObjectMapper. It assumes that all modules uses the same mapping library. What if I want to use AutoMapper in Module A while I want to use TinyMapper in module B. Or what if I change object mapper in the final application where all modules depend on AutoMapper and assumes that it is used by the application.
So, it would be better to contextualize the IObjectMapper.

For example, we can define a `IObjectMapper<TModule>` interface, so you can inject `IObjectMapper<ModuleA>` and you can be sure that you will get the mapper you configured for your module.

You may think that why we have an `IObjectMapper` if we assume a concrete mapping library for a module (current modules directly depends on Volo.Abp.AutoMapper since they define Profile classes).. Well, this may also be a design problem. But there may be two good reasons:

1. Even in this case, final application developer may want to replace one module's object mapper by configuring it via another mapper to gain some critical performance.
2. Not documented yet, but `IObjectMapper` has a powerful feature where you can implement a specific mapping code (from ClassA to ClassB) by implementing `IObjectMapper<ClassA, ClassB>`. This implementation can inject & use any service.

**Comment by hikalkan** [comment]
I created a solution for the design issue I mention above: https://github.com/abpframework/abp/issues/1844

Also, if you need to access AutoMapper's `IMapper` (which can then be used for ProjectTo) when you have an `IObjectMapper` (or `IObjectMapper<TContext>`) reference, you can use `ObjectMapper.GetMapper()` extension method. Be sure that you are using the AutoMapper, otherwise you get an exception.
