### ISSUE TITLE
NGRX in Angular UI template

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#1778]
Hi.

I [noticed](https://blog.abp.io/abp/ABP-v0-19-Release-With-New-Angular-UI) you use NGRX in angular template.

Can you please explain why/how you made decision using NGRX over ngRX or Akita.

Thanks for advance.

**Comment by leonkosak** [comment]
Do you mean "decision using NG**XS** over ng**RX** or Akita"?
As far as I can see trends, NGXS is a rising star (compared to NGRX), because it's simpler to use (code) - ("general advantage").

**Comment by mehmet-erim** [comment]
Hi

We have used NGXS. Because the main goal of NGXS is to reduce boilerplate allowing you to do more things with less.

Also explained in the NGXS documentation:
> Why another state management solution? We asked ourselves that same question before we started on NGXS. After trial and error of several different redux based solutions we decided that they didn’t represent the type of API we wanted and expected from Angular.

See the [Why topic](https://www.ngxs.io/getting-started/why) on NGXS documents

**Comment by sebitsi** [comment]
Sorry i made tipos in my guestion :( . Thanks Leon to correct me. :)

@mehmet-erim I belive you made comparison between main redux based solutions before you
choose one. Can you share it ? 

For now i just try ngRx and i must agree there is too much code need to write.
But in ngRx Core team there are some contributors from Google team (Brandon, Mike, Ward, Viktor, etc…..). I don't know if this is important or not. 

So please share your arguments why you choose NGXS againts others. 

Thanks

**Comment by mehmet-erim** [comment]
I have experienced NGXS for a year. 15-20 people were in the frontend team. Our team easily learned to NGXS structure. We developed a big project and NGXS saved us from the confusion of the structure. Because we modeled the structure with the CQRS pattern with NGXS. The package is highly professional.

1. NGXS can learn easily
2. Less boilerplate
3. The structure which based on RxJS
4. Dependency Injection 
5. Useful decorators 
6. NGXS have an Injection Token for developing plugins (We developed a plugin. [Check this out](https://github.com/ng-turkey/ngxs-reset-plugin))
7. Memoized selectors
8. [Useful plugins](https://www.ngxs.io/plugins)
9. [Lazy loading](https://www.ngxs.io/advanced/lazy)
10. [Action handlers](https://www.ngxs.io/advanced/action-handlers)
11. [State operators](https://www.ngxs.io/advanced/operators)
12. [Life cycles](https://www.ngxs.io/advanced/life-cycle)
...

Just try NGXS with a mini project. I believe you will like the NGXS

**Comment by sebitsi** [comment]
@mehmet-erim Thanks for pointing me to main features NGXS has.
I Will take deep look into it and if i have another questions i will post it here.
