### ISSUE TITLE
Get ApplicationConfiguration too slow

### ISSUE THREAD

**Issue by indexlang** [abpframework/abp#1781]
when I get ：https://localhost:44341/api/abp/application-configuration 
take about 1 minute，how to improve？

**Comment by maliming** [comment]
Steps needed to reproduce the problem.

**Comment by hikalkan** [comment]
It tikes under a second for us. Check your db connection please and try to undertand where it waits.

**Comment by stay2be** [comment]
I have the same problem. I have a remote Postgres database which I'm using locally and in a staging App Service (Linux) on Azure. While using the web app (MVC Pages) locally, everything is fast and I can login with the standard template. Running the same app on Azure is a nightmare. I can't event login because it's so slow.

I've tried scaling up the instance to the maximum, using an Azure SQL database instead. Everything boils down to the ApplicationConfiguration.

Here you can see that the only resource that is pending (forever) is the endpoint where the AppConfig is loaded. The same behavior can be reproduced via the swagger ui.

<img width="688" alt="Screen Shot 2019-10-24 at 21 37 00" src="https://user-images.githubusercontent.com/13693611/67519113-73d73b00-f6a6-11e9-83c3-47d819aa4d0e.png">

This seems to be no direct database problem, as I tested it with different instances and even another type (Postgres vs Azure SQL). Locally, with the same remote db connection, there is no problem. Maybe this is related to Linux or Azure.

Feel free to test the behavior here in this test app with the standard login credentials and no other logic implemented (admin, 1q2w3E*):

https://climmi-service-staging.azurewebsites.net
https://climmi-service-staging.azurewebsites.net/swagger/index.html
