### ISSUE TITLE
User able to login even after deleting user

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#17927]
https://support.abp.io/QA/Questions/6006/user-able-to-login-even-after-deleting-user

**Comment by maliming** [comment]
This is because of the authentication mechanism and **SoftDelete**.

Cookies and tokens are still valid when the user is deleted.
Tables(`settings, permissions`) that use `userid` will have no changes. 

Similar problem: https://github.com/abpframework/abp/issues/8620 https://github.com/abpframework/abp/pull/8676

We can only add some additional checks to prevent this from happening, which will affect performance.

**Comment by leonkosak** [comment]
Additional checks during login process?

**Comment by maliming** [comment]
Do some checks during each request.
