### ISSUE TITLE
Host login to tenants

### ISSUE THREAD

**Issue by wocar** [abpframework/abp#1796]
How can I allow the host to login into any tenant? Any guidance on where to start? Thank you :)

**Comment by hikalkan** [comment]
Like tenant impersonation in [asp.net zero](https://aspnetzero.com/)? Can you explain more please?

**Comment by wocar** [comment]
Thank you for your quick response. I would like the user admin with tenantId: null be able to login into a tenant.

**Comment by hikalkan** [comment]
We solved this problem by creating a tenant impersonation feature in asp.net zero (see https://docs.aspnetzero.com/documents/aspnet-core-mvc/latest/Features-Mvc-Core-Tenant-Management#tenant-user-impersonation).

You can create a similar system, but since it requires changes in a lot of places, it is not easy to explain here.
You can make the host admin user login as tenant admin's user by selecting a tenant. You will use SignInManager just like used in the account module.

**Comment by wocar** [comment]
Ok I’ll take a look and let you know what I achieved thank you.

**Comment by wocar** [comment]
Solved by conditionally disabling the multi tenancy filter in the host side, allowing the host to access certain views. Thank you
