### ISSUE TITLE
How to add Blazor Server Side ?

### ISSUE THREAD

**Issue by NicolasEhrhard** [abpframework/abp#1804]
In Abp.Io 0.21, i want to use **Blazor**. 

I found a tutorial, here at 10:15 (https://www.youtube.com/watch?v=MetcuX1OHD0&list=PLReL099Y5nRd04p81Q7p5TtyjCrj9tz1t&index=8)

So i did exactly what the guy says, but i got an ERR_ABORTED 404 for blazor.server.js file.

Can you help me ?

**Comment by NicolasEhrhard** [comment]
I found something .. I add **app.UseStaticFiles()** in startup.cs and it's working.

It's the right way to do ?

**Comment by Xeevis** [comment]
`app.UseStaticFiles()` is currently I believe the only reliable way to include `/_framework/blazor.server.js`. There are 2 reasons why this doesn't work with ABP's `app.UseVirtualFiles();`.

1) Folder `_framework` isn't whitelisted to serve static content, now it's just wwwroot/Pages/Views/Themes folders. This has to be fixed in ABP source. https://github.com/abpframework/abp/blob/fb4fe908b54e48d44abae022671731d8068126e0/framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/VirtualFileSystem/AbpAspNetCoreContentOptions.cs#L12-L17
2) `blazor.server.js` is an embedded resource in assembly [Microsoft.AspNetCore.Components.Server.dll](https://github.com/aspnet/AspNetCore/blob/a3495751a168c4aa1eb341196d3d7ce5cf161554/src/Components/Server/src/Microsoft.AspNetCore.Components.Server.csproj#L78-L85) and ABP requires explicit declaration of assemblies that include embedded resources.

```
Configure<AbpVirtualFileSystemOptions>(options =>
{
    options.FileSets.AddEmbedded<IServerSideBlazorBuilder>();
});
```

Hope this helps clear things up a bit.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/394#issuecomment-694865006
