### ISSUE TITLE
MVC UI Corruptions after ABP Upgrade

### ISSUE THREAD

**Issue by yusufokaraman** [abpframework/abp#18371]
I upgraded my project, which includes two MVC UIs written in abp, from 3.1.2 to 7.4.2, but there are distortions on my UI screen, I am not sure what to do for them, I am sharing screenshots of the distortions attached. Can you help?
![ui](https://github.com/abpframework/abp/assets/34060382/70c73a93-fdcc-476b-a71c-52cc5bc8b676)
![ui-2](https://github.com/abpframework/abp/assets/34060382/39cf82bb-2cc4-40ce-8512-d25fcd17147d)

**Comment by EngincanV** [comment]
You need to run the `abp install-libs` command. See documentation: https://docs.abp.io/en/abp/latest/CLI#install-libs

Also, to update your existing ABP application from v3.1.2 to v7.4.2, you should update its version by version and follow the [migration guides](https://docs.abp.io/en/abp/latest/Migration-Guides/Index). Otherwise, if you directly update your application from v3.1.2, which is a very old version to v7.4.2 (the latest stable), understandably you would face some issues.

**Comment by yusufokaraman** [comment]
I have made the updates you mentioned. I updated the libs versions in the project, but as you can see on the screen, I see the texts written as dedault on the button. The button I framed with the black box is a dropdown button, when I say activate the user from the drop-down list below, I get feedback that it is active with sweetalert, as it appears in the image, it still appears as inactive on the red background. I think it's a similar problem to the one I mentioned above. While all this is happening, I don't see any errors on the console. Do you have any suggestions on where I should look? 
![tempsnip](https://github.com/abpframework/abp/assets/34060382/6ee14631-da2c-4860-9470-6887c2c02381)
