### ISSUE TITLE
The toaster css doesn't match the screenshot

### ISSUE THREAD

**Issue by ayyash** [abpframework/abp#19152]
https://github.com/abpframework/abp/blob/766a4cd8d36b5ea7c263dc293726f8227e2108be/npm/ng-packs/packages/theme-shared/src/lib/components/toast/toast.component.scss#L15

This built in CSS of the toaster, can it be overridden? Right now it's encapsulated, and hard coded making the override a matter of `!important` selectors. In addition to this, it looks different that the screenshot displayed in the docs here:

https://docs.abp.io/en/abp/latest/UI/Angular/Toaster-Service

**Comment by Sinan997** [comment]
hi, i have produced the problem the toast message looks bad.
![image](https://github.com/abpframework/abp/assets/72804437/26f06821-d381-4a6a-97a3-0ee61293154f)


if you add the code below to the your global style.scss file it will solve your problem. 
```scss
.abp-toast-content{
  flex-direction: column; 
}
```

normally toast message was fixed in 8.1 [with this line of code](https://github.com/abpframework/abp/pull/18976/files#diff-899231a932635bcbf812084751ec1c6f439915c39ff505537dcc33988fdff500R52). i will investigate why it still looks like this in new applications. thanks for creating issue.

**Comment by Sinan997** [comment]
This problem will be fixed in 8.1

**Comment by ayyash** [comment]
can you also use css variables for the colors? like `$lbp-success`? thanks.

**Comment by Sinan997** [comment]
Sadly scss variables aren't not possible for this component case, you can customize the color as below;

```scss
.abp-toast-error{
  background-color: #0f145b !important;
  border: 2px solid #fff !important;
}
```

By the way, there is nothing wrong to use `!important`
