### ISSUE TITLE
Blazor WebApp - When the Authserver is switched, the old logo appears.

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#19510]
**App:** Blazor WepApp - 8.2

![image](https://github.com/volosoft/volo/assets/99716457/c9e633ed-a85b-41df-bb80-e7c3648fb6b9)

**Comment by enisn** [comment]
Not possible to reproduce
![image](https://github.com/abpframework/abp/assets/23705418/67375ca8-bfa2-434d-9e87-670c1e060648)

Since app name is already configured in BrandingProvider: 
https://github.com/volosoft/volo/blob/6ab4ffa24b29907c03275f772743cf9c6b7ce3b9/abp/templates/app-pro/aspnet-core/src/MyCompanyName.MyProjectName.AuthServer/MyProjectNameBrandingProvider.cs#L9

It's not possible to render logo-dark.svg in here. Even this file it's not included in the project or packages. Make sure you execute `abp clean` and `dotnet build /graph` before running

**Comment by enisn** [comment]
LeptonX Lite doesn't support text-logo currently
