### ISSUE TITLE
Allow user to define session timeout 

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#19590]
Users can set this via `SetAccessTokenLifetime`, `SetIdenityTokenLifetime`. But it would be good if we give an interface to set this with an option. I got a feedback from a developer

![image](https://github.com/abpframework/abp/assets/9526587/97f9ccb2-344f-42bf-8011-672aa76f5f74)

**Comment by maliming** [comment]
### Cookies authentication(Identity):

> [SlidingExpiration](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.cookies.cookieauthenticationoptions.slidingexpiration?view=aspnetcore-8.0#microsoft-aspnetcore-authentication-cookies-cookieauthenticationoptions-slidingexpiration)	
The SlidingExpiration is set to true to instruct the handler to re-issue a new cookie with a new expiration time any time it processes a request which is more than halfway through the expiration window.

> [ExpireTimeSpan](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.cookies.cookieauthenticationoptions.expiretimespan?view=aspnetcore-8.0#microsoft-aspnetcore-authentication-cookies-cookieauthenticationoptions-expiretimespan)	
Controls how much time the authentication ticket stored in the cookie will remain valid from the point it is created. The expiration information is stored in the protected cookie ticket. Because of that an expired cookie will be ignored even if it is passed to the server after the browser should have purged it.
This is separate from the value of [Expires](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.cookieoptions.expires?view=aspnetcore-8.0#microsoft-aspnetcore-http-cookieoptions-expires), which specifies how long the browser will keep the cookie.

See https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration#cookie-settings


### Tokens authentication:

Setting Tokens Lifetime: https://docs.abp.io/en/abp/latest/Modules/OpenIddict#setting-tokens-lifetime
