### ISSUE TITLE
Why app template httpapi host projects need wwwroot/libs files and gulpfile ?

### ISSUE THREAD

**Issue by mehmetuken** [abpframework/abp#1979]

**Comment by hikalkan** [comment]
It doesn't have: https://github.com/abpframework/abp/tree/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.HttpApi.Host

HostWithIds (Host with Identity Server) has: https://github.com/abpframework/abp/tree/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.HttpApi.HostWithIds
Because it contains the login page which requires some client side dependencies.

**Comment by mehmetuken** [comment]
@hikalkan my other question how create httpapi project without angular? Cli no-ui only create module template. App template already have host project. just addet --ui none option cli?

**Comment by hikalkan** [comment]
We can add --no-ui option to the app template, but why you have an app without ui :)
For now, you can delete angular after download.

**Comment by mehmetuken** [comment]
Yes im doing right now this method. Beacuse i write my vuejs ui right now. Its good option app template we can write our ui. Thanks the solution.

**Comment by hikalkan** [comment]
Can you create an issue as a feature request for that?

**Comment by mehmetuken** [comment]
#1982
