### ISSUE TITLE
Question about communication between modules

### ISSUE THREAD

**Issue by mkmita** [abpframework/abp#1998]
For example i'm building addresses module, and i want address to have relationship with user module (AddressUserRelationship).

I created addresses module and implemented AddressUserRelationship entity and repository in addresses module.

As i understand acording ddd there is no possibility to have proper joins because scopes of user and addresses module designed to be separate, separate dbcontexts.

Just want to make sure i'm going into right direction with this.

In this case i should add user module reference to address module. Register abp user module dependency in Addresses module. Use abp user module application services to retrieve users data and make data join with addresses in memory? After join i provide data using dto for front end.

Just wondering if this is correct way of module to module communication for monolithic app. I'm not trying to make modules completely separate for now. I just want to have domains separated into reusable modules, trying to understand best practices how to implement those relationships between modules.

Thank you for your input @hikalkan really appreciate it. I spending a lot of time understanding framework and building modules i'm really big fan of the framework since early aspnetboilerplate. If you need help with something i'm happy to contribute and write some code.

**Comment by viewtance** [comment]
The same issue I am confusing too.

**Comment by maliming** [comment]
Although we can learn some through the blogging module, but if there is documentation will be the best. 

https://github.com/abpframework/abp/tree/dev/modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users

**Comment by maxrizwork** [comment]
Same dilemma for me. How to implement a "join" if I have different modules with different DbContext.

**Comment by hikalkan** [comment]
>How to implement a "join" if I have different modules with different DbContext

It is something like "How to join tables in a microservice system where each service has its own database".

Problem is similar because we've [designed](https://docs.abp.io/en/abp/latest/Best-Practices/Index) each mode so that they can be deployed as a independent microservice if needed.

Isn't there any solution?

Performing a join assumes that both module tables will always be in the same database. With this assumption;

* You have two modules: A & B.
* A has entities like A1, A2, A3... and B has entities like B1, B2, B3.
* You want to Join with A1 & B2 entities inside the A module's source code.

Problem: That's not possible because they are in different DbContexts.
Solution:

* Create a similar entity (AB2) to B2 in the A module (you can directly copy or create a similar entitiy with the only properties required for module A).
* Map this entity (AB2) to the same database table with B2.
* To not have problem in your migration, don't include this mapping in the unified migration.

This is just like the AppUser table comes with the startup template. In this was you can join to Identity module's IdentityUser entity (AbpUsers table). For more info, carefully read https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Migrations
