### ISSUE TITLE
Enhance AbpRedisCahce

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#20019]
> Adds the "force reconnect" pattern as described in [azure cache best practices](https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-best-practices-connection), with an implementation modified to retain the pre-existing custom connect logic

https://github.com/dotnet/aspnetcore/pull/45261

**Comment by leonkosak** [comment]
@realLiangshiwei, this is a great improvement! 👍 
What happens, if Redis falls down in a production environment for minimal time and you use abp caching functionality (which uses Redis behind the scenes)? Would abp abstraction layer for caching "swallows" this exception and returns "false" (that desired entity is not in cache) or application would stop working because of Redis outage?

**Comment by realLiangshiwei** [comment]
You can check this: https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-best-practices-connection#using-forcereconnect-with-stackexchangeredis

You can choose to hide the exception or throw it

See: https://docs.abp.io/en/abp/latest/Caching#available-options

**Comment by leonkosak** [comment]
> You can check this: https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-best-practices-connection#using-forcereconnect-with-stackexchangeredis
> 
> You can choose to hide the exception or throw it
> 
> See: https://docs.abp.io/en/abp/latest/Caching#available-options

Thank you.
I hope that in case if the application loses connection to Redis, all cached data in Redis are treated as obsolete (because there is a chance that the application couldn't update/delete some cached entities and therefore application starts working wrong because some data would be valid in cache (time-wise), but in real-world not anymore because of failed update/delete in Redis.
