### ISSUE TITLE
Cannot install Vovo.AbpCli

### ISSUE THREAD

**Issue by KevinFarrow** [abpframework/abp#2003]
I get the following error when trying to install the Cli - for some reason the installer is trying to use the telerik nuget package source. BTW The telerik nuget package source isn't set as the default source.

C:\Windows\system32>dotnet tool install -g Volo.Abp.Cli
C:\Program Files\dotnet\sdk\3.0.100\NuGet.targets(123,5): error : Failed to retrieve information about 'volo.abp.cli' from remote source 'https://nuget.telerik.com/nuget/FindPackagesById()?id='volo.abp.cli'&semVerLevel=2.0.0'. [C:\Users\kevin\AppData\Local\Temp\jokcv153.dq3\restore.csproj]
C:\Program Files\dotnet\sdk\3.0.100\NuGet.targets(123,5): error :   Response status code does not indicate success: 401 (Logon failed.). [C:\Users\kevin\AppData\Local\Temp\jokcv153.dq3\restore.csproj]
The tool package could not be restored.
Tool 'volo.abp.cli' failed to install. This failure may have been caused by:
* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by Trojaner** [comment]
You have added a source to your global NuGet.config which fails authentication.

Try `dotnet tool install -g Volo.Abp.Cli --ignore-failed-sources`

**Comment by KevinFarrow** [comment]
@Trojaner Thanks, that worked a treat!

**Comment by HaiyanDu7** [comment]
Still not working..

C:\Windows\System32>dotnet tool install -g Volo.Abp.Cli --ignore-failed-sources
Failed to install tool package 'volo.abp.cli': Could not find a part of the path 'C:\Users\User\.dotnet\tools\.store\.stage\1bmmc2fx.5gm\volo.abp.cli'.
Tool 'volo.abp.cli' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by maliming** [comment]
hi @HaiyanDu7 

`Volo.Abp.Cli` exists in nuget. https://www.nuget.org/packages/Volo.Abp.Cli.Core

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by HaiyanDu7** [comment]
I installed the previous Dotnet SDK, after I installed the latest Dotnet SDK, the environment SDK path is still the same as previous, which causes the issue to install any NuGet tools. after I deleted the Dotnet SDK path environment variable, I was able to install the tool.

**Comment by sa1ah** [comment]
why this error
Tool 'volo.abp.cli' failed to update due to the following:
The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'volo.abp.cli' failed to install. Contact the tool author for assistance

**Comment by maliming** [comment]
hi

> The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.

https://abp.io/support/questions/8136/Package-voloabpsuite-is-not-a-NET-tool

Please uninstall all preview or rc SDKs, then install the official net 9 SDK.
