### ISSUE TITLE
Polly infinity retry in HttpClientProxies 

### ISSUE THREAD

**Issue by chai93323** [abpframework/abp#2009]
Currently when the service throw exception, Abp HttpClientProxies will infinity retry with polly and throw the exception below. How can I fix this issue or include new policy to disable polly without modify abp http client library? 

TaskCanceledException: A task was canceled.
Polly.Retry.AsyncRetryEngine.ImplementationAsync<TResult>(Func<Context, CancellationToken, Task<TResult>> action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates<TResult> shouldRetryResultPredicates, Func<DelegateResult<TResult>, TimeSpan, int, Context, Task> onRetryAsync, int permittedRetryCount, IEnumerable<TimeSpan> sleepDurationsEnumerable, Func<int, DelegateResult<TResult>, Context, TimeSpan> sleepDurationProvider, bool continueOnCapturedContext)

**Comment by maliming** [comment]
I will check it out.

**Comment by maliming** [comment]
hi @chai93323  Can you explain it in detail? And the steps to reproduce.

**Comment by chai93323** [comment]
hi @maliming , you can just include throw new Exception("Polly Test"); on any service method. The exception will failed retry on method below then throw the polly retry exception.

```
 //use IHttpClientFactory and polly
            services.AddHttpClient(remoteServiceConfigurationName)
                .AddTransientHttpErrorPolicy(builder =>
                    // retry 3 times
                    builder.WaitAndRetryAsync(3, i => TimeSpan.FromSeconds(Math.Pow(2, i))));
```

**Comment by maliming** [comment]
@chai93323  Can you provide a project?

**Comment by chai93323** [comment]
@maliming how can we include own polly policy? Current policy cause issue on our environment.

**Comment by maliming** [comment]
It is not currently customizable, but we can consider adding an option to configure it. I will try to implement it.

**Comment by techmouse84** [comment]
Pls reopen this. I'm facing this issue as well. 
I'm able to reproduce this issue in version 1.0.2 
It's not infinitely retry but definitely alot more than just 3 retries (default)
Steps to reproduce. 
using the default microservice demo 

1. Deliberately throw exception in ProductAppService
```
public async Task<ListResultDto<ProductDto>> GetListAsync() 
        {
            throw new AbpException("Test");
        }
```
2. Update ConsoleClientDemo appSettings to point to the microservice 
3. Update ClientDemoService to run only TestProduceService 

Below is my fiddler output. 
![image](https://user-images.githubusercontent.com/16790128/68955049-27dc6980-0800-11ea-9ec4-b09712fde6d0.png)

I believe the problem is in ServiceCollectionDynamicHttpClientProxyExtensions
The polly retry is registered multiple times due to the foreach loop within the AddHttpClientProxy method.  

```
    foreach (var serviceType in serviceTypes)
            {
                services.AddHttpClientProxy(
                    serviceType, 
                    remoteServiceConfigurationName,
                    asDefaultServices
                    );
            }
```


I moved the Polly config out of the for loop and it seems to fix the problem.
```
 //use IHttpClientFactory and polly
            services.AddHttpClient(remoteServiceConfigurationName)
                .AddTransientHttpErrorPolicy(builder =>
                    // retry 3 times
                    builder.WaitAndRetryAsync(3, i => TimeSpan.FromSeconds(Math.Pow(2, i))));

            foreach (var serviceType in serviceTypes)
            {
                services.AddHttpClientProxy(
                    serviceType, 
                    remoteServiceConfigurationName,
                    asDefaultServices
                    );
            }

```
(1 call + 3 retries )
![image](https://user-images.githubusercontent.com/16790128/68956194-8c002d00-0802-11ea-9a36-4216cdc82eb1.png)

**Comment by maliming** [comment]
@techmouse84 This pr should solve your problem. https://github.com/abpframework/abp/pull/2038

**Comment by techmouse84** [comment]
@maliming , 
thanks for the speedy reply. 
I have tried this PR . However, this does not address my problem. I understand that this PR basically expose the configuration of polly policy. I can remove the configuration of polly in the following manner but this is not what i'm trying to resolve. The following code removes polly entirely. 
```
public class ProductManagementHttpApiClientModule : AbpModule
    {
        public const string RemoteServiceName = "ProductManagement";

        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddHttpClientProxies(
                typeof(ProductManagementApplicationContractsModule).Assembly,
                RemoteServiceName, configureHttpClientBuilder:
                (httpClientBuilder) => {
                }
            );
        }
    }
```

However, if i use the default setup, i still run into many retries instead of the expected number 3. 

```
public class ProductManagementHttpApiClientModule : AbpModule
    {
        public const string RemoteServiceName = "ProductManagement";

        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddHttpClientProxies(
                typeof(ProductManagementApplicationContractsModule).Assembly,
                RemoteServiceName, configureHttpClientBuilder: null
            );
        }
    }
```
![image](https://user-images.githubusercontent.com/16790128/69028972-a3ac0100-0a0e-11ea-9331-a1ae4f836bf6.png)

Maybe you can take a look at my previous post in details?
I mentioned on how i tested and proved that the problem is due to the registration of the polly and httpClient.

**Comment by maliming** [comment]
@techmouse84 I tested it in a project created by cli. Not tried microservices.

**Comment by maliming** [comment]
@techmouse84 see https://github.com/abpframework/abp/pull/2201
