### ISSUE TITLE
Blazor Webapp - The user menu will not close unless triggered again

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#20446]
**App:** Blazor wepapp tiered -Efcore 

The user menu will not close unless triggered again. The user menu should close when the page is selected.

[Apex_1723007759408.webm](https://github.com/user-attachments/assets/adabe7d7-e87c-464e-a314-a98fe971d4d8)

**Comment by maliming** [comment]
Can you share your test project? 
And how you created the project. CLI or studio?

**Comment by gizemmutukurt** [comment]
I may not have the project, I can check again. However, you can create a project with Studio and try it.

**Comment by maliming** [comment]
This is because leptonx theme:

@enisn Why do we use a variable to show/hide the div instead bootstrap component?

https://github.com/volosoft/lepton/commit/91f966dca127c85a170a42f5b3a40b4ff830b6cc

https://github.com/volosoft/lepton/blob/rel-3.2/aspnet-core/volo/src/Volo.Abp.AspNetCore.Components.WebAssembly.LeptonXTheme/Components/ApplicationLayout/SideMenu/MainHeader/MainHeaderToolbarUserMenu.razor.cs#L154

https://github.com/volosoft/lepton/blob/rel-3.2/aspnet-core/volo/src/Volo.Abp.AspNetCore.Components.WebAssembly.LeptonXTheme/Components/ApplicationLayout/SideMenu/MainHeader/MainHeaderToolbarUserMenu.razor#L11

https://github.com/volosoft/lepton/blob/rel-3.2/aspnet-core/volo/src/Volo.Abp.AspNetCore.Components.WebAssembly.LeptonXTheme/Components/ApplicationLayout/SideMenu/MainHeader/MainHeaderToolbarUserMenu.razor#L69

**Comment by enisn** [comment]
Right! Moving this issue to leptonx
