### ISSUE TITLE
abp and commercial features

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#2103]
If application development is started with free abp (open-source), how much effort (and what steps are required) is expected to "upgrade" to abp commercial?

**Comment by hikalkan** [comment]
We haven't published any commercial product on top of the ABP framework, but we will in a short time.

Upgrade path will be reasonably easy, because we have created a common theme base and switching to a paid theme is straightforward (just changing a NuGet package).
Also, commercial startup template will be almost identical to the free one, except it adds some commercial modules as NuGet/NPM packages. You can just copy all of your code or add/change some NuGet package references (first one would be easier).
