### ISSUE TITLE
why would PermissionValueProviderManager be singleton

### ISSUE THREAD

**Issue by Goxiaoy** [abpframework/abp#2110]
All PermissionValueProvider will be singleton during all the requests. but PermissionValueProvider marked as transient

**Comment by hikalkan** [comment]
PermissionValueProviderManager is singleton since it has `public IReadOnlyList<IPermissionValueProvider> ValueProviders` and we want to create this list only once.
PermissionValueProvider becomes singleton, you're right. So, if you need to create a custom PermissionValueProvider then you need to care about it.

Making PermissionValueProviders singleton would be better to make it explicit. I added this to 2.0 since it might be an unnecessary breaking change.

**Comment by Goxiaoy** [comment]
But all the current implemented PermissionValueProvider `ClientPermissionValueProvider ` `UserPermissionValueProvider ` `RolePermissionValueProvider ` depend on `IPermissionStore `, which may be implemented by [PermissionStore](https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/permission-management/src/Volo.Abp.PermissionManagement.Domain/Volo/Abp/PermissionManagement/PermissionStore.cs), then this object holds the `IPermissionGrantRepository ` then holds the dbContext which is not thread-safe...

Chained effect...

**Comment by hikalkan** [comment]
>then holds the dbContext which is not thread-safe...

ABP framework uses ambient unit of work system which is thread safe. No service injects dbcontext directly. So, no problem with the current implementation. But depending transients from singletons are bad in general.
