### ISSUE TITLE
Managing users, which module - Account or Identity? Both? 

### ISSUE THREAD

**Issue by AlphaComposite** [abpframework/abp#2138]
Which module should we be using to manage users? I imported the account module, but it needs  Volo.Abp.Account.IdentityServer and I don't see that in Nuget anywhere. 

Would it be possible to find a detailed description of all the modules and which ones are dependent upon other modules? The readme for almost every module is empty.  

Thanks, gents.

**Comment by maliming** [comment]
There may already be dependencies between modules, the account module has already depend on the identity module, and the identity module depend on the user module.

Although the documentation is still being supplemented, you can look at the source code of the module to understand the features in the module.

Then decide which modules you need to use.

**Comment by AlphaComposite** [comment]
Maybe someone else can provide a detailed answer before the issue is closed again? 

"Go look at the source code" for 3 or 4 modules seems a bit light.

**Comment by hikalkan** [comment]
>The readme for almost every module is empty

Documentation is in progress, but will get some time.

We tried to minimize dependencies between application modules.

* Account depends on Identity (as a core dependency, since it uses the users to login).
* Account depends on IdentityServer as an optional dependency (with [this package](https://github.com/abpframework/abp/tree/dev/modules/account/src/Volo.Abp.Account.Web.IdentityServer)). If you use this package, it will support consent screen and other IDS4 features.

If you have any more specific question, please reopen the issue and write below.

**Comment by hikalkan** [comment]
BTW, it is not hard to see dependencies. No need to look at the source code. You can use NuGet.org. For example, see https://www.nuget.org/packages/Volo.Abp.Account.Web.IdentityServer

![image](https://user-images.githubusercontent.com/1210527/68998480-cd0c4600-08c3-11ea-8dda-298cb3d12375.png)

**Comment by AlphaComposite** [comment]
Would like to know how to import and what to import to allow for the ability to manage users and roles - preferably with the pages for this functionality that we can modify and customize. 

I can't really find any instruction/documentation about this and it seems like a very common use case that people would need help with.
