### ISSUE TITLE
Ignore element after removal in mongodb

### ISSUE THREAD

**Issue by nguyendev** [abpframework/abp#2378]
![image](https://user-images.githubusercontent.com/10234503/70683995-1ab77b00-1cd7-11ea-9830-b12cec52501e.png)

**Comment by maliming** [comment]
Can you elaborate on the problem?

**Comment by nguyendev** [comment]
have created an attribute named "correctUser" in the Puzzle table and used it. After that I no longer use it, I delete it and get the error

**Comment by hikalkan** [comment]
This is how mongodb driver works: It throws exception if your collection in the database has a field but there is no corresponding property in the entity class.

If you inherit from the `AggregateRoot<T>` you don't have this problem because ABP automatically maps missing fields to the `ExtraProperties` dictionary of the `AggregateRoot<T>` class.

You can also solve this manually yourself by following MongoDB C# documentation:
See https://mongodb.github.io/mongo-csharp-driver/2.8/reference/bson/mapping/#ignoring-extra-elements and https://mongodb.github.io/mongo-csharp-driver/2.8/reference/bson/mapping/#supporting-extra-elements
