### ISSUE TITLE
Design question: Can abp framework and no-code approach go hand in hand?

### ISSUE THREAD

**Issue by AliYil** [abpframework/abp#2463]
We are planning to make an application where user can design entities and business logic using workflow editor, and we want to use abp's features (like auditing) on them. Since dynamically creating entities is against abp's code first approach, is it suitable to somehow use abp in this type of application?

If yes, which abp framework (aspnet boilerplate / abp.io) could be the best for this job?

**Comment by hikalkan** [comment]
Surely, you can do it. ABP features will work, but may not be as you are expecting. For example, auditing will write entity-based logs. If you store properties of your entities in a separate table (like a table with Id, EntityType, EntityId, PropertyName, PropertyValue columns, named EntityProperties) and you change 3 properties of the entity, the you will get the change report for the `EntityProperties` table rather than your dynamic entity.
However, you can work on it to make them compatible, because the ABP framework is extensible and almost all services are replaceable.

>which abp framework (aspnet boilerplate / abp.io) could be the best for this job?

Both fine. aspnet boilerplate is more mature, feature rich and well documented now, but abp.io also has a good potential and rapidly growing (actually it also has unique features where aspnetboilerplate doesn't have).
