### ISSUE TITLE
Call ConfigureAwait(false) on await usages

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2497]

**Comment by javiercampos** [comment]
I've made the above PR (#2500) for all Volo.Abp.* solutions in the repository (including framework and modules). I've built and ran the tests and everything is ok except for 1 test which doesn't look related to this (expained on the PR)

**Comment by mehmetuken** [comment]
We don't need this because aspnet core doesn't have SynchronizationContext. 
ref: https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html

And i merge #2414 after don't hanging.

https://github.com/mehmetuken/abp/commit/b4bce66ae6218e19c00aa361e2faefb3ed7e0463/checks?check_suite_id=376506937
https://github.com/mehmetuken/abp/commit/40e8a65f98ec58bb2f042fe6d43b27343a092784/checks?check_suite_id=376313708

**Comment by javiercampos** [comment]
@mehmetuken : yes, aspnet core doesn't have one, but some test runners (and possibly other environments) do, and to me at least, this seems to be causing issues with the sync contexts on both xunit and nunit (which they use for parallelization, even if you disable it), on integration tests ( see #2075 ) when the hardware is not powerful enough (or it's busy)

**Comment by mehmetuken** [comment]
I understand but hanging problem still gone #2464 and #2414 pr for me. You can try which one ci runner using your merge this two change after.

**Comment by javiercampos** [comment]
Yes, as I said, most of the hangs probably came from the use of the `AsyncEx` library (this got fixed once you removed the sync code), *still*, it's a good etiquette to use `ConfigureAwait(false)` on library code and make no assumptions on who is calling it and how. Capturing the synchronization context (if one exists) should be done by whoever needs it captured, and the rest of the `await` calls should refrain from doing so... this is true for basically all library code: it should be the consumer the one that should capture the context, and not the library: whether that context exists or not, it should not be the library the one to decide so.

Not calling `ConfigureAwait(false)` in awaitables when you don't need to capture the context for a specific reason is just wrong code, and if it works, it does so "because of the environment", which is never a good thing for a library to be reliant on.

There's absolutely zero harm on calling `ConfigureAwait(false)` in ABP, and there's a possible tangible benefit on doing so, so I'd start doing so rather sooner than later. That's why I asked if I should make this PR (and was told so here: https://github.com/abpframework/abp/issues/2075#issuecomment-569507256 )

**Comment by mehmetuken** [comment]
https://github.com/AElfProject/AElf
This project full build on ABP. And they doesn't use ConfigureAwait anywhere all test passing. Maybe problem somewhere else.
How to use it instead of doing it one by one if it's really necessary?
https://github.com/Fody/ConfigureAwait

**Comment by hikalkan** [comment]
Resolved with https://github.com/abpframework/abp/pull/2500

Thanks all for your comments.
