### ISSUE TITLE
V2 release

### ISSUE THREAD

**Issue by kurtwilbies** [abpframework/abp#2556]
What id the release date of version 2. Is there a roadmap? And what will be the difference with version 1. The docs are not very helpfull. Also, there is no detailed docs of how to develop with this framework.

**Comment by hikalkan** [comment]
Documentation is constantly improved. It will be complete in the short term.
Release date is not clear but will be in ~10 days.
You can see all changes and the progress here: https://github.com/abpframework/abp/milestone/26
See breaking changes: https://github.com/abpframework/abp/issues?q=is%3Aissue+label%3A%22breaking+change%22+milestone%3A2.0+is%3Aclosed

Don't expect important features with v2.0. We named it v2.0 because it has some important breaking changes, especially by this PR: https://github.com/abpframework/abp/pull/2464/commits
