### ISSUE TITLE
 Mobile with ABP

### ISSUE THREAD

**Issue by desenv2hs** [abpframework/abp#2581]
I need write a mobile app.
My scenario is this: Mobile with the same business rules as the web, we would like to save data to mobile offline. But for that the ABP would have to be .NetStandard instead of .NetCore.
Will ABP have a .NetStandard version to use on Mobile?

**Comment by hikalkan** [comment]
Core ABP packages are already .NET standard ([example](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Core/Volo.Abp.Core.csproj#L4)). Bu ASP.NET Core depended packages are .NET Core 3.1, because ASP.NET Core doesn't support .NET Standard as you know.

**Comment by hikalkan** [comment]
I am closing. If you have additional questions, or you find a package that can be .net standard but accidently made .net core, please reopen.

**Comment by mgochmuradov** [comment]
@hikalkan Actually there are some projects that could be converted to `netstandard` to be able to use them in mobile applications (Xamarin).

1. Please convert `Volo.Abp.Http.Client` and all other `Volo.Abp.MODULE.HttpApi.Client` projects in all module solutions to `netstandard`. This will allow usage of automatic (proxy) rest services clients in mobile applications.

2. Default CLI template will create the following projects in `netcoreapp`:
- Xxx.Application
- Xxx.Domain
- Xxx.EntityFrameworkCore
- Xxx.EntityFrameworkCore.DbMigrations
This is (AFAIK) because of `IdentityServer` module which can't be converted to `netstandard`.
Will it be possible to opt-out IdentityServer when creating a solution from CLI template?
This will allow the usage of these projects in an **offline** mobile application.

**Comment by mgochmuradov** [comment]
PS: Converting `...HttpApi.Client` projects to netstandart will also allow their usage in Blazor Clients

**Comment by maliming** [comment]
@mgochmuradov  see https://github.com/abpframework/abp/pull/2867
