### ISSUE TITLE
How to add tenantId to my new entity ?

### ISSUE THREAD

**Issue by MROALI** [abpframework/abp#2600]
How to add tenantId to my new entity ?

For example i wanted to add multitenancy to the book Entity (https://docs.abp.io/en/abp/latest/Tutorials/AspNetCore-Mvc/Part-I)  So i did the following : 

````csharp
 public class Book : AuditedAggregateRoot<Guid>, **IMultiTenant** {
       public Guid? TenantId { get; set; } 
      ...
}
````

The problem is that the dbmigration file result (Book Entity section) the foreign relation with the tenantTable is not generated ? 

Do i need to do something else ?

**Comment by hikalkan** [comment]
We don't suggest to have a foreign key for the TenantId. Because a tenant may have a dedicated database which naturally will not contain the tenants table (or at least will contain an empty tenants table). So, as a best practice, don't define a foreign key. But if you want, you can configure it in your DbContext's `OnModelCreating` method.
