### ISSUE TITLE
Get Tenant Id by User Name

### ISSUE THREAD

**Issue by Alexbits** [abpframework/abp#2609]
Is there any recommended way to resolve the tenant id from the user name? In my application architecture every new user is a tenant admin (who can add his own users). I would like them to be able to login by getting tenant id by the user name or email and then use ```CurrentTenant.Change(user.TenantId)``` to set current current tenant before proceeding to```SignInManager.PasswordSignInAsync(...)```. Thanks.

**Comment by maliming** [comment]
It is not recommended that you do this, it is an endless loop, you need tenant information when you want to get user. : ) Other than that, different tenants may have the same username.

**Comment by hikalkan** [comment]
There may be multiple solutions to this problem.

First of all;

* You should guarantee that the user name is unique among tenants.
* This system works only if all tenants share the same database (otherwise you should query all tenant databases one by one).

What you should do is to override related .cshtml, .js files and/or replace services of the [account module](https://github.com/abpframework/abp/tree/dev/modules/account/src) or get its source code into your solution and change however you like.

**Comment by Alexbits** [comment]
Hi @maliming @hikalkan Thank you for your replies. I was thinking about separate database for Identity service and getting tenant id by email address for example (I don't need multiple users with same address and/or user name).

Is there better way to add a group of users (same company) and then implement a data filter so they can see only their data?

**Comment by Alexbits** [comment]
Maybe this is a better way for this? [https://aspnetboilerplate.com/Pages/Documents/Articles%5CHow-To%5Cadd-custom-data-filter-ef-core](url)

**Comment by hikalkan** [comment]
>Is there better way to add a group of users (same company) and then implement a data filter so they can see only their data?

Yes, a custom filter would be better.
