### ISSUE TITLE
update to 2.0 and cannot startup

### ISSUE THREAD

**Issue by LGinC** [abpframework/abp#2628]
update all nuget to 2.0,  install Volo.Abp.Localization nuget package for  AbpValidationResource
![image](https://user-images.githubusercontent.com/15363011/72275407-d23e0500-3668-11ea-820b-2b102c4fb8fd.png)

and startup failed
![image](https://user-images.githubusercontent.com/15363011/72275539-1204ec80-3669-11ea-9813-b383a72b599c.png)

**Comment by hikalkan** [comment]
This is because of: https://github.com/abpframework/abp/issues/2499
You need to make necessary changes and re-compile your solution(s).

**Comment by LGinC** [comment]
![image](https://user-images.githubusercontent.com/15363011/72277654-411d5d00-366d-11ea-91f9-d48240680eb7.png)
Installed Volo.Abp.Validation Package and  using Volo.Abp.Validation.Localization  in DomainShareModule.
and rebuilt solution,but i cannot startup it.
![image](https://user-images.githubusercontent.com/15363011/72277809-93f71480-366d-11ea-85e4-114596f204e0.png)
![image](https://user-images.githubusercontent.com/15363011/72277794-8b9ed980-366d-11ea-826b-9a31d59b5758.png)

**Comment by LGinC** [comment]
sorry , i forgot to do this
![image](https://user-images.githubusercontent.com/15363011/72278063-2a2b3a80-366e-11ea-80a4-462de1c8e152.png)

**Comment by gdlcf88** [comment]
Maybe developers need upgrading documents. :D
https://github.com/abpframework/abp/issues/1442

**Comment by hikalkan** [comment]
When you upgrade (especially a major version) check the release notes.
For example, in v2.0, we've written all breaking changes to the release notes: https://github.com/abpframework/abp/releases/tag/2.0.0
Every breaking change issue documents its own solution. For example, https://github.com/abpframework/abp/issues/2499 explains `AbpValidationResource` change and the actions need to take.

https://github.com/abpframework/abp/issues/1442 is a document explains upgrading in general, rather than individual upgrades.
