### ISSUE TITLE
Different apps share their cookies in localhost

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#2658]
Step to reproduce:
1. Create a mvc template abp solution names `A`, and create an angular abp solution names `B`.
2. Run project A, Create a new tenant in A, and log in the tenant as admin user.
3. Run project B, get 500 error, details:
```
2020-01-17 01:50:58.775 +08:00 [ERR] Connection id "0HLSQLII9J84B", Request id "0HLSQLII9J84B:00000001": An unhandled exception was thrown by the application.
Volo.Abp.AbpException: There is no tenant with given tenant id or name: f39c64f4-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

**Comment by maliming** [comment]
This is the behavior of the browser, it does not provide port isolation.

We can consider configuring cookie names for modules such as identity in the template. Similar to cache names.

**Comment by hikalkan** [comment]
OK, I added this to the backlog, but I think it is not urgent. Just delete the cookies for now, because it is not a problem on production (and also it is a problem in a standard asp.net core application by default).

If someone finds exactly where to change (also considering the IDS4 integration scenarios), we can give a higher priority to this issue.

Any PR welcome :)

**Comment by hikalkan** [comment]
We've improved Angular specifically better handle this problem. That's all we can do for now.
