### ISSUE TITLE
Use ABP in a mobile(Xamarin) application (.Net Standard 2.0)

### ISSUE THREAD

**Issue by jader1313** [abpframework/abp#2668]
I would like to use ABP to share domain, application, and data access classes across the various user interfaces: desktop, web, and mobile. I can't use ABP in Xamarin because some projects (modules) are set to .Net Standard 2.1 and Xamarin only supports .Net Standard 2.0:
-Volo.Abp.EntityFrameworkCore
-Volo.Abp.EntityFrameworkCore.Sqlite

Would a downgrade to .Net Standard 2.0 be possible to standardize and make it compatible with Xamarin?

I didn't find an example of using ABP with Xamarin as there was before in Boilerplate. Is it possible ABP + Xamarin?

Any guidance on this?

**Comment by hikalkan** [comment]
Volo.Abp.EntityFrameworkCore using .net standard 2.1 because Microsoft.EntityFrameworkCore 3.0.0 was depending on .net standard 2.1. But now I see that Microsoft.EntityFrameworkCore 3.1 supports .net standard 2.0. So, we will consider to downgrade it. Thanks.

However, I didn't understand why you need EF Core in Xamarin. Will you directly connect to a database from your mobile app?

**Comment by hikalkan** [comment]
@maliming can you check if we can downgrade to .net standard 2.0 for EF Core depended projects?

**Comment by jader1313** [comment]
> However, I didn't understand why you need EF Core in Xamarin. Will you directly connect to a database from your mobile app?

The application will work offline, accessing an SQLite database on the device that will synchronize with a MySQL database on the Web.
