### ISSUE TITLE
BasicConsoleApplication

### ISSUE THREAD

**Issue by Gosha24** [abpframework/abp#2674]
I did not manage to build  BasicConsoleApplication from samples.
It compiles after i added packages
    "Volo.Abp.Autofac" Version="2.0.0" 
    "Volo.Abp.Core" Version="2.0.0" 
and removed
    "..\..\..\framework\src\Volo.Abp.Autofac\Volo.Abp.Autofac.csproj" 
from .cproj
Please refresh distribution version
Please, add possibility  to create console apps from CLI tool

**Comment by hikalkan** [comment]
It works for me.

Visual Studio can not work properly with the local references out of the solution folder. When you open a module/sample solution in the Visual Studio, you may get some errors related to the dependencies. In this case, run the dotnet restore on the command prompt for the related solution's folder. You need to run it after you first open the solution or change a dependency.

I think it is not needed to create an empty console template, because you can create is easily by following the documentation: https://docs.abp.io/en/abp/latest/Getting-Started-Console-Application

**Comment by hikalkan** [comment]
BTW, if anyone want to create a template and work on the CLI to support it, we accept and thank :)

**Comment by hikalkan** [comment]
I created an issue: https://github.com/abpframework/abp/issues/3976
