### ISSUE TITLE
Abp angular modules architectural style

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#2739]
Hi,
@mehmet-erim I saw abp architectural style for angular modules, you defined sperate lib for each module and added them to your app-dev application, Is this style just for reusability of these libs in other application? should I create separate libs for each of my modules in Domain space? or only for my modules that share in other apps for reusability?

**Comment by mehmet-erim** [comment]
Each ABP modules are an NPM package. We created these modules as a library because Angular libraries can publish easily. 

> Should I create separate libs for each of my modules in Domain space?

* If you would like to publish your module to an NPM server, you should create a library.
* If you will have more than one Angular project, you should create a library to reuse this module.

> Angular libraries are harder than standard modules to scale.

You can also create a module with ABP CLI. See https://docs.abp.io/en/abp/latest/Startup-Templates/Module
If you generate a module with ABP CLI, an Angular application with two libraries will be created. You must publish these Angular libraries to use in your main project.

---
If you don't need to reuse a module with different Angular projects, you should create a standard Angular module.
See the [Bookstore tutorial](https://docs.abp.io/en/abp/latest/Tutorials/Angular/Part-I) to learn how to create a standard module and how to manage it.

**Comment by mehdihadeli** [comment]
thank @mehmet-erim.
