### ISSUE TITLE
Questions about forceToSet in SettingManager

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#2749]
https://github.com/abpframework/abp/blob/0a1568781df03fe9c86dc38cb7d47b95389cdf0b/modules/setting-management/src/Volo.Abp.SettingManagement.Domain/Volo/Abp/SettingManagement/SettingManager.cs#L111

1. Question 1:
The property name `forceToSet` is **not easy for people to understand its effect**: In ordinary language, `forceToSet = false` means "set the value to null if inherited value is the same as the value you want to set".
Maybe "autoClearIfInherited" or other better names are more accurate?

2. Question 2:
If developers don't know what the `forceToSet` means, or just forget to set `forceToSet = true`, it may lead to the setting values loss.
Why `forceToSet` is `false` by default?

3. Question 3:
When I want to remove a user's setting and let it inherits from superior providers, I can set user's setting value to `null` manually.
What is the meaning of `forceToSet`‘s existence?

**Comment by itryan** [comment]
when the new value (for UserSettingValueProvider) is the same as its callback value (from TenantSettingValueProvider), it seems Abp considers it as value resetting thus passes actual value null by default. Maybe @gdlcf88 is expecting some use case for this default behavior.

**Comment by hikalkan** [comment]
Actually it doesn't set to null, but deletes the setting completely: https://github.com/abpframework/abp/blob/dev/modules/setting-management/src/Volo.Abp.SettingManagement.Domain/Volo/Abp/SettingManagement/SettingManager.cs#L147-L153

Let's go with the Tenant -> User inheritance (actually we call it User -> Tenant fallback, but not important now).
If a setting's value is "A" for a tenant, then it will be "A" for all the tenant users unless a user overrides it to "B". Asume that this happens, then user sets the setting value to "A" again (the default value in the beginning). What we should do? ABP assumes that you are deleting the customization and returning to the default value. And it deletes the setting record for this user: The result is same, the user value is "A" again.
If the tenant setting value is changed to "C" in the future, this user's value also sets to "C" by inheritance logic. If you don't want that, you can tell ABP to explicitly set user value to "A" (using the forceToSet) even the inherit value is already "A". Then user's value always remains "A" even tenant changes it.

**Comment by gdlcf88** [comment]
> What we should do? ABP assumes that you are deleting the customization and returning to the default value.

Thanks for @hikalkan 's explanation.

For abp's permission system, I set "A" to User, the user will really get the grant (in DB), if I want the user inherit from roles again, I will manually delete the grant instead of setting it to "A".

And the problem is why there are two different design for permission management and setting management? Maybe I should manually set User to null for let it inherit just like what I do in permission management. Or maybe `forceToSet` could be true by default so we can keep the feature and developers can use it just like using the permission management.

**Comment by hikalkan** [comment]
In the permission system, you only set true or false for a permission. When you set false, it [deletes](https://github.com/abpframework/abp/blob/dev/modules/permission-management/src/Volo.Abp.PermissionManagement.Domain/Volo/Abp/PermissionManagement/PermissionManagementProvider.cs#L74) the record from database because a permission is not granted by default so no meaning to store it as false in the database.

If user has role "manager" and the manager role has permission X, then you don't need to grant X permission to the user because it inherits from the role. The user interface doesn't allow it:

![image](https://user-images.githubusercontent.com/1210527/74120571-e0823100-4bd4-11ea-8be3-d26a83b63efc.png)

You see that inherited permissions are disabled. You can not revoke a permission for a user inherited from a role. But you can grant permissions he/she doesn't inherently has.

So, setting system and permission system has many differences, we don't need to make them identically implemented.

Most of the times you don't need to care about this low level details. If you have a use case which is impossible to implement please write here so we can suggest a solution or consider to enhance the framework. Otherwise, it is impossible to convince everyone for the decisions we made while creating the framework. It has thousands of features you know, it is impossible to discuss all :)

**Comment by gdlcf88** [comment]
> If user has role "manager" and the manager role has permission X, then you don't need to grant X permission to the user because it inherits from the role. The user interface doesn't allow it

I get it. So for both permission system and setting system, the design is the same. Maybe there's actually a risk of data loss in this setting system design, but as you said, frameworks have different designs. I will close this issue, and the last suggestion is that [setting doc](https://docs.abp.io/en/abp/latest/Settings) should be enriched because there is no content about `forceToSet` and its related design.
