### ISSUE TITLE
Migration guide.

### ISSUE THREAD

**Issue by mehmetuken** [abpframework/abp#2768]
Update new version template projects changing migration guide missing.

**Comment by hikalkan** [comment]
is this same of https://github.com/abpframework/abp/issues/2120?

**Comment by mehmetuken** [comment]
@hikalkan it's not. v1 to v2 or v2.0 to v2.1. For example [this ](https://github.com/abpframework/abp/commit/ba768a2681a7648bbf7306a0e51422f84620e5a3) change we need complete investigative template projects all change every new version. Migration guide very helpfull for every developper.

**Comment by hikalkan** [comment]
It is not a critical change for the templates, you don't have to implement in your side. Instead of creating a migration guide, we do like that:

* Add `breaking-change` label to the issues and pull requests
* Write what to do for existing applications

Then when we release it ([example](https://github.com/abpframework/abp/releases/tag/2.0.0)), anyone can check the release notes and apply if needed.

For major version changes (v1.x to v2.x) we will definitely write such guides. For minor version changes we want to go as I explained. We write additional notes when needed.
