### ISSUE TITLE
Audit log can't know if an error ocurred if the exception filter handles it

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2821]
We should also check the http response code to understand if there is an error. It currently only checks thrown exceptions:

https://github.com/abpframework/abp/blob/f47a0c1f5f8e9d224663b2d8c2f829c8b78f91b1/framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/Auditing/AbpAuditingMiddleware.cs#L38-L41

**Comment by gterdem** [comment]
Even if there is an error, http response code is always 200. Any other way to check it? Or am I out of scope?

**Comment by hikalkan** [comment]
>Even if there is an error, http response code is always 200

If so, we have another problem. It should return an error status code. Can you confirm that?

**Comment by gterdem** [comment]
Yes, status code always returns 200 because it returns without setting it in `AbpExceptionFilter`
https://github.com/abpframework/abp/blob/2b53c9ad1997c79a70ef59f433da6793385d6edb/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ExceptionHandling/AbpExceptionFilter.cs#L37-L42

Adding
 `context.HttpContext.Response.StatusCode = (int)_statusCodeFinder.GetStatusCode(context.HttpContext, context.Exception);`
before returning without handling solves this.

**Comment by gterdem** [comment]
About; https://github.com/abpframework/abp/blob/f47a0c1f5f8e9d224663b2d8c2f829c8b78f91b1/framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/Auditing/AbpAuditingMiddleware.cs#L38-L41
Do we decide to throw or not depending on status code?
