### ISSUE TITLE
Contribute : how to debug modified Nugets

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2840]
Hi,

I'm able to modify the source code and build it, but once done... how can I test (from another external project) if my changes work ?

should I publish to my own nugets server ?
I need a 'debug' package and local one (not on nuget.org) !

Thanks

**Comment by hikalkan** [comment]
The best way to use local project references instead of nuget packages.

* Fork the abp repository.
* Add a new project, but not use NuGet packages, use local project references ([see the identity module as an example](https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo.Abp.Identity.Domain.csproj#L28))
* See [the development section](https://github.com/abpframework/abp#development) of the readme file (the `dotnet restore` requirement).
