### ISSUE TITLE
Docs Update label improvements

### ISSUE THREAD

**Issue by yekalkan** [abpframework/abp#2843]
We shouldn't add updated label when the change is very small or a typo.

**Comment by hikalkan** [comment]
I don't like to manage it manually. Maybe we can aut-compare changes and if the change amount exceeds a percentage then we think it is updated.

**Comment by Ice2burn** [comment]
Setting it up manually is a bullet proof solution where you control everything. For Json Navigation Document it could be manually set in dedicated "label" section.

>> Maybe we can auto-compare changes and if the change amount exceeds a percentage then we think it is updated.
It may cover 99% of all cases, but it's hard to guess correct percentage for different document sizes.

The most important thing is that New and Upd labels should appear only after documentation version change, like most companies do. It usually folows with release notes.

**Comment by maliming** [comment]
@hikalkan Any comments?

**Comment by hikalkan** [comment]
Currently, documents are read from the dev branch since we continusly write  documents and don't want to wait community (since there are some missing ones).

We should think about labeling after releasing a new version. It can be reasonable since now we release in every 2 weeks, so a new or updated document can wait until the next release.

Manually writing last edit date to the document is also possible and seems reasonable to me now, but re-think on it.
