### ISSUE TITLE
Why does Role save Name, Client and User save ID?

### ISSUE THREAD

**Issue by 344089386** [abpframework/abp#2925]
Why does Role save Name, User save ID?
![image](https://user-images.githubusercontent.com/22017199/75321725-5a403d00-58ac-11ea-8245-e3cb4f71a0e7.png)
Role names can change at any time.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/2599

**Comment by 344089386** [comment]
I get the idea, but I still think it's better to save the ID so you don't have to do anything else to change the name.  
thanks.

**Comment by zhangzunke** [comment]
I think that the saving role is better than role name in AbpPermissionGrants, any suggestion?

**Comment by hikalkan** [comment]
Because identity claims saves the role names in the authentication ticket by default and we generally don't have access to the role ids on every request. We didn't wanted to query it or include to the auth ticket unnecessarily. role name usage is pretty standard. Even the `Authorize` attribute gets the role name as string parameter.
