### ISSUE TITLE
how to fill Detailed DTO Reference Properties

### ISSUE THREAD

**Issue by jortygu** [abpframework/abp#2929]
Hi，
Base on Entity/Application Services Best Practices，My Question is how to fill Detailed DTO Reference Properties (Ex: IssueWithDetailsDto.MileStone ) **efficiently**.
My Solution is to build Detailed DTO By LINQ (Base XXXRepository.AsQueryable()) inside the application service methods,is this accord with best practices?
![aggregate](https://user-images.githubusercontent.com/43945927/75403113-b1dcb800-5941-11ea-956f-76e24a27b303.png)
[https://docs.abp.io/en/abp/latest/Best-Practices/Entities](url)
[https://docs.abp.io/en/abp/latest/Best-Practices/Application-Services](url)

**Comment by maliming** [comment]
Use object mapping in application services.

https://docs.abp.io/en/abp/latest/Object-To-Object-Mapping

**Comment by jortygu** [comment]
@maliming the aggregate roots reference other aggregate roots by Id,object mapping just mapping normal properties,my question is how to fill reference properties?

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/blob/dev/modules/blogging/src/Volo.Blogging.Application/Volo/Blogging/Posts/PostAppService.cs#L37

**Comment by gdlcf88** [comment]
We made a module to help load related DTO from other aggregate, but it is still improving.

https://github.com/EasyAbp/Abp.RelatedDtoLoader

**Comment by jortygu** [comment]
@maliming @gdlcf88 
In both cases, the navigation properties are populated by foreach postDtos/orderDtos.
Is there an more efficient way to fill dto reference properties?

**Comment by maliming** [comment]
I don't know of other better solutions at the moment.

**Comment by gterdem** [comment]
@jortygu You can override your repository's `WithDetails` method or new methods for specific includes.
Something like;
```
public override IQueryable<MyEntity> WithDetails()
{
     return GetQueryable().Include("MyEntity.SubCollection.NavEntity");
}
```
Or to get it better, you can write an extension about it.

**Comment by jortygu** [comment]
@gterdem 
thanks for your reply.
yes,there are both AggregateRoots,that's the source of this question.
I just want to find a high-efficiency way to populate DTO reference properties and accord with DDD patterns & best practices.

**Comment by zoao** [comment]
In DDD principles, this scenario does not happen. Because in the case you need return Milestone inside each Issue, you must create a new simple milestone DTO (and normaly a new entity that is not aggregateroot), only with properties that is need for this Use Case.

This is very important principle in DDD (Entities/DTOs by use case), because your actually entity Milestone that is a Aggregateroot as more properties and behaviors, like for example a list of Issues, conditions to be released, etc..
And normally with the evolution of the application you will add more and more properties/behaviors, and because of that it is wrong to try to reuse entities/dto's for different use cases.
