### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by wjkhappy14** [abpframework/abp#3027]
\Volo.Abp.Identity.EntityFrameworkCore\Volo\Abp\Identity\EntityFrameworkCore\IIdentityDbContext.cs 
DbSet<IdentityUser> Users { get; set; }

\Volo.Blogging.EntityFrameworkCore\Volo\Blogging\EntityFrameworkCore\BloggingDbContext.cs
 public DbSet<BlogUser> Users { get; set; }

what is different  ？ need i create two tables in different databases？

**Comment by cotur** [comment]
Short: There is no differences at all, yes you need because module needs.

It is required because modular programming requeires it. As you see, `Blogging` is a module. So the module's users should be stored different table(in microservice or normal architecture). Meanwile, if blogging module needs an user data, it gets it from your application. Those are automatically executing by ABP Framework.

**Comment by wjkhappy14** [comment]
so must refactor the user of Blogging module？ use  IdentityUser, UserData ？
