### ISSUE TITLE
Docs code highlighting not working for TypeScript

### ISSUE THREAD

**Issue by mehmet-erim** [abpframework/abp#3111]
Code blocks that starts with ` ```typescript` or ` ```ts` are not highlight. It's a problem for TypeScript specific codes.

**Comment by ebicoglu** [comment]
example:

[https://docs.abp.io/en/abp/latest/Tutorials/Part-2?UI=NG&DB=EF#bookmodule](https://docs.abp.io/en/abp/latest/Tutorials/Part-2?UI=NG&DB=EF#bookmodule)

![](https://user-images.githubusercontent.com/9526587/113555956-67c60b80-9604-11eb-8a7f-623b085c9114.png)

After finishing this implementation change all real typescript code blocks to Typescript rather than JavaScript.

**Comment by ebicoglu** [comment]
Added more supported languages 
- typescript
- csharp,
- json,
- aspnet,
- bash,
- css,
- css-extras,
- docker,
- javascript,
- less,
- markdown,
- nginx,
- powershell,
- regex,
- sass,
- scss,
- sql,


And typescript works now
![image](https://user-images.githubusercontent.com/9526587/117574260-f4bd2280-b0e4-11eb-96e6-d4cf02fd2333.png)
![image](https://user-images.githubusercontent.com/9526587/117574336-52516f00-b0e5-11eb-8963-62ee966588ae.png)
![image](https://user-images.githubusercontent.com/9526587/117574488-f3402a00-b0e5-11eb-94d3-3fb715297c61.png)
![image](https://user-images.githubusercontent.com/9526587/117574512-110d8f00-b0e6-11eb-8c58-3acbafb55e25.png)
![image](https://user-images.githubusercontent.com/9526587/117574550-4ca85900-b0e6-11eb-845e-3f681005fa2c.png)
![image](https://user-images.githubusercontent.com/9526587/117574571-677acd80-b0e6-11eb-85ad-f35ce66d23af.png)
