### ISSUE TITLE
Localization error for PagerInfo on Volo.Abp.UI

### ISSUE THREAD

**Issue by gterdem** [abpframework/abp#3277]
arguments for `string.Format(localizedString.Value, arguments)` are 
arguments[0]= `_START_`
arguments[1]= `_END_`
arguments[2]= `_TOTAL_`

Hence;
> "PagerInfo": "`_TOTAL_` kayıttan `_START_` ile `_END_` arası gösteriliyor."

should be 
> "PagerInfo": "{2} kayıttan {0} ile {1} arası gösteriliyor."

for

- tr.json
- zh-Hans.json
- zh-Hant.json

> "PagerInfo": "Showing `_START_` to `_END_` of `_TOTAL_` entries"

should be
> "PagerInfo": "Showing `{0}` to `{1}` of `{2}` entries"

for 

- en.json
- ar.json
- cs.json
- es.json
- pl.json
- pt-BR.json
- vi.json

However if we change all of the localizations this way, newly added localization sources will have problem distinguishing which one is `_START_`, `_END_` and `_TOTAL_`.
Thinking about changing the name of `PagerInfo` to `PagerInfoRef` as a reference since commenting now allowed in json and adding correct values to PagerInfo.
Or keep it changed already and assume whomever localizes know english and can figure it out from `en.json`.

@hikalkan @yekalkan 
Suggestions?

**Comment by hikalkan** [comment]
didn't understand at all. we can chat about it.

**Comment by hikalkan** [comment]
>assume whomever localizes know english and can figure it out from en.json.

Yes, we assume it.

**Comment by hikalkan** [comment]
@yekalkan can you review https://github.com/abpframework/abp/pull/3538
I suppose it solves this issue.

**Comment by yekalkan** [comment]
Hi,

@hikalkan No, it doesn't. I won't approve it.

I didn't use parameters as "{0},{1}" because they are not for our tag helpers, they are for datatables localization. 

See https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/datatables/datatables-extensions.js#L350

It was a mistake to use same localizations for tag helpers. I'll fix it.
