### ISSUE TITLE
abp generate-proxy and appservices

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#3294]
abp generate-proxy command has `module` switch.

How is this switch related to AppService ?
I mean, if i add Area attribute to my appservice it is ignored.
Service is still in app module.

Is api-definition endpoint created only for controllers ?

Is there any documentation related to `abp generate-proxy`, `/api/abp/api-definition endpoint` and `area attribute` ?

**Comment by sebitsi** [comment]
Hi guys.

Any help ? Please.

**Comment by hikalkan** [comment]
I suppose you mention about the [Auto API Controller](https://docs.abp.io/en/abp/latest/API/Auto-API-Controllers) feature of the ABP Framework.

In this case, module name and can be set using the RootPath option:
https://docs.abp.io/en/abp/latest/API/Auto-API-Controllers#route

In this example, `typeof(BookStoreApplicationModule).Assembly` says that "use this route for all app services inside this assembly".

If you have a separate project (.csproj/dll/assembly) for each module, this use is fine.

If you want to customize the module name for a single app service, while others are same in an assembly, use `options.ConventionalControllers.Create` multiple times with [TypePredicate](https://docs.abp.io/en/abp/latest/API/Auto-API-Controllers#typepredicate-option)

Area is not used on the app services (since it is a web layer feature).

>Is api-definition endpoint created only for controllers

Both app services & controllers, with given restrictions;

* For app services, you need to have using options.ConventionalControllers.Create(...) (startup template does it for the app services inside the .Application project)
* For controllers, use the [RemoteService] attribute on the controller class.
