### ISSUE TITLE
Improve relative paths in ABP bundling

### ISSUE THREAD

**Issue by Xeevis** [abpframework/abp#3352]
Related to #3341 

In my opinion ABP bundling should use relative paths by following patterns in ASP.NET Core. Because if you are moving existing working stylesheet links into ABP bundles, it creates surface for new bugs.

While all of these patterns work
```html
<link rel="stylesheet" href="site1.css"> <!-- working relative link -->
<link rel="stylesheet" href="/site2.css"> <!-- working relative link -->
<link rel="stylesheet" href="./site3.css"> <!-- working relative link -->
<link rel="stylesheet" href="~/site4.css"> <!-- working relative link -->
```

For ABP bundles 2 out of those 4 don't

```html
<abp-style src="site5.css" /> <!-- broken -->
<abp-style src="/site6.css" /> <!-- working -->
<abp-style src="./site7.css" /> <!-- working -->
<abp-style src="~/site8.css" /> <!-- broken -->
```

Considering both are relative to wwwroot, shouldn't they work the same?

**Comment by maliming** [comment]
@hikalkan  What do you think? https://github.com/abpframework/abp/issues/3341#issuecomment-603688351

**Comment by hikalkan** [comment]
It seems reasonable, we can implement if possible.

**Comment by alexandis** [comment]
I have published a couple of _web applications_ (**IdentityServer** and **HttpApi.Host** from **abp.io** boilerplate) under _web site_ on my VM and while I have managed to fix the issues with relative paths, I still experience the issue with loading resources in **IdentityServer**: the path to __bundle is calculated from WEB SITE root, not from ITS APPLICATION root. I've tried to set `webBuilder.UseWebRoot` / `webBuilder.UseContentRoot` / `hostingEnvironment.WebRootPath` / `hostingEnvironment.ContentRootPath`, but no luck.

**Comment by hikalkan** [comment]
It is done.

**Comment by maliming** [comment]
Binding still needs to deal with path issues.

**Comment by alexandis** [comment]
Hi, what is the progress with this?
I'm on ABP 2.9.0 and tried to publish **Angular\dist** + **IdentityServer** + **HttpApi.Host** to _IIS_ on _Azure VM_. And despite the fact I've tried to fix all the paths (**base url** when making build, root folder in **angular.json**, links to **IdentityServer** and **HttpApi.Host** in **environment.ts**), I cannot run **Angular** successfully:

![image](https://user-images.githubusercontent.com/6149843/86298255-fc2eb800-bc05-11ea-9ec4-24b97c687efb.png)

As you can see, some paths are still calculated from root web site folder instead of web application. And issuer errors do not allow me to log in (not sure whose problem are those)...

**Comment by maliming** [comment]
hi @alexandis 
You can refer to this article: http://codebuckets.com/2018/05/26/hosting-angular-in-iis-under-an-existing-website/

**Comment by alexandis** [comment]
> hi @alexandis
> You can refer to this article: http://codebuckets.com/2018/05/26/hosting-angular-in-iis-under-an-existing-website/

It did not work for me - i even got more problems instead, now I'm getting error 500 on Angular site :) And after all, I should not receive cross-origin problem, because all 3 apps are hosted on the same "site" - Default Web Site, so they all share the same domain, http://XXXX.cloudapp.azure.com - as I already has written. So the problem is somewhere else...
