### ISSUE TITLE
 PlugInManagement Module integration

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#348]
Do you think it is not useful that each module has its own plugins? And a plugin-management module for all existing plugins (Install/Uninstall/Plugin Settings)?
It's possible by assembly naming:

```
Abp.Blogging   //Module
Abp.Plugins.Blogging.MyPluginName //Blogging Module's Plugin
```

**Comment by hikalkan** [comment]
Hi,

Every "big" module may have additional plugins. This is especially true when we develop a Content Management System which is a perfect module to extend.

Current plugin system is simple: Just add dlls into a folder, restart the application and it works.

It's early to develop a "plugin management module".

If you are asking about the naming, I would prefer ``Abp.Blogging.MyPluginName`` instead of `Abp.Plugins.Blogging.MyPluginName`.

**Comment by hitaspdotnet** [comment]
@hikalkan Hi,

I do not know much about software companies business. I'm sure your information is very good. But one question is in my mind, is it possible to provide a new management system despite the existing content management systems?

Given that applications is now an important part of the companies I can suggest you to keep your business plan as [Abp.io](https://abp.io/) home page. 
Focus on companies as top level of customers then Individuals.

2 version of template free & pro and a official feed for modules and their plugins from Volo company, a marketplace of free or commercial feeds for AMAZING Micro-Service based & Multi-Tenancy & Modular framework and template. WOOOW, that's very heavy!
That's own, we haven't similar in market. 

Just leave CMS. There is no money guys 🤣

**Comment by hikalkan** [comment]
CMS has not top priority for us - as you said, there are plants of open source / free CMS.
Our goal, as you guess it, to create a market of application modules (some of them are free, some of them are paid). Good news is that, anyone will be able to publish modules on the market, not only our team.
Wait for news :)
