### ISSUE TITLE
abp angular seo

### ISSUE THREAD

**Issue by ChangYinShung** [abpframework/abp#3562]
hello,i know this issue has no related to abpframework .
But i want ask some suggestion:
Which way is  better to implement seo  (When abp Mutiltenant is enabled and DomainTenantResolver)?
1.  Angular Universal : https://angular.io/guide/universal
2. Prerender io : https://prerender.io/

**Comment by hikalkan** [comment]
@armanozak & @mehmet-erim what do you suggest?

**Comment by armanozak** [comment]
Hi @ChangYinShung,

I am guessing you would like to build **pre-rendered (static) pages instead of server-side rendering (SSR)** via a Node server. I will try to compare them briefly:

Angular Universal | Prerender.io
:-- | :--
Build-time rendering w/ Angular compiler | External rendering w/ headless Chrome
Very easy to implement (as of Angular v9) | Easy to implement
You need to implement before seeing results | You can have a sneak peek before implementation
Dynamic routes require additional work | Middleware handles that for you
You do not have to signal page readiness | Tries to guess, but sometimes you may need to give a signal
Free | Has free tier, paid tiers are reasonably priced

[Scully](https://scully.io/), which provides an experience and results much like Angular Universal, is another alternative. Even building your own solution with Puppeteer is an option, although, honestly, a bold one. 🙂You may also consider using SSR instead or pre-rendering and go with Angular Universal, which indeed does a fine job at that.

I am not at liberty to bring a verdict in. The solution to pick does not really depend on ABP and rather depends on your project and how much effort you are willing to put into it. 

I hope this has been helpful.

**Comment by ChangYinShung** [comment]
@armanozak , thanks !
First time to see 'Scully' and it  look like a good  chose for angular ,i will try it.
