### ISSUE TITLE
Tenant resolvers on Kestrel server on Ubuntu not working

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#3612]
For asp.net to work with nginx you have to add usekestrel and URL in the program.cs file.

The result is below

If I don't set tenant resolvers, all works fine, but if I set tenant resolvers it fails to work.

Any known issue / specific settings ?

Do I still need to set URL in module class ? Am using Unified Web Project

**Comment by maliming** [comment]
> If you use nginx as a reverse proxy server, please note that if TenantKey contains an underscore or other special characters, there may be a problem, please refer to: http://nginx.org/en/docs/http/ngx_http_core_module.html#ignore_invalid_headers http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers

**Comment by maliming** [comment]
> "__tenant" by default.
> If you use nginx as a reverse proxy server, please note that if TenantKey contains an underscore or other special characters, there may be a problem, please refer to: http://nginx.org/en/docs/http/ngx_http_core_module.html#ignore_invalid_headers http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers

**Comment by dicksonkimeu** [comment]
Thank you for highlighting this.

Let me first address IdentityServer4 on Nginx; seems there are certain settings to take care of. Then I rename tenantkey(i know how to change this) to something else like accountid.

**Comment by olicooper** [comment]
Without any sample code it is difficult to help. A description of what is 'not working' too would help too. Also it might be worth mentioning what version you are on and type of project (api, mvc, console etc). I don't believe this is a bug but rather a question, so it might also be worth asking on Stackoverflow.

I have not needed to add any additional settings in the abp solution to make it work with kestrel if you have used the `Volo.Abp.Cli` to create the basic project. Logs are you friends, whenever I have issues with requests, I look to see what the requests look like as they come in to the server and trace back from there.

- The position of the tenant resolvers is important. Don't add any resolvers in position 0 as it will be a security issue. https://docs.abp.io/en/abp/latest/Multi-Tenancy#example-add-a-subdomain-resolver
- Are you using the correct urls in the `appsettings.json` for accessing directly from Kestrel? Possible CORS issue?
- Are you making curl requests on the same server the app is running as the test and appending the `__tenant` to the request headers or is the an external request?

My CreateHostBuilder in `Program.cs`
```csharp
internal static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        })
        .UseAutofac()
        .UseSerilog();
```

I hope this helps 👍

**Comment by dicksonkimeu** [comment]
great,

you are using ubuntu? this issue is no there in windows

**Comment by olicooper** [comment]
All my files are the same as the one in the templates, except they have more things in specific to my application. See the [module file](https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.HttpApi.Host/MyProjectNameHttpApiHostModule.cs) and [appsettings.json](https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.HttpApi.Host/appsettings.json)

As a test, I have just built and uploaded the basic project (version 2.5.0 using `abp new AbpBasic250 --ui angular`) to an Ubuntu-18.04 server running in Hyper-V and it works fine. The only difference is that I am using MySql instead of the default SqlServer. I have installed latest dotnet `sudo apt-get install aspnetcore-runtime-3.1` (3.1.3) and used `chown www-data -R /var/www/myproject` to ensure the file permissions are correct. I use supervisor to run the project.

I could access `/.well-known/openid-configuration`, `api/abp/application-configuration`, I was able to login via `/Account/Login` and fetch a list of tenants via the swagger UI. Everything seems fine.

Try starting with a basic project and get that working on Ubuntu first?

**Comment by olicooper** [comment]
I have just uploaded the angular client as another test. I am able to login as a tenant fine. 
You get some request errors if forward headers are not properly set. Essentially you need to make sure the `X-Forwarded-For` and `X-Forwarded-Proto` are passed from nginx to Kestrel so that IdentityServer creates the proper openid configuration etc.

HttpApiHostModule
```csharp
private void ConfigureCors(ServiceConfigurationContext context, IConfiguration configuration)
{
    // other stuff above..

    if (configuration.GetValue("App:Proxies:Enabled", false))
    {
        var rawKnownProxies = configuration.GetSection("App:Proxies:KnownProxyIPs").Get<List<string>>();
        var knownProxies = rawKnownProxies == null ? new List<IPAddress>() : rawKnownProxies
            .Select(o => IPAddress.Parse(o.RemovePostFix("/"))).ToList();

        var rawKnownNetworks = configuration.GetSection("App:Proxies:KnownNetworks");
        var knownNetworks = rawKnownNetworks == null ? new List<IPNetwork>() : rawKnownNetworks.GetChildren()
            .Select(o => new { IpPrefix = o.GetSection("IpPrefix").Get<string>(), PrefixLength = o.GetSection("PrefixLength").Get<int>() })
            .Select(o => new IPNetwork(IPAddress.Parse(o.IpPrefix.RemovePostFix("/")), o.PrefixLength))
            .ToList();

        context.Services.Configure<ForwardedHeadersOptions>(options =>
        {
            options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
            options.KnownNetworks.Clear();
            options.KnownProxies.Clear();
            knownProxies.ForEach(x => { options.KnownProxies.Add(x); });
            knownNetworks.ForEach(x => { options.KnownNetworks.Add(x); });
        });
    }
}

// other stuff...

public override void OnApplicationInitialization(ApplicationInitializationContext context)
{
    var app = context.GetApplicationBuilder();

    if (context.GetConfiguration().GetValue("App:Proxies:Enabled", false))
    {
        app.UseForwardedHeaders();
    }
}
```
appsettings.json (note the addition of "proxies" section):
```json
{
  "App": {
    "SelfUrl": "https://localhost:44333",
    "CorsOrigins": "https://*.AbpBasic250.com,http://localhost:4200",
    "Proxies": {
      "Enabled": true,
      "KnownProxyIPs": [ "127.0.0.1" ]
    }
  },
  "ConnectionStrings": {
    "Default": "server=127.0.0.1;uid=root;pwd=;database=abpbasic250"
  },
  "AuthServer": {
    "Authority": "https://localhost:44333"
  }
}
```

This may help for request logging but it isn't required:
```csharp
public override void OnApplicationInitialization(ApplicationInitializationContext context)
{
    //...  place after "app.UseRouting();"
    if (context.GetConfiguration().GetValue("Logging:EnableRequestLogging", false))
    {
        app.Use(async (context, next) =>
        {
            // Request host, method, scheme, and path
            Log.Information("Request Host: {Host}", context.Request.Host);
            Log.Information("Request Method: {Method}", context.Request.Method);
            Log.Information("Request Scheme: {Scheme}", context.Request.Scheme);
            Log.Information("Request Path: {Path}", context.Request.Path);

            // Headers
            foreach (var header in context.Request.Headers)
            {
                Log.Information("Header: {Key}: {Value}", header.Key, header.Value);
            }

            // Connection
            Log.Information("Request RemoteIp: {RemoteIpAddress}", context.Connection.RemoteIpAddress);
            Log.Information("Request RemotePort: {RemotePort}", context.Connection.RemotePort);

            await next();
        });
    }
```

**Comment by dicksonkimeu** [comment]
This is highly appreciated. 

I will test again after adding this settings.

**Comment by olicooper** [comment]
> I will test again after adding this settings.

Did this work for you in the end? If so, make sure to close the ticket :)
