### ISSUE TITLE
CLI proxy-gen supported features and roadmap

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#3630]
We are moving our  stable project with lot of API from ABP ZERO to ABP Framework.
We tried to process all that apis and generate proxies for them. Simple APIs goes without problems, but more compex proxies are generated with errors. I'm talking about errors in generated proxies code.

Most of them are generated because there is no support for generics (#3626). 
Ok. I can change Dtos to supported one like _ListResultDto<T>, PagedresultDto<T>_, etc.
But what are supported ? It will be nice if you make a list in cli documentation. Something is written in **Dto best practice** document, but it is not clear what is supported.

Another problem are missing models. For example: I have method that returns PagedResultDto<MyDataDto>. CLI generates service, import MyDataDto into service file, 
but there is no model for MyDataDto generated. Why ? I can't imagine. CLI returns no error.

What enums are supported ?
For example:

```
public enum UcnaPogodbaVrsta
    {
        IUP = 1,
        VUP = 2
    }
```
is converted to

```
import { UcnaPogodbaVrsta } from '../models';
import { ValueType } from './value-type';

export class UcnaPogodbaVrsta? extends ValueType {
  value: any;
  hasValue: boolean;

  constructor(initialValues: Partial<UcnaPogodbaVrsta?> = {}) {
    super(initialValues);
  }
}
```
Look imports. What is ValueType ? It is not generated.

There is problem with VoloSoft code too.
Feature service (ng) accept _UpdateFeaturesDto_ type in body. It is generated as:

```
export class UpdateFeaturesDto  {
  features: any[];
  constructor(initialValues: Partial<UpdateFeaturesDto> = {}) { ... }
  }
}
```
Look at feature property. It's declared as any[]. So without type. In c# it is declared like:

```
    public class UpdateFeaturesDto
    {
        public List<UpdateFeatureDto> Features { get; set; }
    }
```
And there are another ......

As i can see generator has limitations.
So please make a list with supported in unsupported features, make better documentation about this features and share with us plans you have with proxy generator. 
This will be very valuable for us when we decide how to continue our work.

Regards.

Edvin

**Comment by sebitsi** [comment]
@erolarkat Any news about proxy-gen progress ?

**Comment by leonkosak** [comment]
Based on https://github.com/RicoSuter/NSwag/issues/1398#issuecomment-555507846 response from Nov '19 for multiple file feature output (which is still not "published"), what advanteges will your custom proxy-gen have compared to nswag?

I tried generate proxy with abp v2.6.2 (monolithic app), and generated output was catastrophic. A lot of errors. If I resolve these issues manually, then the "update" would generate (overwrite) faulty files again.

In ANZ, nswag works flawlessly and really saves time and make frontend more robust, because many errors are detected during compile (transpiling) time.

Without reliable proxy generator gor Angular frontend, the development is noticeable slower.

**Comment by hikalkan** [comment]
closing this since we are completely re-writing the angular proxy-generation: https://github.com/abpframework/abp/issues/4881
