### ISSUE TITLE
Consider Rebus Integration for Distributed Event Bus

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#376]

**Comment by brunobertechini** [comment]
This can be a huge boost to not reinvent the wheel. Rebus is very good. I have integrated it with aspnetboilerplate in the past.

It will be even better to have the "wrapper" layer around it. I would consider an eventbus rather than specific transports (rabbitmq, activemq etc).

Enterprise Service Bus (rebus, nservicebus, etc) are much more than message queues and brokers.

I would like to participate in the discussion if possible

**Comment by hikalkan** [comment]
Thanks @brunobertechini for your thoughts. We will create an integration package for this. Any PR welcome :)

**Comment by kegumx** [comment]
Is MassTransit more appropriate? 
https://github.com/MassTransit/MassTransit
