### ISSUE TITLE
Custom PagedResultRequestDto filter cannot transfer '+' character to server

### ISSUE THREAD

**Issue by zachary-chi** [abpframework/abp#3934]
I have a custom PagedResultRequestDto which contains a property 'Filter' , when the filter string contains character '+', the character '+' was auto convert to space '  ' or deleted.

1. when the filter string contains only '+', the '+' was deleted
2. when the filter string contains not only '+', the '+' was convert to space ' '

I was observe the filter string value on the 'CreateFilteredQuery' function

`
public class PagedTestResultRequestDto : PagedResultRequestDto
    {
        public string Filter { get; set; }
    }
`

**Comment by maliming** [comment]
Can you explain the problem in detail?

**Comment by zachary-chi** [comment]
> Can you explain the problem in detail?

The abp version used is  2.7.0, and the UI framework is angular. I used the command 'abp generate-proxy' to generate services.

For example, the following application service contains a function test.
`
    public class TestAppService : CrudAppService<...>
    {
        public void Test(TestInput input)
        {

        }
    }

    public class TestInput
    {
        public string Filter { get; set; }
    }
`

If the Filter string is '123+456', it was received as '123 456' on the test function.

By the way ,if I used the swagger UI , the received '123+456' is ok.

I thought the problem was brought by the RestService on the '@abp/ng.core'?

Thanks

**Comment by maliming** [comment]
>  I used the command 'abp generate-proxy' to generate services.

Can you share the generated `ts` code?

**Comment by zachary-chi** [comment]
> > I used the command 'abp generate-proxy' to generate services.
> 
> Can you share the generated `ts` code?

Attached is the sample code, it seems that method 'get'  or 'post' make the difference.

[sample code.zip](https://github.com/abpframework/abp/files/4625755/sample.code.zip)
![Capture1](https://user-images.githubusercontent.com/61579833/81886801-30a3d180-95d0-11ea-8383-d868aefc07f9.PNG)
![Capture2](https://user-images.githubusercontent.com/61579833/81886810-35688580-95d0-11ea-9726-f2d2da5d0999.PNG)

**Comment by maliming** [comment]
hi
Try to encode the parameters.
```
input.filter = encodeURIComponent(`123+456`);
```

**Comment by zachary-chi** [comment]
> hi
> Try to encode the parameters.

Thanks. That would work. And I Use `Uri.UnescapeDataString` to parse the correct string on the server side.

By the way, am I supposed to do this `encodeURIComponent` and `Uri.UnescapeDataString`  every time for the string property? Or, would the Abp framewokr do the job?

Thanks

**Comment by maliming** [comment]
hi @mehmet-erim Is this a problem?

**Comment by mehmet-erim** [comment]
Yes @maliming, this is a problem.

@armanozak Is there any generic way to encode all query params?

**Comment by armanozak** [comment]
Hi @mehmet-erim,

Angular `HttpClient` does not encode the character `+`, because it uses a default [HttpUrlEncodingCodec](https://github.com/angular/angular/blob/698b0288bee60b8c5926148b79b5b93f454098db/packages/common/http/src/params.ts#L142) and that codec calls an encoder function named [standardEncoding](https://github.com/angular/angular/blob/698b0288bee60b8c5926148b79b5b93f454098db/packages/common/http/src/params.ts#L89), which restores an already encoded `+` back, among a few others. So, this is about Angular's client, not ABP.

However, IMHO, the `RestService` in the core package should (and currently does not) take an option called `encoder` (type: `HttpUrlEncodingCodec`) as a key in the config parameter (type: `Rest.Config`) and its default value should be `new HttpUrlEncodingCodec()` in order to comply with Angular defaults and be backwards compatible, while becoming flexible enough to get a custom `HttpUrlEncodingCodec`. Then, the following can be done:

```ts
import { HttpParameterCodec } from '@angular/common/http';

export const rfc3986CompliantEncodeURIComponent = (str: string) =>
  encodeURIComponent(str).replace(
    /[!'()*]/g,
    (substr: string) => "%" + substr.charCodeAt(0).toString(16)
  );

export class CustomHttpParamEncoder extends HttpUrlEncodingCodec {
  encodeKey(key: string): string {
    return rfc3986CompliantEncodeURIComponent(key);
  }
  encodeValue(value: string): string {
    return rfc3986CompliantEncodeURIComponent(value);
  }
}

// CustomHttpParamEncoder then will be passed to request method of RestService as encoder
```

Hi @zachary-chi,

I am afraid, this requires some development. Until then, you may try using the Angular `HttpClient` instead of the `RestService` and pass the custom encoder above to it.

**Comment by zachary-chi** [comment]
ok, thanks all @armanozak @mehmet-erim @maliming 
Hope to see the new feature of the encoder option on the `RestService` soon. Thanks
