### ISSUE TITLE
Module's template project naming

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#402]
The name of a module should contain CompanyName, ProjectName, ModuleName. 
For an application which has application A & application B that serves their own modules as remote services the CompanyName.ModuleName isn't a concept naming.

**Comment by hikalkan** [comment]
It depends..

For instance, background jobs module's solution name is `Volo.Abp.BackgroundJobs` which fits to `CompanyName.ProjectName.ModuleName` but blog module's name is `Volo.Blogging`.

When you create "additional" modules to an application, you are right. But if you are creating a reusable application independent module, we prefer 2-deep naming.

We could not found a way of properly providing 2-deep/3-deep naming for a single template. You can download with `CompanyName.ProjectName.ModuleName` naming now, but it will have some problems (uses dot instead of folders to separate CompanyName and ProjectName).

**Comment by hikalkan** [comment]
This is done with new templates.
