### ISSUE TITLE
[question]How do  the module in MicroService sample exchange each other?

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#4049]
I am using  in MicroService sample.   I cannot understand how the module works with  other  module.

example:

I got a `Product` List in `ProductManagement` , it has column `CreatorId`,

When I render a dataTable  in razor,   How can I get the Creator UserName to display?

Is there any way  for modules exchange? 

Can it  just use the Application Service  Interface ?

**Comment by hikalkan** [comment]
This is a typical problem in microservice architecture. A microservice (A) has Id of an entity inside another microservice (B). Then you need to know other properties of the entity (like name of the user in this case).

There are several solutions. I suggest you to search and read some articles about it. 

For this sample, we had a similar problem (blog service needs to get username since we need to write username of the blog post creator). We prefered to duplicate & synchornize the data like I explained in my microservice presentation (https://github.com/hikalkan/presentations/blob/master/2019-10-25-Microservices/Presentation.pptx).

**Comment by xyfy** [comment]
thank you



---Original---

**Comment by xyfy** [comment]
It is helpful,I will closed this issure

**Comment by xyfy** [comment]
I got a new issue in this scene

How can I pass the jwttoken  from a service to another,your ppt shows use `UseCurrentAccessToken`  with false ,

then it can not set the token to the called service. in the called service  the `ICurrentUser` will got null value

if I set it to true , in the called service  the `ICurrentUser` will got correct value

but I don't sure it will effect other things.

**Comment by afresh** [comment]
> I got a new issue in this scene
> 
> How can I pass the jwttoken from a service to another,your ppt shows use `UseCurrentAccessToken` with false ,
> 
> then it can not set the token to the called service. in the called service the `ICurrentUser` will got null value
> 
> if I set it to true , in the called service the `ICurrentUser` will got correct value
> 
> but I don't sure it will effect other things.

I set `UseCurrentAccessToken` to true, but the `ICurrentUser` got null value. Why?
