### ISSUE TITLE
Consider providing all the permission name constant objects in abp.js.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#4125]
Current permission check in JavaScript uses permission strings
```js
abp.auth.isGranted('AbpIdentity.Roles.Create')
```

We can consider using permission JavaScript objects.
```js
abp.auth.permissions.abpIdentity.roles.create = "AbpIdentity.Roles.Create";

abp.auth.isGranted(abp.auth.permissions.abpIdentity.roles.create)
```

**Comment by hikalkan** [comment]
Thanks maliming. You know JavaScript is not type safe. So, what is the point of writing `abp.auth.permissions.abpIdentity.roles.create` instead of `AbpIdentity.Roles.Create`?.

Probability of wrong typing in JavaScript code is equal.

In addition, when you later rename the permission (like changing `AbpIdentity.Roles.Create` to `AbpIdentity.Roles.CreateRole`), you will need to change all names in the JavaScript code in both cases.
