### ISSUE TITLE
Work on language / culture name differences between libraries

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4150]
We are using client side localization for some libraries like;

- JQuery Validation
- Datepicker
- Luxon

However, some of this libraries are using different language names than .NET. We've made some tricks to aling the names:

https://github.com/abpframework/abp/blob/f43b5ec3d3ff9eb1125b2af027a4a41abc088937/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/dom-event-handlers.js#L75-L81

However, we should check it more and better understand (and fix/document?) these differences.

**Comment by hikalkan** [comment]
@maliming I assigned this you. Before starting any development, please analyse it and write what we can do to solve this problem in a consistent way. Thanks.

**Comment by maliming** [comment]
@hikalkan 

We can introduce `LocalizationMapOptions`.  In this way, developers can solve the language code &  language filename mapping problem through options, because we cannot set all mappings in advance.

In **angular**, it may be necessary to map the file names of localized modules, such as `zh-Hans` => `zh.js` module. This is similar to the standard package: https://github.com/abpframework/abp/pull/2972

```cs
public class LocalizationMapOptions
{
      // jquery-validation => {zh-Hans: zh-CN}
      // Datepicker => {zh-Hans: zh}
     public Dictionary<string, NameValue> LanguageMap {get; set;}

      // jquery-validation => {zh-Hans: zh-CN}
      // Datepicker => {zh-Hans: zh}
     public Dictionary<string, NameValue> LanguageFileNameMap {get; set;}
}
```

This code is generated dynamically.
```js
abp.localization.languageMap["jquery-validation"].map('zh-Hans': 'zh-CN');
abp.localization.languageMap["Datepicker"].map('zh-Hans': 'zh');

abp.localization.languageFileNameMap["jquery-validation"].map('zh-Hans': 'zh-CN');
abp.localization.languageFileNameMap["Datepicker"].map('zh-Hans': 'zh');
```

```js
abp.localization.languageMap.get("jquery-validation", abp.localization.currentCulture.name)
```

We can also consider refatoring `BundleContributor`. Make it support `LocalizationMapOptions`.

https://github.com/abpframework/abp/blob/b65aecafdc25ae50a77362315a701d37aaca875d/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Packages/Volo/Abp/AspNetCore/Mvc/UI/Packages/BootstrapDatepicker/BootstrapDatepickerScriptContributor.cs#L12-L15

**Use one solution to solve the problem of language codes and language files in mvc+angular.**

**Comment by hikalkan** [comment]
I think your solution is pretty fine. You can go and implement it. Thanks.
We can then fill this options as we can do.

However, I suggest to not introduce a new options class and use the existing AbpLocalizationOptions.

**Comment by wakuflair** [comment]
Hi all

The culture map feature is great! (I think the 3.0 post should has its position :blush: )

However, will this be done?

> We can also consider refatoring `BundleContributor`. Make it support `LocalizationMapOptions`.

The bundle contributors now still use a static culture name, e.g:

https://github.com/abpframework/abp/blob/eac15a232943f76a498f84343ee1235c107d498a/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Packages/Volo/Abp/AspNetCore/Mvc/UI/Packages/Timeago/TimeagoScriptContributor.cs#L19

**Comment by maliming** [comment]
@wakuflair 

I will check all `ScriptContributor`.
https://github.com/abpframework/abp/issues/4574
