### ISSUE TITLE
ABP generate-proxy with multiple angular projects

### ISSUE THREAD

**Issue by lukebooroo** [abpframework/abp#4181]
Abp package version. 2.8.0
Your base framework: .Net Core.

I'm using angular-cli with multiple angular projects. Documented here:
https://angular.io/guide/file-structure#multiple-projects

There doesn't seem to be a way of selecting which project to put the ABP code into. It simply places it in to /src/app which does not exist in this sort of cli project.

Also, it doesn't seem that in a regular cli app there's a way of putting the files anywhere but the root src/app folder.

Thanks :)

**Comment by armanozak** [comment]
Hi @lukebooroo,

There actually is a way to do that:

```
abp generate-proxy --module identity --apiUrl "https://example.com/api" --out apps/example-app/src/app
```

However, currently, there is a problem with the --out parameter. You may follow [the issue here](https://github.com/abpframework/abp/issues/4375) for the progress.

Please let me know if this answers your question.

Thanks for your contribution. It is most appreciated.

Have a nice day.

**Comment by armanozak** [comment]
Closing since there already is [an open issue](https://github.com/abpframework/abp/issues/4375) for tracking this subject.

**Comment by lukebooroo** [comment]
@armanozak  That's great, thank you!
