### ISSUE TITLE
generate-proxy without @ngxs and @angular/router dependency?

### ISSUE THREAD

**Issue by lukebooroo** [abpframework/abp#4213]
I'm trying to use generate-proxy for an existing project. We're not using @angular/router, which is a requirement of @ngxs. Is there a way to use generate proxy to create a class using only HttpClient?

**Comment by hikalkan** [comment]
@mehmet-erim can you discuss this with @armanozak ?

**Comment by mehmet-erim** [comment]
Hi @lukebooroo

A generated service via the `generate-proxy` command uses the [RestService](https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/core/src/lib/services/rest.service.ts) that is imported from @abp/ng.core. We use the Rest Service for some benefits.

If you're not using the @angular/router and @ngxs/*, you don't use the @abp/ng.core, right?

See @abp/ng.core dependencies:

```json
 "dependencies": {
    "@abp/utils": "^2.9.0",
    "@angular/localize": "~9.1.9",
    "@ngxs/router-plugin": "^3.6.2",
    "@ngxs/storage-plugin": "^3.6.2",
    "@ngxs/store": "^3.6.2",
    "angular-oauth2-oidc": "^8.0.4",
    "just-clone": "^3.1.0",
    "just-compare": "^1.3.0",
    "snq": "^1.0.3",
    "ts-toolbelt": "^6.3.6"
  }
```

Would you like to use the HttpClient instead of the RestService, you can change the generated services content easily.

An API call via RestService:
```ts
 getList(params = {} as PagedResultRequestDto) {
    return this.restService.request(
      {
        url: '/api/text-template-management/template-definitions',
        method: 'GET',
        params,
      },
      { apiName: this.apiName },
    );
  }
```

The same API call via HttpClient:

```ts
getList(params = ({} as PagedResultRequestDto) as { [key: string]: any }) {
  const apiUrl = environment.apis[this.apiName].url;

  return this.httpClient
    .request('GET', `${apiUrl}/api/text-template-management/template-definitions`, {
      params,
    })
    .pipe(
      catchError(err => {
        // handle error here
        return of(null);
      }),
    );
}
```

Maybe we'll add an option to create services without RestService.

**Comment by lukebooroo** [comment]
@mehmet-erim Thank you for your detailed example. In the end I copied your RestService and removed the unwanted dependencies so that I can keep the generated services largely the same.

**Comment by John0King** [comment]
@lukebooroo   I'm strongly recommended to remove all those dependencies.
1)  angular's service is enough   for state management (remove @ngxs  and router)  , service is simple and easy for any kind of angular project.
2)  `${apiUrl}/api/text-template-management/template-definitions`   I'm thinking no one will do this,  because `HttpClient` has `intercepters`  we use `intercepters` to combine the url and  add/refresh the token ,  so we write `this.httpclient.post("/api/somapi", data)`
3)  since the authentication is done by `intercepters` ,  we can remove `angular-oauth2-oidc` (maybe you need in the default template, but not everyone like the default template right ?   I'm using  https://ng-alain.com/)

so  to continue to support current tempalte,  you can still generate the `restServeice` based proxy.
and also add an new command `abp light-proxy `  or add an option `abp generate-proxy --light`  ,
and the new generated should like this.

```ts
// abp light-proxy  --base-type  
add all the `PagedAndSortedResultRequestDto`  `AggrateDto` type

// abp light-proxy 

@Injectable({ provindeIn:'root' } )
export class SomApiSerivce{

   constructor(private http:HttpClient)

    getList(params : ApiInput):Obseralbe<PageResult<ApiDto>>{
       return this.http.reqest(.......)
   }

 ....
}

```

those proxy can be use in any kind of Angular project, including the current template one.

**Comment by bnymncoskuner** [comment]
This issue is not valid anymore, since the proxy generation doesn't depend on `ngxs` or `angular/router`
