### ISSUE TITLE
Where can I find documentation about Angular ABP components?

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#4328]
I have various problems with Angular ABP components.

For instance, `abp-lookup-select`:

1) I need it to have default option "Select ..." and have no idea how to add it;
2) I need to fire onchange event and use the selected _id_ - and don't know how to do that as well;

The same problem relates to other Angular ABP components.
Could you please point me where I can read about **all Angular ABP components** and how to use them (examples)?

**Comment by mehmet-erim** [comment]
Hi

We have not documented all components, services, etc. yet. We'll complete the missing documents soon. You can find the current docs at [docs.abp.io](https://docs.abp.io) (Menu -> User Interface -> Angular).

Unfortunately, both can't be done with the `abp-lookup-select`. But `abp-lookup-select` is a basic component. You can create your own component and use it instead of the `abp-lookup-select`.

Here is the source code of the component:
https://gist.github.com/mehmet-erim/75849eaeb3ad547f2c752a8373fb36be

**Comment by alexandis** [comment]
Thank you for the update!
