### ISSUE TITLE
Custom Error Page

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#4463]
Hi,

I'm looking to customize my error page. 

For now I use the following:
`app.UseErrorPage();`

But also, I have added my own 'Error.cshtml' page (Pages/Error.cshtml). But it seems that another default page is called.

Is it possible to change, and how ?

**Comment by cihangll** [comment]
Hi @vd3d ,
You can check https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/Views/Error/Default.cshtml. This is a default error page.

Use `Views/Error/Default.cshtml` page instead of `Pages/Error.cshtml`.

If you want to more detailed Exception page example, then you can check https://github.com/liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla/blob/master/src/Views/Error/Default.cshtml.

**Comment by 1alikhan** [comment]
You can override the error component for the underlying theme you are using as well. e-g For **LeptonX** its `ErrorView.razor`
