### ISSUE TITLE
Not sure it is a bug or a feature, my consumer only consumes one-half published messages.

### ISSUE THREAD

**Issue by yangfan-zz** [abpframework/abp#4622]
**Volo.Abp.EventBus.RabbitMq** 3.0

Steps to reproduce:
1> Created a dedicated consumer project and a publisher project.
2> See screenshot below, my consumer only consumes one-half messages.
![image](https://user-images.githubusercontent.com/59385737/86510260-cca7c780-be20-11ea-8d04-59379a1d7c42.png)
![image](https://user-images.githubusercontent.com/59385737/86510356-8868f700-be21-11ea-9429-dd6f177bd6a4.png)

Possible reason:
By default, the event bus embedded a consumer to consume published message in round robin way.

**Comment by liangshiw** [comment]
Publishers are also consumers.

![image](https://user-images.githubusercontent.com/16813853/86515798-3ab6b380-be4e-11ea-8754-c7d5109f2f2c.png)


See the example : https://github.com/abpframework/abp-samples/tree/master/RabbitMqEventBus

**Comment by yangfan-zz** [comment]
Clear, but it's weird, because my publisher has not been implemented the handler to consume messages. It would be good if I can overwrite the Initialize(), possibly use virtual in ABP source code, or add an option to stop consuming messages in publisher.

**Comment by jimmidier** [comment]
I guess you provided same ClientNames for both clients. According to ABP source codes publishers are designed to be consumers  because ClientName is required during configuration to declare queues. If one client does not consume anything, which you take as publisher, the queue it listens to will be just blank. In your case if you provide same ClientNames for both clients then RabbitMQ will average messages to both of them because they both consume the same queue. If that's the case, try provide different ClientNames.

**Comment by yangfan-zz** [comment]
@jimmidier Thanks, it works. I think there may be better solution from the point view of architecture.

**Comment by xyfy** [comment]
@jimmidier  Cool,I got the same err, came the same **ClientNames **
