### ISSUE TITLE
Custom Angular UI

### ISSUE THREAD

**Issue by uwascan** [abpframework/abp#4632]
Great job on the v3 release.
@hikalkan  is it possible to do a custom angular UI client for ABP Framework? I Love the framework but it appears the angular client is strongly coupled to the default design (Bootstrap based), Any Guidance will be appreciated.

Thank you

**Comment by armanozak** [comment]
Hi @uwascan,

Thanks.

The UI, not only Angular but also MVC, creates HTML according to Bootstrap, but ABP modules are not dependent on the default themes (free or commercial). In other words, they are designed to work with custom themes as long as they are made according to Bootstrap. If a Bootstrap theme does not work well with ABP modules, there are two possible reasons for that:

1. The theme depends on some custom HTML or styles (element hierarchy, non-Bootstrap classes, data attributes, id’s, etc) to work.
2. We made a mistake.

If you find out there is any strong coupling with our own themes, please create an issue, because this is not our intention, it may be a bug.

If, on the other hand, you find out the theme you are trying to implement has

**Comment by heitorgiacomini** [comment]
I hate boostrap, Why the hell to they style default html tags like div, button, p. Why doesn't do they create custom components on custom class for each css style. It didn't cross their minds, that by applying the style globally, automatically it would be really difficult to use other libraries?
