### ISSUE TITLE
A big fan's suggestion on the ABP commercial

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#4898]
Hi @hikalkan and other Volo-Man. I'd like to talk about what I think about the ABP commercial. 

There are some suggestions: 

1. **ABP commercial can be open-source.**
    * Potential customers can try it out, more people know how great the ABP commercial is!
    * Module developers can make modules based on the ABP commercial's features.
    * A company with real income doesn't dare to use piracy. Pirated users use the ABP commercial for study or to develop apps for the business projects that haven't been successful yet, and they are also good missionaries, aren't they? 🤣

2. **The commercial licenses could be adjusted.**
    * No license
        * Can use the commercial framework and a few basic commercial modules **only for study**.
    * The basic license
        * Can use the commercial framework and a few basic commercial modules.
        * Can buy more commercial modules in market.abp.io.
        * This license does not provide services.
        * It sells for a low price since it brings the market share, you know.
    * The secondary license (based on the previous license)
        * Can use all the commercial modules for free.
        * Provide limited services.
    * More advanced licenses
        * Provide more services and get more privileges.

It is well known that Unity3D, Office, Windows, and more successful products are using similar business models. It's all for a higher market share and a more active community.

The above is just a big fan's idea. I will always support Volo's decision. ❤️

**Comment by ltm0203** [comment]
Well, that's a good idea.
But the problem is that Volosoft's legal and compliance departments are missing.
And the development circle itself is a minority, it is hard to grab what kind of market, because everyone knows this module is good, but the biggest problem is not the code, but the matching staff can not keep up.

**Comment by hikalkan** [comment]
Thank you for your suggestions. I will write a longer reply. Just wanted to inform you that I've read it and will discuss with the team.

**Comment by gdlcf88** [comment]
Another important thing: the ABP market needs to be launched as soon as possible.

Maybe the prosperity of the community and the Volo's business opportunities are all in the market. It could sell not only modules but also consulting services and development services.

People and companies (including Volosoft) can compete in the market, no matter who sells the module well, Volo can get the commission and the market share of the framework.

In this context, **market.abp.io** is very similar to **store.playstation.com**.

**Comment by hikalkan** [comment]
market.abp.io is or big ideal and we also want to lunch it as soon as possible. There are a lot of work (related or not related to the market) to be done, but we don't want  to wait it too much.

**Comment by leonkosak** [comment]
We had conversation with @sebitsi and we came to the conclusion that there would be noticeable less issues if developers could see Commercial code.
When we started with ANZ, we had a lot of real-world code examples inside your code. That helped us a lot (maybe in some cases more than documentation).
abp documentation is improving without any doubt, but sometimes it's just faster and easier to find similar solution in the code that you know that exists and where. :)
If you have fewer "question issues" you would also benefit from that point of view.

**Comment by Y2zz** [comment]
I haven't paid attention to abp for a while, and learned from the community that it seems that the commercialization of abp is a bit serious now?
But i have always been abp but a big fan

**Comment by hikalkan** [comment]
@leonkosak ABP Commercial Business and Enterprise licenses include the full source code of all the modules. So, you can see the source code :)
In addition, we are continously adding open source modules. There are more than 10 open source modules ([see](https://github.com/abpframework/abp/tree/dev/modules)). We just have started to work on a useful module, [CMS Kit](https://github.com/abpframework/abp/tree/dev/modules/cms-kit). So, there are a lot of codebase to learn.

@Y2zz comparing to AspNet Boilerplate & AspNet Zero, we are adding much much more feature to the open source side with the ABP Framework. To be honest, we are spending our most of the total effort to the open source side and the open source side (the framework especially) is harder to build & document. We think the open source side is very strong.
So, no worry, ABP Framework is a real open source project and will always remain like that. However, it is essential to gain money from this project, otherwise we can not survive and the open source side can not be improved too. So, ABP Commercial should also provide a good value. And we think it provides. We are trying to make it balanced 😃

**Comment by torronen** [comment]
If working with Abp.io commercial, but then at some point would like to publish our solution as open source, are there restrictions on that? At least, we would need to remove commercial modules. Apart from that are there other licensing issues, such as code created with Abp Suite?

**Comment by maliming** [comment]
hi @torronen 

You can send an email to info@abp.io to learn more info about ABP commercial.
