### ISSUE TITLE
/api/abp/application-configuration endpoint takes long time?

### ISSUE THREAD

**Issue by mertglcan** [abpframework/abp#4925]
Hi,i downloaded bookstore template with angular ui.And i apply step by step all parts of tutorials at documentation until 2.part then when i run angular ui project it takes too long time. the reason is /api/abp/application-configuration this endpoint response like 10 min .but i couldnt solve why it takes too long time.

**Comment by liangshiw** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

In addition, maybe you need to install redis https://github.com/abpframework/abp/issues/2764.

**Comment by mertglcan** [comment]
To install redis fix this problem thank you.
