### ISSUE TITLE
[Bug/Documentation] FullAuditedAggregateRootWithUser

### ISSUE THREAD

**Issue by kanadaj** [abpframework/abp#4936]
The documentation mentions using `FullAuditedAggregateRootWithUser` with EF Core for navigation properties; in certain cases I feel this makes sense as the given entity might not make sense without it's owner/creator, but querying it from the user side would not be ideal in case of a one-to-many list.

The main issue I was having is that using FullAuditedAggregateRootWithUser requires you to explicitly `b.Ignore()` the navigation properties for migrations to work, otherwise `Add-Migration` throws the following exception:
```
The property 'AppUser.ExtraProperties' could not be mapped, because it is of type 'Dictionary<string, object>' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
```

I feel like the framework should either contain a work-around to allow foreign key mappings to the `AppUser` table via navigation properties, or the documentation should explicitly include the code needed for ignoring the navigation properties and then adding foreign key constraints via the fluent API.

Edit: It appears that adding the relationship via the Fluent API even without a navigation property results in the same error, so this seems like it needs manual modification of the generated migrations...

**Comment by JadynWong** [comment]
[https://docs.abp.io/en/abp/latest/Entity-Framework-Core#configurebyconvention-method](https://docs.abp.io/en/abp/latest/Entity-Framework-Core#configurebyconvention-method)

**Comment by kanadaj** [comment]
@JadynWong My definitions use `ConfigureByConvention()` but it does _not_ help with the migration issue. The navigation property has to be explicitly ignored for classes that implement `IMayHaveCreator<TCreator>`, `IModificationAuditedObject<TUser>` and/or `IDeletionAuditedObject<TUser>`; or their aggregate `FullAuditedAggregateRootWithUser<TKey, TUser>` via:

```cs
            builder.Entity<MyEntityWithUser>(b =>
            {
                b.Ignore(x => x.Creator);
                b.Ignore(x => x.LastModifier);
                b.Ignore(x => x.Deleter);
            });
``` inside
```cs
ProjectMigrationsDbContext.OnModelCreating`, otherwise `Add-Migration` and `Remove-Migration` result in errors. This behaviour is undocumented, so it's _either_ a documentation issue or an implementation issue. `ConfigureByConvention` has absolutely nothing to do with this.

**Comment by JadynWong** [comment]
Can you share a demo project?I can't understand.

**Comment by kanadaj** [comment]
@JadynWong https://github.com/kanadaj/AbpMigrationErrorRepro
`Add-Migration` fails with error.

https://github.com/kanadaj/AbpMigrationErrorRepro/blob/master/src/Project.EntityFrameworkCore.DbMigrations/EntityFrameworkCore/ProjectMigrationsDbContext.cs#L43 this is the fix but it's not in the documentation. Either fix the error or add the solution to the docs.

**Comment by JadynWong** [comment]
@kanadaj I understand the problem.The `AppUser` can't be identified on the `DbMigrations` project.Ignoring it is a way.We need official personnel to provide a common way to use user navigation attributes in migration projects.

The migration configuration of `AppUser` is not included in the migration project, so the navigation property cannot recognize it.

We can use efcore's "table-split" technology . see it [https://docs.microsoft.com/en-us/ef/core/modeling/table-splitting](https://docs.microsoft.com/en-us/ef/core/modeling/table-splitting)

We can use it like this.
(Move `AppUser` fluent config to DbContextModelCreatingExtensions)
https://github.com/JadynWong/AbpMigrationErrorRepro/blob/e9e9aa1af6c7b639df2d7928d841a7c2145efef1/src/Project.EntityFrameworkCore/EntityFrameworkCore/ProjectDbContextModelCreatingExtensions.cs#L14-L46


Hi @maliming, @hikalkan  what do you think?
Is it possible to use it in the startup template

**Comment by JadynWong** [comment]
Sorry, I found that this is not a better way, if we need to isolate the efcore context before different modules. I have to call `ConfigureIdentity` in the project `DbContextModelCreatingExtensions`, because it requires that IdentityUser must also be configured in the current project context.

**Comment by hikalkan** [comment]
IdentityUser is designed to be used by the Identity module which has its own identity dbcontext.
AppUser uses the same table and should be used by the application and defined by the application dbcontext.

Identity dbcontext should not know the AppUser and application dbcontext should not know the IdentityUser. Otherwise, EF Core doesn't work properly as it has some its own rules and restrictions. It is definitely not designed for such a modular system we have. I've requested a feature that can make this much easier, but Microsoft has rejected it: https://github.com/dotnet/efcore/issues/19046

We tried to explain the EF core multi-dbcontext & migration pattern we are using with the startup templates: https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Migrations

Based on this info, you should design/map your entities yourself. Nothing to do in the framework level. If you have any good suggestion, we may consider to implement it.

**Comment by JadynWong** [comment]
Hi @hikalkan, I absolutely agree with you.

Docs [https://docs.abp.io/en/abp/latest/Entities#auditing-base-classes](https://docs.abp.io/en/abp/latest/Entities#auditing-base-classes)
For `...WithUser` audit base classes, although it is not a best practice in audit root. However, some users still use it because abp provides it.

Does this mean that if we use the `...WithUser` audit base classes, we must manually set to ignore the `AppUser` navigation property in the DbMigrations project?

Because `AppUser` is a shared table with IdentityUser, we cannot configure it in the DbMigrations project.
Is there a better way to avoid configuring everywhere to ignore the `AppUser` navigation property?Or did I overlook some documents?
Thanks.

**Comment by hikalkan** [comment]
Hi @JadynWong 

The problem is not unique to the `...WithUser` base classes. Assume that you have a Product class with has a navigation property to the AppUsers. You will have the same problem and you need to manually handle (ignore / map) this property in the migration dbcontext. Also, the problem is not unique to user. Whenever you try to reuse a table between two modules you will have the same problem because EF Core has not a built-in way to solve it.

But I know that many developers are having to the same problem when they don't understand the system. We can try to reduce the change by introducing a system in the ABP Framework level. For example, a `[SharedWith(typeof(IdentityUser))]` (the naming seems bad to me, yes) on the AppUser attribute may help the ABP framework to understand the situation and ignore/map it automatically. We will work on this. Follow https://github.com/abpframework/abp/issues/5001

**Comment by kanadaj** [comment]
@hikalkan In the meantime, wouldn't it be best to include this peculiarity in the ...WithUser documentation for transparency?

**Comment by hikalkan** [comment]
As I said, it is not unique to WithUser. As I observed it, most of the developers are defining navigation properties to User in some other way, most of them don't know the WithUser classes at all. But, ok, I will add a small not and refer to the EF Core migration document.

**Comment by hikalkan** [comment]
Added note: https://github.com/abpframework/abp/commit/3fd143d04d093c32864e1c75c9b6f49274a289ad
