### ISSUE TITLE
EntityChanges on MongoDb environment

### ISSUE THREAD

**Issue by carloszan** [abpframework/abp#5031]
Version: 3.0.4

Well, as [docs](https://docs.abp.io/en/abp/latest/Audit-Logging) are saying, entity changes are not working for mongodb module. So, what I'm doing is I'm writing my own IAuditLogRepository.GetEntityChangeListAsync but of course, I inherit from MongoAuditLogRepository and override GetEntityChangeListAsync.
But the problem is: my audit logs doesn't save EntityChanges in AuditLogsInfo objects. I don't know if the problem is on AbpAuditingMiddleware or somewhere else. I also put the code below on my module for it to know what entity I want to save - **besides** the entity is with [Audited] decorator:
```
Configure<AbpAuditingOptions>(options =>
{
    options.EntityHistorySelectors.Add(new Volo.Abp.NamedTypeSelector("My selector", (type) =>
    {
        return type == typeof(MyEntity);
    }));
});
```

Can anyone tell why this EntityChanges are not being saved? Do i have to override something?

Thank you!

**Comment by hikalkan** [comment]
MongoDB has not a change tracking system, so we can't know the changed properties of an entity when it is updated.
Entity histories implemented for EF Core since it provides these changed entities on DbContext.SaveChanges.

>my audit logs doesn't save EntityChanges in AuditLogsInfo objects

If it was saving EntityChanges in AuditLogsInfo object, then we would already implement it. That's the essential problem.

So, this feature will not be available for mongodb unless we implement a custom change tracking system, which is not a simple work. There are some libraries (like https://github.com/joelweiss/ChangeTracking) which may simplify it.

**Comment by carloszan** [comment]
Thanks. Now I understand the correct problem!
