### ISSUE TITLE
Error loading library

### ISSUE THREAD

**Issue by wocar** [abpframework/abp#507]
I'm using the default template, how can I fix this ty

> GET http://localhost:53929/libs/lodash/lodash.min.js?_v=0 net::ERR_ABORTED 404 (Not Found)

> <script src="/libs/lodash/lodash.min.js?_v=0" type="text/javascript"></script>

**Comment by hikalkan** [comment]
It should be fixed with the latest template.
Can you run `yarn` (or `npm install`), then 'gulp' in the Web project's folder?

**Comment by wocar** [comment]
> npm install lodash 

> gulp

?

**Comment by hikalkan** [comment]
No, lodash is already installed. Just run "npm install" (or "yarn" as better) to restore packages. Then run "gulp".

**Comment by hikalkan** [comment]
Lodash.min.js is already there in the latest template: https://github.com/abpframework/abp/blob/master/templates/mvc/src/MyCompanyName.MyProjectName.Web/wwwroot/libs/lodash/lodash.min.js
Are you using an old template (because this problem was exists). If so, then upgrade `@abp/aspnetcore.mvc.ui.theme.basic` package to 0.4.9 (see https://github.com/abpframework/abp/blob/master/templates/mvc/src/MyCompanyName.MyProjectName.Web/package.json#L6) then run `yarn` (or `npm install`), then 'gulp' in the Web project's folder

**Comment by wocar** [comment]
Ran NPM install
ran gulp

ensured package version 0.49

![image](https://user-images.githubusercontent.com/9215073/46501697-d6377200-c7eb-11e8-8dc1-606515b6e226.png)

![image](https://user-images.githubusercontent.com/9215073/46501737-efd8b980-c7eb-11e8-9310-5a1a8083e29b.png)

folder is not there :(

**Comment by hikalkan** [comment]
Strange! Can you try to download a new template and run npm install and gulp again. If it has a problem then we work to fix it.

**Comment by wocar** [comment]
Ended up adding the following code to `abp.resourcemapping`
  ```
mappings: {
        "@node_modules/moment/min/moment-with-locales.min.js": "@libs/moment/js/",
        "@node_modules/lodash/dist/**": "@libs/lodash/",

    }
```
