### ISSUE TITLE
how to solve System.ArgumentNullException : Value cannot be null. (Parameter 'provider')

### ISSUE THREAD

**Issue by wuuer** [abpframework/abp#5099]
encounter this exception when running the unitest of the official sample demo BookStore-Mvc-EfCore 

System.ArgumentNullException : Value cannot be null. (Parameter 'provider')

ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
    ApplicationService.LazyGetRequiredService[TRef](Type serviceType, TRef& reference)
    ApplicationService.LazyGetRequiredService[TService](TService& reference)
    ApplicationService.get_AsyncExecuter()
    BookAppService.GetListAsync(PagedAndSortedResultRequestDto input) line 73
    BookAppService_Tests.<Should_Get_List_Of_Books>b__3_0() line 29
    BookStoreTestBase`1.WithUnitOfWorkAsync(AbpUnitOfWorkOptions options, Func`1 action) line 34
    BookAppService_Tests.Should_Get_List_Of_Books() line 26
    --- End of stack trace from previous location where exception was thrown ---

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem.

**Comment by maliming** [comment]
Github's action doesn't report any error.

https://github.com/abpframework/abp-samples/actions

**Comment by wongkhaimeng** [comment]
Hello.

I am having the same exception when accessing the `ObjectMapper` instance in an `ApplicationService` concrete class.
The version I am using is 3.3.2.

`
System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Volo.Abp.Application.Services.ApplicationService.LazyGetRequiredService[TRef](Type serviceType, TRef& reference)
   at Volo.Abp.Application.Services.ApplicationService.LazyGetRequiredService[TService](TService& reference)
   at Volo.Abp.Application.Services.ApplicationService.get_ObjectMapper()
`

And I could not figure out what am I missing that caused the ABP framework to not be able to obtain an instance of `IServiceProvider`.

**Comment by maliming** [comment]
hi @wongkhaimeng 
* Steps needed to **reproduce** the problem.

**Comment by wongkhaimeng** [comment]
[WebApplication1.zip](https://github.com/abpframework/abp/files/6923258/WebApplication1.zip)

Hi. Here's an example application implementing basic ABP things.
If you debug this program, put a breakpoint at the Controller calling the `ApplicationService` instance that was injected. When you step over, it will cause an exception with the same error:

`
System.ArgumentNullException: Value cannot be null. (Parameter 'provider') at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType) at Volo.Abp.Application.Services.ApplicationService.LazyGetRequiredService[TRef](Type serviceType, TRef& reference) at Volo.Abp.Application.Services.ApplicationService.LazyGetRequiredService[TService](TService& reference) at Volo.Abp.Application.Services.ApplicationService.get_ObjectMapper()
`

Hopefully it can be pinpointed what is missing from this solution. I suspect it is a missing `DependsOn` module, but it was not clear due to the lack of documentation/example.

**Comment by maliming** [comment]
@wongkhaimeng 

Please add the `AbpAutofacModule` to your application.

```cs
 <PackageReference Include="Volo.Abp.Autofac" Version="3.3.2" />

typeof(AbpAutofacModule)

Host.CreateDefaultBuilder(args)
    .ConfigureWebHostDefaults(webBuilder =>
    {
        webBuilder.UseStartup<Startup>();
    })
    .UseAutofac();
```

**Comment by wongkhaimeng** [comment]
@maliming 

Thank you so much, it worked! I actually tried setting all these up before, but it failed previously probably because I did not put the `DependsOn(typeof(AbpAutofacModule))` in the module where the `ApplicationService` classes were.

Now it is working once I did that. Thanks again.
