### ISSUE TITLE
 identityuserorganizationunit cannot be extended

### ISSUE THREAD

**Issue by FingersMusic** [abpframework/abp#5312]
Can identityuserorganizationunit inherit the ihasextraproperties interface, because I need to sort by user's department

**Comment by gterdem** [comment]
@FingersMusic, 
Can you explain a bit more about your use case? Your users has departments different than organization units?

**Comment by FingersMusic** [comment]
@gterdem I need to add a sortid field to the abpuserorganizationunits

**Comment by gterdem** [comment]
@FingersMusic I don't think IdentityUserOrganizationUnit entity can be extended since it is an associative entity (junction table) which doesn't exist in NoSql db contexts such as MongoDb.

Did you try sorting users by their organization units (by Id, Code, Name etc) with an extra repository method? What problems did you come across?
