### ISSUE TITLE
Create auto controller routes in kebap-case

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#5325]
The current implementation uses camelCase.
Change this behavior to kebap-case-plural or enable users to set the endpoint manually, (because plural of a word can be hard and needs a library to find.)

![image](https://user-images.githubusercontent.com/9526587/92391655-bde1d780-f125-11ea-866f-493320219c9c.png)

**Comment by PMExtra** [comment]
For now, you can do that:
In `src/{Namespace}.{Project}.HttpApi.Host/{Project}HttpApiHostModule`:
```cs
private void ConfigureConventionalControllers()
{
    Configure<AbpAspNetCoreMvcOptions>(options =>
    {
        options.ConventionalControllers.Create(typeof({Project}ApplicationModule).Assembly, setting =>
        {
            setting.UrlControllerNameNormalizer = context => context.ControllerName?.Pluralize().Kebaberize();
            setting.UrlActionNameNormalizer = context => context.ActionNameInUrl?.Kebaberize();
        });
    });
}
```

Edited:

`Pluralize()` and `Kebaberize()` are both from https://github.com/Humanizr/Humanizer

If you use underline naming style you may need also `Dasherize()`.

Thank @maliming for recommending Normalizer

**Comment by maliming** [comment]
It is better to use https://github.com/Humanizr/Humanizer  to convert the name. As far as I know, many libraries such as EF Core use it.

**Comment by PMExtra** [comment]
@maliming Great! I got that from https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md#new-behavior-12 :
> EF Core now includes a pluralizer that uses the Humanizer library. This is the same library Visual Studio uses to recommend variable names.

**Comment by hikalkan** [comment]
This is done. You can see the migration guide: https://github.com/abpframework/abp/blob/dev/docs/en/Migration-Guides/Abp-4_0.md#auto-api-controller-route-changes

I added an option for who want to continue with the version 3.x approach since this breaking change may effect their client applications.

OLD STYLE:

![image](https://user-images.githubusercontent.com/1210527/97086966-4b727b80-162f-11eb-9be3-d486f473164f.png)

NEW STYLE:

![image](https://user-images.githubusercontent.com/1210527/97086962-47465e00-162f-11eb-9c6e-5a987c873b7e.png)

I didn't implement pluralization. If anyone wants plural names, they can make the Application service name plural, for example `ReadingBooksAppService` results the following API:

![image](https://user-images.githubusercontent.com/1210527/97086995-74930c00-162f-11eb-937e-204624339cdb.png)

**Comment by feafarot** [comment]
Is there a way to do that for default services that are defined inside Abp?
@PMExtra

**Comment by PMExtra** [comment]
@feafarot Sorry for late reply. I think it's impossible. The predefined modules (what you call them default services that defined inside Abp) have their own controllers instead of `ConventionalControllers` (well known as dynamic controller). They have specified route for each action. (ref #5866)
You can remap the route for each action just like what you did in ASP.NET Core.
