### ISSUE TITLE
Blazor: Entity Actions component

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5560]
We add actions to the DataGrid almost in all pages. It causes repeating code. We can create a component that we can simply add the actions column.

![image](https://user-images.githubusercontent.com/1210527/93848599-c227fc00-fcb2-11ea-82e1-130e2c99b790.png)

Features;

* Allows to set a policy (permission) for each action and hide the action if no permission
* If none of the action policies was granted, the column should be completely invisible
* If only one action available (including non-authorized actions) then show a button, instead of dropdown.
* Allow to set an action as "primary". In this case, the dropdown becomes a split button:
![image](https://user-images.githubusercontent.com/1210527/93848822-5b571280-fcb3-11ea-98be-5bbfc15a0ce3.png)

Note that: We should allow to reuse the same dropdown everywhere, independent from the data grid as well as inside a data grid.

**Comment by sebitsi** [comment]
@hikalkan Good suggestion.

I have another two on top of yours:

- actions are often linked with some validation function that enable/disable it. 
  For example:
  If we have two actions "Set as read", "Set as unread" and item(row) with "IsReaded" field with value set to true then first 
         action is disabled and second is enabled. And vice versa.
  So, if we can inject some function into action that return true/false or better can set action's properties it will be very handfull.

- if you create indepentent action component, please split it on ActionComponent and ActionService. It will be very usefull, because in that case we can use action service with more that one component. We can bind it to button collections for example.

   So, with other words: action service can be service as single point of truth for actions in it's collection of actions.
   Action component is only for visual presentation.

Regards
