### ISSUE TITLE
SQLite Error 6: 'database table is locked'

### ISSUE THREAD

**Issue by DanzigGLT** [abpframework/abp#5661]
I created a project using abp-cli, removed sql-server as explained in the docs and replaced it with sqlite. After deleting SQL-Server migrations, creating SQLite migrations and executing Update-Database I started the IdentityServer (own database with simple connection-string: "Data Source=identityserver.db" and a the app itself ("Data Source=myapp.db").

The process of login throws exception: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database table is locked'.

attached you find a part of the my log.txt with the stacktrace of the exception:
[stacktrace.txt](https://github.com/abpframework/abp/files/5310170/stacktrace.txt)

**Comment by mdocter** [comment]
I encountered almost the same error this evening. I added SQLite and could register a new user. Enter a first and last name in the profile. Save / update the profile, Logout. Try to login again. Time-out occurred and SqliteException: SQLite Error 5: 'database is locked'.

My connection-string is:    `"Data Source=K:\\data\\my.db;"`

Do I need to add something extra here? I tried to add `Journal mode=WAL`, but then a  keyword `journal mode` is not supported error occurs. So that didn't help.

**Comment by maliming** [comment]
hi

Try completely disable the database transactions for sqlite.

```cs
Configure<AbpUnitOfWorkDefaultOptions>(options =>
{
    options.TransactionBehavior = UnitOfWorkTransactionBehavior.Disabled;
});
```

**Comment by mdocter** [comment]
Thanks @maliming! Disabling the database transactions seems to work for me. I added them in the `MyAppEntityFrameworkCoreModule` `ConfigureServices` method. Is that the correct and only location? Because the documentation (see: https://docs.abp.io/en/abp/latest/Unit-Of-Work#default-options) refers to my own module:

> Configure the options in the ConfigureServices method of your module.

**Comment by maliming** [comment]
Add them to ef core module is no problem. the web module is ok too.

**Comment by muratcanoguzhan** [comment]
Why I can't use transactions? There should be another solution.

**Comment by scottiemc7** [comment]
@muratcanoguzhan I had success by disabling the security log

```
Configure<AbpSecurityLogOptions>(x =>
{
    x.IsEnabled = false;
});
```
