### ISSUE TITLE
Add the FirstOrDefaultAsync and FirstOrDefault method to the IReadOnlyBasicRepository interface

### ISSUE THREAD

**Issue by Nokecy** [abpframework/abp#573]

**Comment by hikalkan** [comment]
Find (by id) method already does it. Returns null if not found.
If you are looking for a Find method that get an expression, we didn't add it intentionally because it assumes that underlying DB layer supports expressions. `IReadOnlyBasicRepository` is minimalist interface. Use `IReadOnlyRepository` instead to get all power of LINQ since it supports `IQueryable`.
