### ISSUE TITLE
Document how to run the blogging module

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#588]

**Comment by wakuflair** [comment]
+1

**Comment by vnetonline** [comment]
I have the http://www.abpCentral.com website up and running with abp vnext version 0.17.0.0 where I hope to dog food the app.io. I am have started to create video tutorials for abp framework and hope to release the following video tutorials.

“How to setup development environment up and running”
“How to generate the the Project template”
“How to add the docs module to your Project”
“How to add the blogging module to your Project”

I am having trouble getting the blogging module working because it does seem Have a method ‘builder.ConfigureBlogging();’ Which I need to add to my OnModelCreating in my ProjectNameDbContect.cs in the EntityFrameworkCore project so it can create the tables etc.

Can someone please explain how it is done so I can complete the video tutorial

**Comment by hikalkan** [comment]
Hi,

Skip these for now:

“How to add the docs module to your Project”
“How to add the blogging module to your Project”

Because I've added `add-module` feature to CLI which will simplify this very much. Planned to release it in the next week.

**Comment by hikalkan** [comment]
Canceling this since CMS Kit already has a blogging feature and we no longer work on the blogging module.
