### ISSUE TITLE
Distributed Event Bus RabbitMQ integration

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#593]

**Comment by natiki** [comment]
@hikalkan What is the rationale in terms of integrating message busses? Will there be integrations for other ones aside from RabbitMQ? Does that mean heaps of modules implementing IDistributedEventBus? I thought the plan was to use something like https://github.com/rebus-org/Rebus which ultimately supports many busses out of the box?

**Comment by hikalkan** [comment]
We are already considering Rebus integration (https://github.com/abpframework/abp/issues/376). RabbitMQ integration will be a simple integration for test the distributed event system. We may then drop it or maintain in parallel with the Rebus integration. My first impression on Rebus was not clear in some points. I will re-investigate it.

**Comment by natiki** [comment]
Hi @hikalkan, 

> My first impression on Rebus was not clear in some points. 
Yes mine as well.

I would like to add support for https://nats.io/ (first the [streaming](https://nats.io/download/nats-io/nats-streaming-server/) version as it has guaranteed delivery and then later the [vanilla](https://nats.io/download/nats-io/gnatsd/) version) for both this project and Rebus. So just wondering if you want me to implement it for IDistributedEventBus or not? I would be happy to maintain it.

Also I assume somewhere there will be a pluggable serialization aspect as well? Ultimately for performance, on wire efficiency and robustness (automatic data versioning) I prefer to use [Google's Protocol Buffers](https://developers.google.com/protocol-buffers/) using Marc Gravell's https://github.com/mgravell/protobuf-net rather than JSon. But ultimately if this was pluggable then everyone could use their "favourite" serialization. So if you have an interface or part of the framework defined I would be happy to add Protocol Buffers at the same time. Just let me know.

**Comment by hikalkan** [comment]
> So just wondering if you want me to implement it for IDistributedEventBus or not? I would be happy to maintain it

It would be good, but a bit early now since I should complete the interface and some other parts and test it. Then you can contribute and it's very appreciated :)

> Also I assume somewhere there will be a pluggable serialization aspect as well

Yes, the serialization will be a replaceable service (like https://github.com/abpframework/abp/blob/master/framework/src/Volo.Abp.RabbitMQ/Volo/Abp/RabbitMQ/IRabbitMqSerializer.cs)

**Comment by natiki** [comment]
@hikalkan nudge me when u r ready for a PR in whatever form.

**Comment by natiki** [comment]
@hikalkan where to as this one is being closed?

**Comment by natiki** [comment]
So I can start coding against the interfaces if I wanted to start implementing https://github.com/abpframework/abp/issues/593#issuecomment-441828289

**Comment by hikalkan** [comment]
Yes, IDistributedEventBus interface is good to start.

**Comment by yadurajshakti** [comment]
Dear @hikalkan **Do we have Amazon MQ integration support as well?**

I am very new to this framework and have to decide between Rabbit MQ or Amazon MQ. Any help would be greatly appreciated. :)

**Comment by sreekanthedayar** [comment]
> Hi [@hikalkan](https://github.com/hikalkan),
> 
> > My first impression on Rebus was not clear in some points.
> 
> Yes mine as well.
> 
> I would like to add support for https://nats.io/ (first the [streaming](https://nats.io/download/nats-io/nats-streaming-server/) version as it has guaranteed delivery and then later the [vanilla](https://nats.io/download/nats-io/gnatsd/) version) for both this project and Rebus. So just wondering if you want me to implement it for IDistributedEventBus or not? I would be happy to maintain it.
> 
> Also I assume somewhere there will be a pluggable serialization aspect as well? Ultimately for performance, on wire efficiency and robustness (automatic data versioning) I prefer to use [Google's Protocol Buffers](https://developers.google.com/protocol-buffers/) using Marc Gravell's https://github.com/mgravell/protobuf-net rather than JSon. But ultimately if this was pluggable then everyone could use their "favourite" serialization. So if you have an interface or part of the framework defined I would be happy to add Protocol Buffers at the same time. Just let me know.

We are using nats with ABP, as all our stack uses it. We open sourced the package and is available in nuget.
