### ISSUE TITLE
Please enable discussions on this Repo

### ISSUE THREAD

**Issue by TonyValenti** [abpframework/abp#5935]
This can be done under the repository settings.

**Comment by TonyValenti** [comment]
Can someone please make this happen on this repo?

**Comment by hikalkan** [comment]
Currently GitHub issues & Stackoverflow [abp tag](https://stackoverflow.com/questions/tagged/abp) seems enough for support.
However, we will consider this if this adds a value.

**Comment by martenw** [comment]
> Currently GitHub issues & Stackoverflow [abp tag](https://stackoverflow.com/questions/tagged/abp) seems enough for support.
> However, we will consider this if this adds a value.

Perhaps discussions here would be good? It seems questions posted in Stackoverflow are missed? I came here planning to post an issue since the question I added in SO has no answers. Looking at the [abp-tag in SO](https://stackoverflow.com/questions/tagged/abp) it seems to be the case for several questions.

I have just started using the platform and without a place to ask questions it is easy to get stuck even though the documentation in most cases is really good.

**Comment by hikalkan** [comment]
I created the discussions: https://github.com/abpframework/abp/discussions

We have a very active community. I get ~50 emails in every day from GitHub issues/PRs 😃 
Fortunately, we have a big core team working on this project and managing all these. Also, community helping us to answer to the issues.

We are actively checking [the stackoverflow tag](https://stackoverflow.com/questions/tagged/abp) and also [support.abp.io](https://support.abp.io/) for commercial customers. Now, we have another channel to support. We will see how the community will use it and how can we be in the discussions.
