### ISSUE TITLE
DataGrid no longer scrolls after Popup (Blazorise Modal) closes

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#5940]
This has some history [here](https://github.com/stsrki/Blazorise/issues/296)

In the actual Blazorise repo the issue is closed but I see the issue is a problem here inside the Abp v3.3.0-rc.2

There may be a case to check if Abp referencing an up to date version of Blazorise?

**Comment by 274188A** [comment]
Looking at the latest Blazorise with boostrap here and the problem is not an issue outside of the world of ABP
https://bootstrapdemo.blazorise.com/tests/datagrid (set the option to pop-up modal) which leads me suspect something in ABP is breaking this again (despite being fixed in Blazorise repo)

**Comment by tonjurah** [comment]
I am having this happen with non-ABP Blazorise.

**Comment by maliming** [comment]
@stsrki What do you think?

**Comment by stsrki** [comment]
@maliming I know the problem already. The issue is in how the backdrop is placed. Instead of it being placed inside of modal `div`, it should be placed outside of it. To make it work I will need to refactor Modal slightly, but keeping it without breaking changes.

It's scheduled for 0.9.3 final release but I can make it work for the next preview.
