### ISSUE TITLE
Abp 3.3.0 does not generate auto API controller for ApplicationService inheriting from other ApplicationService

### ISSUE THREAD

**Issue by desmored** [abpframework/abp#5964]
ABP Framework version 3.3.0

Hi i migrated a project from version 3.2.1 to version 3.3.0, and i noticed that an ApplicationService was not exposed as api in swagger definition. With version 3.2.1 it was there and i used it in my angular app with no problem.

This ApplicationService inherits from IdentityUserAppService:

````csharp
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(CustomIdentityAppService), typeof(IIdentityUserAppService), typeof(IdentityUserAppService))]
    public class CustomIdentityAppService : IdentityUserAppService
````

So i tried to create two simply application services A and B in same project, B inherits from A: in swagger i can see only A.

Can be a problem in version 3.3.0?

Thanks

**Comment by hikalkan** [comment]
Hi @desmored 

Thank you for reporting this in a short time. I must say that this is by design. I've done this intentionally with [this commit](https://github.com/abpframework/abp/commit/71b1384598128b7432491422f1b64837c7fb97af#diff-7432d3f3b7633b52d87af78008085b7b9562fe0d5c61a873693ef6e3a6fc3259R88).

Inheriting a controller/appservice without replacing/overriding it is not a good idea and it was causing problems because AspNet Core adds both classes to the controller models and this causes conflicts with the routes. So;

* Don't inherit a app service from another app service, unless the base service is `abstract`.
* The only reason to derive from a non-abstract service can be to override the methods. This is typically needed when you want to override a method of a service/controller defined in a module package. In this case, don't add new methods, just override the existing methods since the new class is not added to the application model, but just replaces the runtime service. If you want to add a new method, just do it with a new, independent service/controller. You can use the same route prefix, so the clients may not understand the difference.

You can remove the `typeof(CustomIdentityAppService)` from the `ExposeServices` list since it has no effect in practical.

I am sorry if that breaks your application. However I had to do it since it was not working as expected otherwise.

Edit: You can replace the `IAbpServiceConvention` implementation with your own class and override the `RemoveDuplicateControllers` to bypass this logic. However, I definitely don't suggest such a usage.

**Comment by gdlcf88** [comment]
Wow, it seems an important change, maybe this line in [the doc](https://github.com/abpframework/abp/blob/rel-3.3/docs/en/Customizing-Application-Modules-Overriding-Services.md#example-overriding-an-application-service) could be removed:
> //[RemoteService(IsEnabled = false)] // If you use dynamic controller feature you can disable remote service. Prevent creating duplicate controller for the application service.

@maliming What do you think?

And here is a little tip: when using the ABP's Auto API Controller, after we create an extension app service, we can [configure the conventional controller](https://docs.abp.io/en/abp/latest/API/Auto-API-Controllers#route) to route it as expected.

**Comment by maliming** [comment]
@gdlcf88 Yes. I'm going to update the document.
