### ISSUE TITLE
How to get entity in Web Project.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#611]
![image](https://user-images.githubusercontent.com/6908465/49058172-d11bff80-f23d-11e8-91c0-4ed45f73e830.png)

If we define the dependencies between modules as shown above,
How to use entities in web projects (because web projects don't depend on domains)
Such as `private readonly SignInManager<MyEntity> _signInManager; `
https://github.com/abpframework/abp/blob/b05751d2d0d45273a66baf7f48be8428ee636dd4/modules/account/src/Volo.Abp.Account.Web/Areas/Account/Controllers/LogoutController.cs#L7-L20

**Comment by SlowLogicBoy** [comment]
Domain has Entities that are most of the time 1:1 to database tables.
Application layer (Application.Contracts) holds DTO Objects that are mapped from Entities in Domain Layer.
In HttpApi/Client/Web you have to use those DTO objects.
Example:
```
Domain
    MyEntity
Application.Contracts
    MyEntityDTO
Application
   Map MyEntity -> MyEntityDTO.
   Method inputs and outputs must be DTO objects
Web
   Use MyEntityDTO
```
[Best practices](https://abp.io/documents/abp/latest/Best-Practices/Module-Architecture)

**Comment by hikalkan** [comment]
@maliming we should not use entities in the web layer. Otherwise, we can't deploy we layer and application layer into separated servers. Web layer uses the application layer via app service interfaces and DTOs.

Account module is an exception. We haven't find a way of separating it because Microsoft's implementation forces to use UserManager, RoleManager and entities inside the web layer. We will work on that later if we can a way of it.

**Comment by maliming** [comment]
@SlowLogicBoy 

thank you for your reply. 

I read the documentation and just got confused. 
As you can see, the above web project `SignInManager<IdentityUser>` uses the `IdentityUser` entity.

**Comment by maliming** [comment]
thanks @hikalkan

**Comment by hikalkan** [comment]
You're welcome :)
