### ISSUE TITLE
Moving Connection String to UserSecrets  in .DbMigrator Project

### ISSUE THREAD

**Issue by kishoresahas** [abpframework/abp#6331]
### Documentation
https://docs.abp.io/en/abp/latest/Connection-Strings#configure-the-connection-strings

> ABP uses the IConfiguration service to get the application configuration. While the simplest way to write configuration into the appsettings.json file, it is not limited to this file. You can use environment variables, user secrets, Azure Key Vault... etc. See the configuration document for more.

### Issues

When I try to move the `.DbMigrator` Connection String from `appsettings.json` to [`UserSecrets`](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-5.0&tabs=linux). I am getting the below error.

`ArgumentNullException:` Value cannot be null. (Parameter 'connectionString')`

PS: At the same time `.HttpApi.Host` works perfectly without any other changes.

**Comment by abhishekbhalani** [comment]
@kishoresahas share your connection string.
provide more details to figured out the issue..

**Comment by kishoresahas** [comment]
> @kishoresahas share your connection string.
> provide more details to figured out the issue..
`
  "ConnectionStrings": {
    "Default": "Server=(localdb)\\MSSQLLocalDB;Database=SampleDB;Trusted_Connection=True"
  },
`

**Comment by maliming** [comment]
@kishoresahas 

I will not merge these codes, but you can refer to it.

https://github.com/abpframework/abp/commit/64d2ce32686ee36d4d6457c98ed06e85ed6223f6

**Comment by RicardoLans** [comment]
@maliming I know this is an old and closed Issue, but I found a cleaner solution which I would like to share. It wont require additional dependency injection and could be a useful addition. 
We (personal feeling) don't like the idea of having a secrets file in repo (or at repo file location) that we should set with gitignore in order to have developers give the possibility to use their personal settings. Since ABP chose to use [Host configuration](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-8.0#host) instead of [Application configuration](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-8.0) 

DbMigrator project:
Add a usersecret on the DbMigrator.csproj

Program.cs:
In the CreateHostBuilder method after the `AddAppSettingsSecretsJson` ABP extension that is called insert  `.ConfigureAppConfiguration(builder => builder.AddUserSecrets<DbMigratorHostedService>())`

The CreateHostbuilder method will look like below
```csharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
        .AddAppSettingsSecretsJson()
        .ConfigureAppConfiguration(builder => builder.AddUserSecrets<DbMigratorHostedService>())
        .ConfigureLogging((context, logging) => logging.ClearProviders())
        .ConfigureServices((hostContext, services) =>
        {
            services.AddHostedService<DbMigratorHostedService>();
        });
```

With this change you are able to still use appsettings.secrets.json, but whenever developers (like ourselves) choose to use UserSecrets then the values in the secrets.json will override the values set in appsettings.secrets.json. So the hierarchy would be:

appsettings.json
appsettings.Development.json -> if applicable
appsettings.secrets.json
secrets.json
