### ISSUE TITLE
Disabled property on BlazoriseUI.Components.EntityAction

### ISSUE THREAD

**Issue by Stirda** [abpframework/abp#6461]
Could `EntityAction` have a `Disabled` property acting like the one on `Button` component? I'd want some of them to be disabled based on a binded property.

This is not completely what I am looking for, but I tried to use `IsVisible` instead. But even `IsVisible` is internal. I cannot find a way to write my own `EntityAction` because I cannot inherit from it and use IsVisible because of this. And there is another internal references that block me. 

Anyway my main wish is a `Disabled` property. I believe this would be helpful to others too.

**Comment by ilkayilknur** [comment]
Good suggestion, @Stirda. I think we can add a public `IsVisible` property to control the visibility of the `EntityAction`. I also saw some workarounds in our templates because of lacking this property. We can also consider adding the `Disabled` property. It would be useful in some scenarios. I will add this to our backlog, and I'll let you know when we release it.  FYI @hikalkan
