### ISSUE TITLE
Blazorise.xxx 0.93-preview2 missing NuGet packages

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#6860]
Where are those packages? There are only v0.9.2.4?
@stsrki, @hikalkan?

**Comment by stsrki** [comment]
@leonkosak They are on [MyGet](https://www.myget.org/gallery/blazorise). Since Blazorise and ABP Blazor are actively in work and previews are released faster, this was the best option. Otherwise, new features in Blazorise would take too long until the new version is released.

Once all the major features are stabilized we will use only the official Blazorise packages.

**Comment by leonkosak** [comment]
Thank you.
