### ISSUE TITLE
Exception details in ABP framework

### ISSUE THREAD

**Issue by slm-w** [abpframework/abp#6879]
I wanna return the details of exception for users,for example a user can't delete a given parent row if a child row exists,i changed the parameter in database cascade to restrict but i get a a pop up without the type of  exception how can i generate the details of exceptions for users.
Thank You

**Comment by cristiandmonda** [comment]
You can create a custom exception, there's an example in the [tutorial](https://docs.abp.io/en/abp/latest/Tutorials/Part-6?UI=MVC&DB=EF) and more information in the exception handling section of the [documentation](https://docs.abp.io/en/abp/latest/Exception-Handling)

**Comment by slm-w** [comment]
@cristiandmonda  thanks for your feedback,i have already used abp exception, I use this function to generate exception message if the user want delete a foreign key already in use but it doesn't work,i got just a error message without details
        [Authorize(SocietePermissions.Villes.Delete)]
        public async Task DeleteAsync(Guid id)
        {
          try
            {
                await _villeRepository.DeleteAsync(id);
            }
            catch (DbUpdateException)
            {

                throw
                      new UserFriendlyException(
                        "Item Cannot be deleted"

              );
            } ;


![image](https://user-images.githubusercontent.com/75528090/103322824-24c22e00-4a40-11eb-9252-0efb785768b4.png)

**Comment by slm-w** [comment]
@maliming

**Comment by berkansasmaz** [comment]
Maybe, as an alternative, you can query the entities it is connected to with a foreign key, and if there is, you can throw an error without running the delete operation. The downside of this is making requests to multiple databases, but when you actually get a save error, your users won't see the message "Item Cannot be deleted". Because DbUpdateException is thrown when saving of changes fail.

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/Exception-Handling#send-exception-details-to-the-client

**Comment by lanpin** [comment]
@realLiangshiwei This problem still exists.

**Comment by realLiangshiwei** [comment]
@lanpin 
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by lanpin** [comment]
@realLiangshiwei 
run microservice-pro
add this code to ProductAppService.cs
<img width="632" src="https://user-images.githubusercontent.com/8994721/110420894-5528e700-80d7-11eb-8bd2-f66d5b0d34d4.png">
and you see:
<img width="436" src="https://user-images.githubusercontent.com/8994721/110420955-7ab5f080-80d7-11eb-8523-a4b70063759c.png">
