### ISSUE TITLE
Clone/ Copy tenant to a new tenant

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#6937]
How can i create a new tenant by copying an existing one ? It would help copy all the data from an existing tenant to do some tests .

**Comment by davidzwa** [comment]
Hi,

Copy in what way? Just the instance itself or all the dependants?

In case of the 1st: just use ITenantManager.
In case of the 2nd: use ITenantManager, IdentityUserManager etc and script it! Otherwise you could also clone the database itself and start with a different connection string... sounds easier than scripting and is exactly suitable for testing.

There's no easier way than the latter in my belief. Good luck!

**Comment by dicksonkimeu** [comment]
A common feature in multi tenant is to clone a tenant (with all it's data) in a new tenant (in the same database)

**Comment by real-zony** [comment]
If you are copying data from an existing tenant, you need to do this manually.

**Comment by davidzwa** [comment]
@dicksonkimeu I'm eager to look at any examples to what you mean, as I'm a bit hesitant to believe your statement at first sight. This I mean in the interest of us learning something, of course!

**Comment by MattPil29** [comment]
Hi, I see this is dormant but think its an important question.  We also have a need to duplicate tenants (including all data).  We are using one database per tenant so the suggestion to clone the database and update the connection string seems sensible.  

However on inspection each of our databases have tables that contain a tenantID discriminator column. Must this be changed everywhere to a new GUID?  If so the only approach to use SQL updates?  

Finally, and importantly, is the tenantid really needed when doing one database per tenant?  if not how would be default to null or remove altogether?

Thanks in advance (and for the great platform), Matt

PS for bonus points has any work been done to allow a user to login once and only be displayed tenants they have access too (defined by permissions inside the tenant)....
