### ISSUE TITLE
How to seed AppUser

### ISSUE THREAD

**Issue by rygar08** [abpframework/abp#6938]
### How to seed AppUser

I'm trying to seed and AppUser with Entity framework database.  I know how to seed a IdentityUser using IdentityUserManager but can not find any documentation of how to seed an entity that extends abpUser like appUser.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Domain/Users/AppUser.cs#L10-L13

* You can define your custom properties into this class.
* You never create or delete this entity, because it is Identity module's job.
* You can query users from database with this entity.
* You can update values of your custom properties.

**Comment by rygar08** [comment]
So should I create a user using IdentityUserManager then create a new AppUser and set it's ID to the same ID as the new user. How is the One 2 one relationship created from the UserIdentity (abpUser) and the AppUser ?

**Comment by maliming** [comment]
> This **AppUser**  entity shares the same table/collection with the **IdentityUser** entity of the Identity module.

**You can update values of your custom properties.**

**Comment by rygar08** [comment]
So how do you seed a new AppUser?
