### ISSUE TITLE
MVC UI: Implement page toolbar extensions for open source modules

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6949]
https://docs.abp.io/en/abp/4.1/UI/Angular/Page-Toolbar-Extensions

- [ ] Framework infrastructure (we probably need to do it in the basic theme)
- [ ] Identity module
- [ ] Tenant management module

This system was already implemented for ABP Commercial modules.

**Comment by enisn** [comment]
Layout already has `content_toolbar` placeholder. 

https://github.com/abpframework/abp/blob/0d4ab74b61cdb5d8d3192278952c791e5799f0ee/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic/Themes/Basic/Layouts/Application.cshtml#L61

If **AbpPageToolbarViewComponent** component is moved into `content_toolbar`, toolbaritems are rendered out of card-view and will have different view with given document ( [Page-Toolbar-Extensions](https://docs.abp.io/en/abp/4.1/UI/Angular/Page-Toolbar-Extensions) )

It should be rendered like this:
![image](https://user-images.githubusercontent.com/23705418/105861328-a6858700-5fff-11eb-94c2-7e874d6f6180.png)

But it's rendered as:
![image](https://user-images.githubusercontent.com/23705418/105861244-8fdf3000-5fff-11eb-8644-739ca18baead.png)

---

So, without changing anything, following line looks working fine currently:
https://github.com/abpframework/abp/blob/0d4ab74b61cdb5d8d3192278952c791e5799f0ee/modules/identity/src/Volo.Abp.Identity.Web/Pages/Identity/Roles/Index.cshtml#L37


Also same with tenant-management module
This line renders fine instead of `content-toolbar`
https://github.com/abpframework/abp/blob/0d4ab74b61cdb5d8d3192278952c791e5799f0ee/modules/tenant-management/src/Volo.Abp.TenantManagement.Web/Pages/TenantManagement/Tenants/Index.cshtml#L34

@hikalkan , should still we move **AbpPageToolbarViewComponent** to `content_toolbar` in layout from card-title?
