### ISSUE TITLE
Cli , Generate Date Properties into String Properties #abp-cli #angular #generate-proxy

### ISSUE THREAD

**Issue by IslamEldeeb** [abpframework/abp#6979]
### My User Interface : Angular ver.10

I have a problem with cli generate proxies , when generate the **DateTime** data type property , the file generated with **String** data type , example 
**Backend :**
Public Class ClientDto{
        public DateTime Birthdate { get; set; }
}

**FrontEnd  (Angular) :**
export interface ClientDto extends EntityDto<number> {
  birthdate?: string;
}

I need help ASAP ..

**Comment by armanozak** [comment]
Hi,

Dates are represented as string in JSON. The response to any request will have date properties as string. Likewise, any request body will have them as string. Therefore, `DateTime` properties are converted to `string` in generated proxies.

Please let me know if this answers your question.

**Comment by IslamEldeeb** [comment]
Hi,
Thanks for your support , but i want to know why datatime converted to string in generated proxies

**Comment by armanozak** [comment]
Hi,

Because, the requests and responses will have `string` type, not `Date`.

**Comment by IslamEldeeb** [comment]
Hi , 
But The nswag generate the correct datatype and handle this operation in runtime , so we need to enhancement this point in abp cli .
Thanks ..

**Comment by armanozak** [comment]
Hi,

ABP does not use NSwag and it is debatable which one is correct. Generated models have dates as string because of the reasons explained above. In our Angular UI app, datepickers handle dates as you can see here: https://docs.abp.io/en/abp/latest/Tutorials/Part-3?UI=NG&DB=EF#datepicker

We are not planning to change this in near future.

**Comment by snowchenlei** [comment]
> Hi,
> 
> ABP does not use NSwag and it is debatable which one is correct. Generated models have dates as string because of the reasons explained above. In our Angular UI app, datepickers handle dates as you can see here: https://docs.abp.io/en/abp/latest/Tutorials/Part-3?UI=NG&DB=EF#datepicker
> 
> We are not planning to change this in near future.

Hi,
cli Generated htttp request hot convert DateToString?
i get error `'2021-10-07T10:34:03.000Z' can't parse to DateTime(yyyy-MM-dd HH:mm:ss)!`
![image](https://user-images.githubusercontent.com/26211283/138010502-84572a25-1339-41e5-b399-e684c08ddea3.png)

![image](https://user-images.githubusercontent.com/26211283/138010486-93d5ac06-74c4-43fc-98f0-bf77defed48a.png)

**Comment by lgadola** [comment]
Hi @armanozak 
I think @IslamEldeeb has a very valid point here.
In my opinion, too, the Typescript interface should represent dates as datatype DateTime and the conversion should be done in generate-proxy or the mapping json->DTO.
In NSwag, when generating the js-interface, you can even choose your preferred datetime handler, (p.e. moment.js).
As it stands now, the client has to convert EVERY date in every DTO manually before feeding it into ReactiveForms, Devextreme or other client-side controls.
I agree with your opinion that the json should contain a string representation of a UTC date, but that does not seem to be related to the issue here. The issue being that on the client side these date strings are quite useless and it would be relatively easy to map them to the correct data type when converting the json to the dto interface.
But very hard if we have to do it client-side for all the DTOs.
That for me currently is a huge show-stopper in using abp of which I am generally very fond.

**Comment by antonGritsenko** [comment]
@armanozak may be it will sounds a bit offensive, but you even can't image show much pain this cause in the projects. Right now we need to replace ALL strings with Date type. Very stupid decision to generate string instead Date, really, there are no any valid reason to do so. 

Please re-opne this issue.
