### ISSUE TITLE
Autofac not work

### ISSUE THREAD

**Issue by loning** [abpframework/abp#715]
BuildServiceProviderFromFactory will build from IServiceProviderFactory<IServiceCollection>, and I found 

`            services.AddTransient<IServiceProviderFactory<IServiceCollection>, DefaultServiceProviderFactory>();
`
in 
https://github.com/aspnet/AspNetCore/blob/5665d78ffe6c2e414c42548facfe3e6375192f4e/src/Hosting/Hosting/src/WebHostBuilder.cs

**Comment by loning** [comment]
now I just temp use services.BuildAutofacServiceProvider()

**Comment by hikalkan** [comment]
You should build the web host manually like that:

https://github.com/abpframework/abp/blob/8f7a05616321231b7de4f51356ea1f914cb2e193/templates/mvc/src/MyCompanyName.MyProjectName.Web/Program.cs#L37-L44

Otherwise, it overwrites the autofac and uses the default. We should document that here: https://abp.io/documents/abp/latest/Getting-Started-AspNetCore-Application

**Comment by loning** [comment]
how about replace IServiceProviderFactory<IServiceCollection> ?

**Comment by hikalkan** [comment]
Doing it, but in different way (https://github.com/abpframework/abp/blob/master/framework/src/Volo.Abp.Autofac/Volo/Abp/AbpAutofacAbpApplicationCreationOptionsExtensions.cs#L13). I will check this. Thanks.

**Comment by hikalkan** [comment]
I could not find a way of using Autofac when we use the `WebHost.CreateDefaultBuilder()` method.
Closed this issue and created a new one: https://github.com/abpframework/abp/issues/821

**Comment by hikalkan** [comment]
Also, updated the document: https://github.com/abpframework/abp/commit/73ad39ed2db9ff1e60e3f1474b9ee99553acc790
