### ISSUE TITLE
Implement CorrelationId

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#738]
That is passed between service calls to track the same request/operation/transaction. It's also logged.

**Comment by natiki** [comment]
Hi @hikalkan,

I just want to put forward that in all likelihood the microservices will be running in something like https://konghq.com/. The OSS version is very powerful. That is how I run things because it gives me a native K8s solution and does so many things more than correlation ID's https://docs.konghq.com/hub/kong-inc/correlation-id/. Might also then be worth a discussion as to what ABP needs to do in terms of a microservice framework.

I can do request transforms, security, logging etc etc.  So if you could consider that the microservices will actually be written using ABP but not necessarily using the ABP workflow that would be great.

**Comment by natiki** [comment]
@hikalkan Interested in your comments based on my comment https://github.com/abpframework/abp/issues/738#issuecomment-462196096

**Comment by hikalkan** [comment]
Hi @natiki,

ABP has no goal to be a complete microservice framework & solution. It is better to integrate/use existing popular tools and libraries. Our goal is to be compatible to different tools (but will not have direct integrations to all of them). And our main goal is to develop the framework & modules as microservice compatible, and even ms focused. For this purpose, we defined a [module specification](https://abp.io/documents/abp/latest/Best-Practices/Index) and basic framework features.

For instance, if you are using a service mesh or logging system that has a CorrelationId feature, just forget about using ABP's feature, or integrate it by just implementing ICorrelationIdProvider, it is flexible.
