### ISSUE TITLE
MongoDB repository base aggregation API

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#7423]
See this: https://support.abp.io/QA/Questions/829

We can provide the necessary functionality in the mongo repo base and document it for alternative usage approach.

**Comment by michaelsudnik** [comment]
This does mean that the base repository class now supports aggregation, but it would be nice if the automatically generated repositories created by abp suite used the aggregation option rather than queryable (maybe an option to choose). It would mean that navigation properties can be included in a single database call. It would also allow for sorting on navigation properties. It would bring the mongodb repositories to the same functional level as entity Framework. Maybe a new backlog issue could be raised to cover this?

**Comment by hikalkan** [comment]
Thanks for your suggestion. I've created an internal issue to evaluate it for the next milestone. BTW, you can customize the code generation templates for your own applications.
