### ISSUE TITLE
Angular - split NgBootstrap and other big libraries in angular.json

### ISSUE THREAD

**Issue by davidzwa** [abpframework/abp#7473]
* Abp 4.2-rc2
* Angular v11 with respective @abp/ng.core, identity and tenant-management package
* Feature discussion
* Reproduce: use any Angular ABP package which depends on the Angular Theme packages.

**Problem/Challenge**
Our app does not require `ng-bootstrap`, `chart.js` and some other peer-dependencies as we already have our own methods with `Angular Material` with `MomentJS`. Currently both packages and more are installed by peer-dependency as we have the packages `core`, `identity` and `tenant-management`. Can we work towards a solution where we dont automatically have to include the peer-dependencies in our bundle?
Just because we use the awesome services, auto-generated proxies, state management, etc etc does not mean should use bootstrap/chart.js.

Splitting (and thus ignoring) `ng-bootstrap` and `chart.js` in `angular.json` is definitely one option, of course. But I'm hinting at a solution where we keep Abp components and theming optional and separated from services/state/models in a different 'base package'. So something like `@ng/abp-core` for data and `@ng/abp-components` for any component using the visual packages like chart/bootstrap described above.

**Comment by davidzwa** [comment]
Related https://github.com/abpframework/abp/issues/7472

Ok, after thinking a bit I think my question is: 

> How to properly split out such dependencies and other big packages so my application does not have to download it (adjusting NGSW with exclamation marks)?

Think this is a pretty easy question, as it's already done for chart.js and could help others who do not want to use the components based on bootstrap (shaking out the dependency).

**Comment by mehmet-erim** [comment]
Hi @davidzwa

We want to make some optimizations for dependencies. But we can't do this before v5.0 because it will cause breaking changes. 

We may not be able to make any changes for `ng-bootstrap`. Many ABP packages are depended on the bootstrap and this is a design decision. Many ABP Angular UI packages use `ng-bootstrap` components as well. But there is nothing terrible in this situation. Because tree-shaking is working well. Unused modules, components, services, etc. do no increase the final output size. So `ng-bootstrap` modules that are not used anywhere do not increase the bundle size. If you are very meticulous about it, you can develop your own modules (like tenant management) and use them instead of ABP Angular UI modules even though I don't recommend it much.

Your thoughts are important to us. We will consider what we can do about it. Thanks for creating the issue.

**Comment by davidzwa** [comment]
Hey @mehmet-erim,

I thank you for the elaborate answer. And I agree that tree-shaking does its job quite well.

The reason for recreating the components is that we want to avoid integrating `ng-bootstrap` due to Angular Material theming as well as the fact that it would provide 2 styling frameworks which is unoptimal.
The project is older than ABP framework (it was using the original Asp .NET Boilerplate), so it's a classical legacy challenge by now due to the amount of dependencies on Angular Material.

Luckily, the project will go open-source soon, so more people can take a look at how we took up the challenge of integrating Abp in Material from the get-go.
