### ISSUE TITLE
How to customize exchange  when use AbpBackgroundJobsRabbitMqModule  to  configure multiple job?

### ISSUE THREAD

**Issue by fmpfmp** [abpframework/abp#7629]
How to customize exchange  when use AbpBackgroundJobsRabbitMqModule  to  configure multiple job?

**Comment by fmpfmp** [comment]
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.BackgroundJobs.RabbitMQ/Volo/Abp/BackgroundJobs/RabbitMQ/JobQueue.cs

line:160;

how to customize the parameter  "exchange"

**Comment by real-zony** [comment]
Hi @fmpfmp 
As you can see, change exchange is currently not supported, you can implement `IJobQueue<TArgs>` and replace the original implementation. Because RabbitMQ Background must follow `IBackgroundJobManager`, no additional parameters can be passed.

One way to deal with this is that you can define an interface that contains an Exchange property, like this:
```csharp
public interface IRabbitMqJobArgs
{
      string ExchangeName {get; set;}
}
```
Your TArgs needs to inherit this interface. When passing TArgs, read the additional exchange name parameters based on reflection or coercive type conversion, and publish to different exchanges according to the situation.
