### ISSUE TITLE
Get extra properties of AppUser in ICurrentUser

### ISSUE THREAD

**Issue by amLabib** [abpframework/abp#7676]
Hi,
I followed the below Abp documentation and community article, to add extra properties to Identity user entity:
[https://docs.abp.io/en/abp/latest/Module-Entity-Extensions#navigation-properties-foreign-keys](url)
[https://community.abp.io/articles/how-to-add-custom-property-to-the-user-entity-6ggxiddr](url)
is there any implemented way to get current user's extra properties?

**Comment by gterdem** [comment]
Did you check [here](https://docs.abp.io/en/abp/latest/Object-Extensions#some-best-practices)? You can add hard-coded and also get as you declare in an extension method.

**Comment by gterdem** [comment]
Sorry, it seems I misunderstand your question.

 You can not get extra properties over [ICurrentUser](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Security/Volo/Abp/Users/ICurrentUser.cs) since it is an interface and it doesn't implement `IHasExtraProperties`. You will need to make a request to db or userlookup service.

**Comment by amLabib** [comment]
making a request to db with each request will be a headache, In my case we have entity called "branches", and we need to assign user to multiple branches to use these info in getting data from db, making a round trip to db with each request will add complicity.
in Asp Zero we used Session to store these information, I hoped there is simple way to implement same scenario

**Comment by real-zony** [comment]
All the data of `ICurrentUser` is read from the Token, maybe you need to add custom additional information when the Token is issued.
