### ISSUE TITLE
Improvements for Blazor UI module entity extensibility system

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#7729]
* Lookup component should be improved. Currently, it looks like a textbox.

We will work on these after #6647 merge.

**Comment by ilkayilknur** [comment]
In order to test the same functionality on the MVC side,

- Open `MyProjectNameModuleExtensionConfigurator.cs` file in the `MyCompanyName.MyProjectName.Domain.Shared` project.
- Copy the following code into the  `ConfigureExtraProperties` method.
```csharp
ObjectExtensionManager.Instance.Modules()
                .ConfigureIdentity(identity =>
                {
                    identity.ConfigureUser(user =>
                    {
                        user.AddOrUpdateProperty<string>("Role", config =>
                        {
                            config.UI.Lookup.Url = "/api/identity/roles";
                            config.UI.Lookup.DisplayPropertyName = "name";
                        });
                    });

                });
```

- Run the `MyCompanyName.MyProjectName.Web` project.
- Login and navigate to the `IdentityManagement/Users` item in the menu. 
- Click on the `New User` button. You will see the `Role` field in the modal. 
- It's a select2 component. As you see, you can see the initial items and filter the items by typing.

<img width="483" alt="image" src="https://user-images.githubusercontent.com/5785927/113141064-e5b79a80-9231-11eb-90f7-61b255a1a3e4.png">
