### ISSUE TITLE
After set ValidationInterval, when login in with a tenant, after the interval, refresh will logout

### ISSUE THREAD

**Issue by gerryge** [abpframework/abp#7791]
* Your **ABP Framework version**: 
   v4.2.1

* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
  MVC

* Your database provider(EF Core/MongoDB)
  EF Core

* Steps needed to **reproduce** the problem.
  1. abp new Acme.BookStore
  2. add below code in BookStoreWebModule.ConfigureServices
  ```C#
        Configure<SecurityStampValidatorOptions>(options =>
        {
            options.ValidationInterval = TimeSpan.FromSeconds(10);
        });
  ```
  3. Start web and new a tenant
  4. Loging with the tenant
  5. After 10s, refresh the website, it will logout automatedly
 
Screenshots:
![image](https://user-images.githubusercontent.com/6952917/108618384-a50d7a00-7458-11eb-8974-2f1c10998b58.png)
![login](https://user-images.githubusercontent.com/6952917/108618389-ad65b500-7458-11eb-9d79-dd77455acd7f.gif)

**Comment by yang-er** [comment]
This is because `app.UseMultiTenancy()` is after `app.UseAuthentication()`.

The reason isn't the low value of ValidationInterval.

Authentication uses `SecurityStampValidator`, and then it `SignInManager` -> `UserManager.GetUserAsync(ClaimsPrincipal)`.

That function will get no value because `CurrentTenant.Id` is not set yet. However, there's one Claims `tenantid` in the ClaimsPrincipal.

I think `UserManager.GetUserAsync(ClaimsPrincipal)` should be changed that Claims-"tenantid"-value is used first.
