### ISSUE TITLE
ABP CLI: The mongodb option does not need to check the migration file exists

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#7983]
Steps:

   `abp new qa -d mongodb`

![image](https://user-images.githubusercontent.com/16813853/110272355-f8f59280-8004-11eb-9990-d86ae12c8058.png)

**Comment by maliming** [comment]
@yekalkan 
You can consider moving `DbMigrationsProjectExists,MigrationsFolderExists, AddInitialMigration` methods to `EntityFrameworkCoreMyProjectNameDbSchemaMigrator`.

Use reflection to check if the `MyProjectNameMigrationsDbContextModelSnapshot` class of assembly exists. Because when DbMigrator published, there will be no folders and migration files.
