### ISSUE TITLE
Undefined background job for the job name:TP.Youzan.Jobs.Args

### ISSUE THREAD

**Issue by leunghoary** [abpframework/abp#8005]
Hi .

I use backstage tasks to report mistakes:Undefined background job for the job name:TP.Youzan.Jobs.Args.MemberInfoArgs
my code :

```
 public class MemberChangedJob : BackgroundJob<MemberInfoArgs>, ITransientDependency
  {
      //private readonly ISettingProvider _settingProvider;
      private readonly IHttpClientFactory _clientFactory;
      private readonly MsgSubscribeManager _msgSubscribeManager;
      private readonly AppInfo _appInfo;

      public override void Execute(MemberInfoArgs args)
      {

          var entityStr = JsonConvert.SerializeObject(args);

          try
          {
              var url = AsyncHelper.RunSync(async () => { return await _msgSubscribeManager.GetUrlAsync(args.RootKdtId, YouzanUrlType.SCRM_CUSTOMER_EVENT); });
      }
  }
```

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/Background-Jobs

**Comment by leunghoary** [comment]
Thank you. There was an update

**Comment by maliming** [comment]
### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

Please **write in English**.
