### ISSUE TITLE
invalid_grant response when calling refresh token prevents the angular app from opening

### ISSUE THREAD

**Issue by ahmadalmunajjed** [abpframework/abp#8010]
**ABP Framework version** 4.2.2
**User Interface** Angular
**database provider** EF Core
**Exception message** invalid_grant
**Steps needed to reproduce**

- Download new project 
- Reduce AccessTokenLifetime to very short time (for testing to be able to test it quicly, the purpose is enabling refresh token)
- Login to Angular app
- Delete PersistentGrants records from database
- Refresh the angular app page

Then the app can't load anymore until I delete refresh_token key from local storage

When the app is bootstrapping, and the token is invalid, the app tries to call connect/token for refresh token 
So when it returns 400 status code with invalid_grant message (for some reason, the one mentioned above one of them)
It throws an error preventing the app from opening, and it gets stuck on loading page.

PS: What I'm aiming to do is block user API, so I need to prevent the user from refreshing the active access token. Thta's why I'm deleting the PersistentGrants

It would be great if you handle it in the next version

Thanks

**Comment by mehmet-erim** [comment]
Hi @AhmadAlMunajjed 

Can you open the `src/app/environments/environment.ts`, remove the `offline_access` from the value of `environment.oAuthConfig.scope` property and try again?

The problem is probably related to the lack of PersistentGrants records. If you remove the `offline_access` scope, the app will not perform HTTP requests for the refresh token.

**Comment by ahmadalmunajjed** [comment]
Hi @mehmet-erim 

Thanks for your reply, removing the `offline_access` will lead to losing the refreshing token ability, but I need to keep it. 

Yes, the problem is the API doesn't find the PersistentGrant record that's looking for.

Therefore, when refresh token doesn't find the key it returns invalid_grant which is fine. However, it prevents the app from loading, which needs to be handled by 
- removing refresh_token key from local storage
- logout
and we need to let the app open as usual.

Thanks

**Comment by mehmet-erim** [comment]
@AhmadAlMunajjed , I have created a [PR](https://github.com/abpframework/abp/pull/8027). You can check what I have done. Since the refresh token error is not handled, if any error occurs when refreshing the token, the app cannot be initialized. So I handled the `refreshToken()` error and clear the storage keys related to the OAuth when any refresh token error occurs.

**Comment by ahmadalmunajjed** [comment]
@mehmet-erim , Thanks and appreciate your quick response.
