### ISSUE TITLE
Use DI instead of static variables in OnModelCreating of DbContext.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#8088]

**Comment by iyilm4z** [comment]
@maliming When i was working on ticket titled [Extract AbpDbContext global query filtering to an external service](https://github.com/abpframework/abp/issues/2208), i had problems with DI. I do wonder how this ticket will be done. Could you please share your feature repo? I would like to follow it.

**Comment by maliming** [comment]
hi @iyilm4z 

See https://github.com/abpframework/abp/pull/7996

**Comment by maliming** [comment]
I just trying to use DI to configure the `AbpModelBuilderConfigurationOptions`.

https://github.com/abpframework/abp/pull/8092/files#diff-75d85b6d759e64ce06d67e6d36db94a9bf2849f0eda1c72119e970483e0847c7R57-R60

**Comment by iyilm4z** [comment]
@maliming i got it, thanks for your fast reply. I want to give another try on that issue again. Does it effect/block you?

**Comment by maliming** [comment]
I think it won't affect me. : )

**Comment by iyilm4z** [comment]
Hi @maliming, i realized that you cancelled working on [Use DI in OnModelCreating](https://github.com/abpframework/abp/pull/8092/files#diff-75d85b6d759e64ce06d67e6d36db94a9bf2849f0eda1c72119e970483e0847c7R57-R60) improvement. First of all i would like to know why? Because i was hoping to use your solution to fix [this ticket](https://github.com/abpframework/abp/issues/2208) as well. 
Secondly i don't know how many times i said to myself that "this time i'll fixt this ticket!!". Probably i tried **5-7 times** to work on that ticket but each time i failed.. Because i faced with few problems like few failed tests, etc. This time i would like to share my work on the ticket with you because this time i'm so close to fix the ticket. Maybe you can help/guide me to solve it. [Here](https://github.com/iyilm4z/abp/tree/extract-global-query-filtering) is the branch contains my work. This time the problem is failing tests below.

```
Volo.Abp.EntityFrameworkCore.Tests (3 tests) Failed: 3 tests failed
    Volo.Abp.EntityFrameworkCore (3 tests) Failed: 3 tests failed
      DataFiltering (3 tests) Failed: 3 tests failed
        MultiTenant_Filter_Tests (2 tests) Failed: One or more child tests failed: 2 tests failed
          MultiTenant_Filter_Tests.Should_Get_All_People_When_MultiTenant_Filter_Is_Disabled Failed: Shouldly.ShouldAssertException: people.Count
          MultiTenant_Filter_Tests.Should_Get_Person_For_Current_Tenant Failed: Shouldly.ShouldAssertException: people.Count
        SoftDelete_Filter_Tests (1 test) Failed: One or more child tests failed: 1 test failed
          SoftDelete_Filter_Tests.Should_Get_Deleted_Entities_When_Filter_Is_Disabled Failed: Shouldly.ShouldAssertException: people.Any(p => p.IsDeleted)
  Volo.Abp.TestApp (2 tests) Failed: 3 tests failed
    Volo.Abp (2 tests) Failed: 3 tests failed
      EntityFrameworkCore.DataFiltering (2 tests) Failed: 3 tests failed
        MultiTenant_Filter_Tests Failed: One or more child tests failed: 2 tests failed
        SoftDelete_Filter_Tests Failed: One or more child tests failed: 1 test failed
```

The problem with these failing tests is the global queries couldn't be called second time but it must be. Do you know why?

**Comment by maliming** [comment]
I will check the [PR ](https://github.com/abpframework/abp/pull/8092)again.

**Comment by maliming** [comment]
A simple solution: 
`--- public static void ConfigureIdentityServer(this ModelBuilder builder)`
 `+++ public static void ConfigureIdentityServer(this ModelBuilder builder, DbContext dbContext)`
