### ISSUE TITLE
Add AppUser to the MVC startup template

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#809]
Hi.
According to your recommendations, we should not use IdentityUser/IdentityUserRole in our application. Please add basic AppUser infrastructures to application templates. 
Thanks in advance.

**Comment by hikalkan** [comment]
That can be good.

**Comment by hikalkan** [comment]
## What's done?

* I added `AppUser` to the domain project.
* I configured to share the same `AbpUsers` table between the application and the Identity module.
* I also created a new separated DbContext, `MyProjectNameMigrationsDbContext`, to manage db migrations.

## How To Use?

- Just inject `IRepository<AppUser, Guid>` as use as normally you do.
- You can define your custom properties into this class (see the example below).
- You never create or delete this entity, because it is Identity module's job.
- You can query users from database with this entity.
- You can update values of your custom properties. You can not update Identity's properties, they are readonly. See the `AppUser` class, I have written comments.

### Example: Adding a new property to the AppUser

1. Define the property in the `AppUser` class:

````csharp
public virtual int Reputation { get; set; }
````

2. Map the property inside the `MyProjectNameDbContextModelCreatingExtensions.ConfigureCustomUserProperties` method:

````csharp
b.Property<int>(nameof(AppUser.Reputation)).IsRequired().HasDefaultValue(1);
````

3. Add new migration using Package Manager Console:

````
Add-Migration "Added_AppUser_Reputation"
````

This will produce a migration like this:

````csharp
public partial class Added_AppUser_Reputation : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<int>(
            name: "Reputation",
            table: "AbpUsers",
            nullable: false,
            defaultValue: 1);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "Reputation",
            table: "AbpUsers");
    }
}
````

4. Update the database schema:

````
Update-Database
````
