### ISSUE TITLE
[Documentation] - Mapping example against principles

### ISSUE THREAD

**Issue by worthy7** [abpframework/abp#8091]
https://docs.abp.io/en/abp/latest/Object-To-Object-Mapping

This is suggesting to sometimes use mapping for the InputDto, but in the best practices it says to avoid doing this. I think maybe use output as an example instead?

https://docs.abp.io/en/abp/latest/Domain-Driven-Design-Implementation-Guide#object-to-object-mapping
"Do not use auto object mapping for input DTO to Entity mappings."

**Comment by NecatiMeral** [comment]
I honestly think "it depends". The following represents my personal opinion, it has nothing to do with ABPs Guidelines nor best practices.

I like to use the mapper not to create the entity, but map properties from a dto to the initialized (Created or Get'ed) Entity. This requires proper mapping, since you don't want to map the ID (for example). When using Aggregate Roots, you shouldn't use the mapper. The Aggregate Root should be responsible of it's values (by using a proper constructor or methods).
When coding the opposite way (Entity to DTO), i like to just map the entity, if possible. Here aren't any constraints afaik you should take care of.

**Comment by worthy7** [comment]
I understand there is a small case when you have already constructed the object that you think using Automapper to just fill in the many many other properties, but it's a bit of a niche case.
