### ISSUE TITLE
Configure kubernetes for microservice demo

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#811]

**Comment by brunobertechini** [comment]
@hikalkan how do you plan to configure kubernetes? Do you plan to create a helm chart for the MicroServices Demo? 

Or any other approach using only yml ?

I think a helm chart will be the best scenario.

Let me know if you need any help here.

**Comment by natiki** [comment]
Helm would be ideal, but having the ability to do it with yml so that portions can be spun up would also be good.

**Comment by hikalkan** [comment]
To be honest, I don't know Kubernates. @atakanozceviz is working on it. 
@atakanozceviz what do you think about that?

**Comment by atakanozceviz** [comment]
> how do you plan to configure kubernetes? Do you plan to create a helm chart for the MicroServices Demo?

@brunobertechini as for now only yml. But it would be great if we have both (helm charts and standard yml files). I dont know so much about Helm Charts, any help would be appreciated :relieved:

**Comment by brunobertechini** [comment]
@atakanozceviz I agree that both approach can be usefull. So my recommendation would be split this in two different issues. One to work on pure yml files and another for helm charts.

Helm is basically the package manager for kubernetes where we can "combine" all service configurations for a given deployment.

Is that possible to split the issues and then we can work first on the yaml files, and later on helm charts?

Remembering that since kubertenetes can be configured in thousands ways, most probably both approachs (yml / helm) will be the starting point (working scenario) for developers to enhance/adapt accordingly.

It would be very nice to have:

`helm install -f abp-helm-properties.yml`

and we have working solution (on development machine).

For production, the scenarios for microservices can vary heavily. I think we need to define some preconditions first.

**Comment by atakanozceviz** [comment]
@brunobertechini [Here](https://github.com/abpframework/abp/tree/master/samples/MicroserviceDemo/k8s) I have been working on k8s yml files. I have tried to deploy using k3s and minikube unfortunately couldn't get it work on my local machine (Linux).

**Comment by carlsonsoft** [comment]
I'm new to learning k8s, I ran the script on win10 and service started normally. However, there is a problem with DNS_PROBE_FINISHED_NXDOMAIN when I log in to the auth-server on the website.
What's the reason for this?
Very much looking forward to your answers.
Environment:
![image](https://user-images.githubusercontent.com/17350481/81136076-11cc8c00-8f8d-11ea-8510-a55e30473865.png)
![image](https://user-images.githubusercontent.com/17350481/81136110-2dd02d80-8f8d-11ea-846b-0ebd61228c56.png)

**Comment by atakanozceviz** [comment]
@carlsonsoft please add this line to the end of your [hosts](https://en.wikipedia.org/wiki/Hosts_(file)) file:

```
127.0.0.1	auth-server
```

**Comment by brunobertechini** [comment]
Sorry for the delay, I will have a look soon on the k8s/k3s implementation and try it out. 

Im also keen to check how this can play with the newly releases WSL2 and Docker on windows so we don't need Powershell :)

**Comment by kelvinksau** [comment]
Any update on k8s enabling the micro service demo ?

**Comment by bhagwatkushwaha** [comment]
> 127.0.0.1



> @carlsonsoft please add this line to the end of your [hosts](https://en.wikipedia.org/wiki/Hosts_(file)) file:
> 
> ```
> 127.0.0.1	auth-server
> ```

can you please specify file name here

**Comment by hikalkan** [comment]
already done
