### ISSUE TITLE
A little more examples, preferably the official documentation corresponding to the detailed demo code

### ISSUE THREAD

**Issue by X-Lucifer** [abpframework/abp#8150]
### GitHub Issues

* **ABP Framework version**: 4.2.2
* **User Interface** : ASP.NET Core MVC
* **Database provider**: EF Core

Can you provide more examples, preferably the official document corresponding to the detailed demo code ? I have read the official documents and sample code, but the documentation and examples are incomplete. I do not know how to integrate ABP in the project. Could you please provide more detailed examples and documents?For example, if I use Quartz, I can't find how to add Trigger and Job

**Comment by realLiangshiwei** [comment]
Hi,

It is difficult to provide examples for every detail, but the documentation will contain most of what you need.

> I can't find how to add Trigger and Job

You can't because background jobs are abstract. You can use the Quartz API directly or background worker: https://github.com/abpframework/abp/blob/dev/docs/en/Background-Workers-Quartz.md#create-a-background-worker
