### ISSUE TITLE
Article request: Using Syncfusion Razor components

### ISSUE THREAD

**Issue by EdmundHerbert** [abpframework/abp#8259]
I use Syncfusion controls extensively and they offer a community edition. 
Could someone add example of how to implement example Syncfusion Grid to ABP Entity Framework Razor Page.

**Comment by hikalkan** [comment]
Done with https://community.abp.io/articles/using-syncfusion-components-with-the-abp-framework-5ccvi8kc

**Comment by fileman** [comment]
@hikalkan to use the Syncfusion SfDataManager control, a little change is required, but I don't know if this break something in ABP:
`context.Services.AddHttpClient("abp", sp =>
            {
                sp.BaseAddress = new Uri("/");
            });`
Instead of:
`context.Services.AddTransient(sp => new HttpClient
            {
                BaseAddress = new Uri("/")
            });`
I can submit a PR if it can be changed without other issues
