### ISSUE TITLE
Q: Mixing Blazor and MVC

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#8331]
Based on [this blog article](https://blog.abp.io/abp/ABP-Framework-4.3-RC-Has-Been-Published), I have some questions.

If abp with Blazor **Server-Side** UI option is generated and then parts of application (specific GUI masks) are written completely in MVC - is this the solution for situations when device is on un-stable internet connection?
(As we know - Blazor Server-Side applications "behave" really bad when device have poor and un-stable internet connection).
So, if parts of Blazor Server-Side application, which are accessed from devices with poor internet connection are written in MVC - would user experience be better (or good) or is this approach still not sufficient?

Thank you for explanations.

**Comment by stsrki** [comment]
It all depends on how bad your internet connection could be. As you already know, Blazor SS requires a SignalR connection to be opened all the time. Once it is lost you will obviously need to refresh the page to start the new app state. This is different from MVC where each page request brings the new state.

Now I'm not sure how big of a problem this could be on your side for your specific project. But considering once Blazor SS is running it will use much less bandwidth than the equivalent MVC app. This is because only parts of the UI are refreshed with each UI event. This can help in cases where the connection is slower.

But as I said if your connection has multiple dropdowns then Blazor SS would not be a good choice from a UX perspective.

**Comment by leonkosak** [comment]
Thank you.
