### ISSUE TITLE
Generating proxy for react native ?

### ISSUE THREAD

**Issue by islam-b** [abpframework/abp#8577]
Hello guys,
I am using the ABP react-native template, and I wonder if there any CLI to generate proxy services like in the angular template.
Thank you.

**Comment by davidzwa** [comment]
Just guessing a bit here, because I dont think it exists. Lets speculate.

Consider switching to Typescript based react-native if you can. 
This will open up some possibilities with model generation.
https://reactnative.dev/docs/typescript

I found these great so far, if you like writing a tool in Javascript (f.e. NodeJS, or `ts-node`):
https://www.npmjs.com/package/json-schema-to-typescript
or the more simplistic wrapper (problematic as everything is marked as nullable, so do consider option above)
https://www.npmjs.com/package/json-to-typescript

As axios is used, I think you could consider consuming the ABP api specification document and use that to parse your own models and reconstruct the URLs within that response. That API endpoint is pretty powerful already! Consider taking a look at that response and tell me what you think.
Find it here `...your running host+port.../api/abp/api-definition/`
