### ISSUE TITLE
Documentation: Domain Driven Design example

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#869]
There is BookApp example in Domain Driven Design => Application Layer => Application Services): https://abp.io/documents/abp/latest/Application-Services#bookappservice-implementation

Wouldn't be better to implement Create/Update/.... operations in a **manager** like in EventCloud application example?
https://aspnetboilerplate.com/Pages/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/index.html#eventmanager
https://aspnetboilerplate.com/Pages/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/index.html#eventregistrationpolicy

It's recommended that simple and then advanced example are "together" in the documentation since application based on ABP are enterprise-grade and therefore more advanced and complex most of the time.

**Comment by hikalkan** [comment]
Hi,

In DDD, there is no rule offers that an application service shouldn't create a domain entity. Application services can work with domain objects within given possibilities and restrictions.

In this example, creating a Book does not require and additional business logic that should be forced. I strongly recommend to not introduce complexity when it is not needed (YAGNI).

As an opposite example, [TenantManager](https://github.com/abpframework/abp/blob/master/modules/tenant-management/src/Volo.Abp.TenantManagement.Domain/Volo/Abp/TenantManagement/TenantManager.cs) defines a Create method which is forced to use while creating a new tenant.

How we forced it? Simple: Declared the [Tenant constructor](https://github.com/abpframework/abp/blob/master/modules/tenant-management/src/Volo.Abp.TenantManagement.Domain/Volo/Abp/TenantManagement/Tenant.cs#L21) as internal, so it can only be used in the Domain layer and Application layer should always use the TenantManager to create a new tenant. Why? Because the TenantManager [ensures ](https://github.com/abpframework/abp/blob/master/modules/tenant-management/src/Volo.Abp.TenantManagement.Domain/Volo/Abp/TenantManagement/TenantManager.cs#L21) uniqueness of the tenanct name.

As similar, changing name of a tenant is only possible through the TenantManager.

So, if I should write a rule for that, I would write these set of rules:

1. Make it simplest possible (as a general rule :)
2. Entity constructor should ensure validity of the entity.
3. If an entity constructor can also ensure validity of the system, then the constructor can be public and directly be usable inside the application layer.
4. If an entity constructor can NOT ensure validity of the system (like in the Tenant example), it should force to use a domain service by making the constructor internal (or with another way, but I don't want to extend the topic).

This is not only for constructor actually, but also valid for any method/property of the entity.

This was the best practices in my opinion. But, for this specific document;

* Each document should focus on its own concept (application services in this case) and should keep other concepts simpler.
* Domain service document will already provide necessary information about domain services and include examples of domain service requirement.
* Additionally, we can create a DDD document to explain best practices while it has lower priority since the ABP framework has many missing documents until come there :)

**Comment by leonkosak** [comment]
Maybe I didn't write clearly enough. :)
My whole point was that each example has to have a basic and advanced scenario (BookApp and CloudEvent app).
Many developers who started development in ABP/ASP.NET Zero don't leverage whole architecture and therefore methods inApplication/Web projects are long and full of business logic inside.

Excuse me for misunderstanding.

**Comment by hikalkan** [comment]
No problem @leonkosak :)
I tried to answer to both questions. One of the goals of the ABP project is to help developers to learn best practices. So, a DDD best practices document or tutorial would be good in the future.

Created an issue for it: https://github.com/abpframework/abp/issues/876
