### ISSUE TITLE
Suite creates a Public empty constructor in contradiction to the docs

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#8730]
In the docks it says "[If you create an entity with a constructor that takes parameters, also create a private or protected empty constructor](https://docs.abp.io/en/abp/latest/Entities#entities-with-guid-keys)" but Suite creates the empty constructor as public.

It should be protected/private right?

* Your **ABP Framework version**. 4.2.2
* Your database provider: EF Core

**Comment by ebicoglu** [comment]
@[sturlath](https://github.com/sturlath) you're right. the empty constructor should be protected. but we didn't make it protected because many developers have an issue while mapping entity to DTO with Automapper and thinking it's a problem. But you can change your entity template in ABP Suite. The template name is `Entity.txt`. Change the public keyword to protected.
