### ISSUE TITLE
Throwing BusinessException does not display modal

### ISSUE THREAD

**Issue by emilsjog** [abpframework/abp#8818]
* 4.3
* Blazor-server
* EF Core

When an BusinessException is thrown there is only the standard yellow bar showing with the text "An unhandled exception has occurred. See browser dev tools for details. Reload"
Shouldn't the error message modal be displayed? I have texts in the en.json together with correct error codes as in the documentation.

**Comment by emilsjog** [comment]
Noticed that this got assigned. Any timeline on this?

**Comment by stsrki** [comment]
For Blazor Server it is still not fully possible to catch all "unhandled exceptions". As far as I know, this is more a problem with .Net and Blazor Framework than it is with ABP. While we have managed to handle most of the errors with our custom _message modal_, we still need to find a way to handle the rest.

@hikalkan Maybe you can know more about the limitations since you were able to implement the message modal?

**Comment by emilsjog** [comment]
I've tested wit userFriendlyException but there is no _custom message modal_. What type of exception did you use @stsrki to trigger the modal? We migrated from WASM to blazor-server and this worked nicely before the migration so there could also be something missed in the upgrade.

**Comment by emilsjog** [comment]
I guess it's better to follow #8195 for this case

**Comment by Stirda** [comment]
@hikalkan said in #8195:
> We'd implemented a custom logger to show errors for Blazor WASM. For server side, ...

1. Does this mean that BusinessExceptions/UserFriendlyExceptions thrown from HttpApi.Host show a nice modal in Blazor WASM already? Because this is not the case for me. Exception message is not displayed. Only standard generic error one is.
2. Does this mean that exceptions thrown **into Blazor project** are the only ones handled by this automagical modal?

So, @emilsjog, maybe #8195 cannot close the current issue...

**Comment by emilsjog** [comment]
> 1. Does this mean that BusinessExceptions/UserFriendlyExceptions thrown from HttpApi.Host show a nice modal in Blazor WASM already? Because this is not the case for me. Exception message is not displayed. Only standard generic error one is.

1. Yes, when we used WASM there was a nice modal showing on exceptions thrown in api-side. But in Blazor-server there is only the yellow error bar with default text.

> 2. Does this mean that exceptions thrown **into Blazor project** are the only ones handled by this automagical modal?
2. Yes, exception thrown in application layer is not handled with the modal showing in the blazor-server project. I had to wrap service calls in `try{
 MyAppService.HelloWorld("john"); } catch(BusinessException)` in order to get that nice _automagical_ modal. Then it's possible to use the error code in the exception and act on it as I wish.
