### ISSUE TITLE
How to implement Save without Close in Angular Modal

### ISSUE THREAD

**Issue by gregbrant2** [abpframework/abp#8879]
* Your **ABP Framework version**. 4.3
* Your **User Interface** type: Angular
* Your database provider(EF Core/MongoDB): EF
* Exception message and **stack trace** if available (check the logs). : N/A
* Steps needed to **reproduce** the problem.

I want to implement a "Save without close" action on my modals but they always throw a warning that there is unsaved data. The code generated by ABP Suite assumes the Save action is always "Save and close". I've implemented "Save don't close" by removing the `this.isModalOpen = false` line from the `pipe` on the API call. How can I tell the modal that the data has been saved successfully?

**Comment by bnymncoskuner** [comment]
Hello,

You could pass `[suppressUnsavedChangesWarning]=true` to the `abp-modal` or you can provide it globally throughout your application as shown in the [docs](https://docs.abp.io/en/abp/latest/UI/Angular/Modal#suppressunsavedchangeswarning)

**Comment by ayyash** [comment]
Need to reopen this, you have two lines that go against each other in this file:
https://github.com/abpframework/abp/blob/125395a93b08c0116a5832a56494e46e477e12c2/npm/ng-packs/packages/theme-shared/src/lib/components/modal/modal.component.ts#L208

```
 fromEvent(window, 'beforeunload')
      .pipe(takeUntil(this.destroy$))
      .subscribe(event => {
        // TODO: check this
        if (!this.isFormDirty || this.suppressUnsavedChangesWarning) {
          event.preventDefault();
        }
      });
```

According to documentation, `suppressUnsavedChangesWarning` needs to be set to true to get rid of the notification, but on window refresh, I still get the browser confirmation because it returns `event.preventDefault`, it should be like the one in line 172:
```
if (this.isFormDirty && !this.suppressUnsavedChangesWarning) {
```
