### ISSUE TITLE
Update package error：Unable to find package Volo.Abp.Features with version (>= 0.15.0).

### ISSUE THREAD

**Issue by Nongzhsh** [abpframework/abp#907]
I am trying to update the reference package to  0.15.0 version in my project.
But an error occurred while executing the "dotnet restore" command: Cannot find Volo.Abp.Features package with version (>= 0.15.0).

**Comment by lszabados** [comment]
It is also a problem for me

**Comment by hikalkan** [comment]
Unfortunately, a developer (@gexiaoxu) has published the package's v0.14.0 before me: https://www.nuget.org/packages/Volo.Abp.Features
So, he is the package owner. I contacted him/her to transfer ownership to me, but not answered yet.
I will contact to nuget support since this is an abuse of the system.

**Comment by hikalkan** [comment]
It is now available. gexiaoxu transferred the ownership.
