### ISSUE TITLE
Object2Object mapping enhancements

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#94]
- [ ] If a custom map defined for T->K then we should also can map ``ICollection<T>`` -> ``ICollection<K>``.

**Comment by genoher** [comment]
Would it be possible to integrate this fix in the next release 5.3 or 6.0 or 7.0, please. 
I understand that if it hasn't been integrated it will be because it breaks something, or for some good reason that I don't understand, maybe because the tests are missing?

If not possible, what is the best way to do it? implement an IObjectMapper<TSource, TDestination> Interface
where TSource is ICollection<source> and TDdestination is ICollection<destination>?

Thank you very much.

https://stackoverflow.com/questions/70107428/abp-does-not-automatically-use-custom-mapper-class

**Comment by hikalkan** [comment]
@maliming can you check if we can implement this?

https://github.com/abpframework/abp/blob/b270e1aa6cee199fe7c98526496027e276d30e45/framework/src/Volo.Abp.ObjectMapping/Volo/Abp/ObjectMapping/DefaultObjectMapper.cs#L42-L49

Here, if we don't find a `specificMapper`, and if `TSource` implements `ICollection<TS>` and `TDestination` implements `ICollection<TD>` , then we can try to resolve `IObjectMapper<TS, TD>`. If it is registered to DI, we can use it to map items one by one and create the target collection manually. Can you check if that possible and efficient?
If you can implement this, please add tests and update the document as well.
