### ISSUE TITLE
Article Request: Basic theme without Bootstrap.

### ISSUE THREAD

**Issue by antosubash** [abpframework/abp#9440]
I see there is a lot of improvements made in ABP to make it themeable and to add the basic theme to the created project to make it easy to create our theme. It will be great if there is documentation or community article to remove bootstrap from the theme and replace it with something else like material or tailwind.

**Comment by enisn** [comment]
Replacing bootstrap completely is not possible since TagHelpers are static. 

How about rendering components from `.cshtml` files in TagHelpers. For example: `<abp-button>`  tag should render `AbpButton.cshtml` which includes bootstrap type button inside with given parameters. 

If someone tries to implement material, will replace `AbpButton.cshtml` and everything will work smoothly.

Also creating a new TagHelper is a good solution but existing modules can't be affected.

What do you think @hikalkan, @maliming  ?
