### ISSUE TITLE
Extending  Localization Resource, namespace name 'AbpIoLocalization' could not be found

### ISSUE THREAD

**Issue by mrs01dev** [abpframework/abp#9506]
Dear Dev's
trying to extend resources that exist on  ABP module  "AbpIoLocalization" , 
As per ABP sample:
https://github.com/abpframework/abp-samples/tree/master/DocumentationSamples/ExtendLocalizationResource#extending-existing-resource
and ABP FRAMEWORK DOCUMENTS
https://docs.abp.io/en/abp/latest/Localization#inherit-from-other-resources

using 
ABP Framework Version="4.3.3"
User Interface="MVC"
database provider="EF"
Exception message="Error	CS0246	The type or namespace name 'AbpIoLocalization' could not be found"

Also There is no NuGet for "AbpIoLocalization".

 Please specify how to 
override resources on AbpIoLocalization that exist on :
https://github.com/abpframework/abp/tree/48c52625f4c4df007f04d5ac6368b07411aa7521/abp_io/AbpIoLocalization/AbpIoLocalization/Admin/Localization/Resources

Thanks.

**Comment by berkansasmaz** [comment]
You can do that, but I don't think that's what you want to do. Because the [AbpIoLocalization project](https://github.com/abpframework/abp/tree/dev/abp_io) contains all localized resources of the [abp.io](http://abp.io/) platform.

If your goal is to localize the Identity resources, you can have a look [here](https://github.com/abpframework/abp/tree/dev/modules/identity/src/Volo.Abp.Identity.Domain.Shared/Volo/Abp/Identity/Localization).
