### ISSUE TITLE
4.4.0-rc.2 update encounter error

### ISSUE THREAD

**Issue by ruby0602** [abpframework/abp#9543]
![image](https://user-images.githubusercontent.com/4489940/125008307-d8157a80-e094-11eb-92a1-95d05826d085.png)
![image](https://user-images.githubusercontent.com/4489940/125008362-f4b1b280-e094-11eb-8526-47198775f00e.png)
there is no error in 4.3.3

**Comment by berkansasmaz** [comment]
This is because, as you know, the parameters in the base constructor of the AuditingStore have changed. We are constantly adding new features to the framework and our modules, so such cases may happen with major version changes. I don't think this is a problem.

https://github.com/abpframework/abp/commit/2491c8c488eb74da179b31e937b0cf4d1b6335d8#diff-887f3a7a1fe96e4db319df8157d3c42197aa1fde40d039927c8b0af1d3ed234aR19

**Comment by ruby0602** [comment]
@berkansasmaz thanks, I had solved it
