### ISSUE TITLE
About abp.js files.

### ISSUE THREAD

**Issue by ghost** [abpframework/abp#9602]
Hi,

We use 4.3.3 version. 

framework/src/Volo.Abp.AspNetCore.Components.Web/wwwroot/libs/abp/js/abp.js

abp.utils.setCookieValue metod not include secure parameter.

ABP Framework version : 4.3.3
User Interface                 : MVC
Your database provider  : EF Core
@hikalkan @maliming

**Comment by maliming** [comment]
hi

It has the `secure` parameter.

https://github.com/abpframework/abp/blob/4.3.3/framework/src/Volo.Abp.AspNetCore.Components.Web/wwwroot/libs/abp/js/abp.js#L27
https://github.com/abpframework/abp/blob/4.3.3/framework/src/Volo.Abp.AspNetCore.Components.Web/wwwroot/libs/abp/js/abp.js#L41

**Comment by ercanxp** [comment]
Hi, I upgraded abp version from 4.3.2 to 4.3.3. But the abp.js file is not updated. The current abp.js file does not have a secure parameter. Thank you for your answer, Best regardsErcan Çiftçi 15.07.2021, 15:57, "maliming" ***@***.***>: hiIt has the secure parameter.https://github.com/abpframework/abp/blob/4.3.3/framework/src/Volo.Abp.AspNetCore.Components.Web/wwwroot/libs/abp/js/abp.js#L27https://github.com/abpframework/abp/blob/4.3.3/framework/src/Volo.Abp.AspNetCore.Components.Web/wwwroot/libs/abp/js/abp.js#L41—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ghost** [comment]
Hi, @maliming 
 
I upgraded abp version from 4.3.2 to 4.3.3. But the abp.js file is not updated. The current abp.js file does not have a secure parameter.
 
Thank you for your answer,

**Comment by enisn** [comment]
You can update js & css files via using `yarn`.

You can follow [This document](https://docs.abp.io/en/abp/4.3/UI/AspNetCore/Client-Side-Package-Management) to update Client-Side packages

**Comment by ghost** [comment]
I used the yarn command. But there was no update in the abp.js file.

I got this file. [npm/packs/core/src/abp.js]  

not below

https://github.com/abpframework/abp/blob/4.3.3/framework/src/Volo.Abp.AspNetCore.Components.Web/wwwroot/libs/abp/js/abp.js#L27

![image](https://user-images.githubusercontent.com/9715414/125839607-3b03e900-7734-419c-9315-596b43fd6d7f.png)

![image](https://user-images.githubusercontent.com/9715414/125839896-25e6a79d-a2b7-4273-a817-e821af1dff41.png)

Am I doing something wrong? @enisn @maliming @hikalkan

**Comment by maliming** [comment]
hi

Are you executing the above command in a web project?

**Comment by ghost** [comment]
Hi @maliming 

Yes.

![image](https://user-images.githubusercontent.com/9715414/125909459-20337aff-9436-480e-bf67-30c0df078373.png)

**Comment by maliming** [comment]
hi
Can you share a minimum project to reproduce this?

**Comment by ercanxp** [comment]
Hi @maliming,

Can you connect me with AnyDesk?  544 147 714
