### ISSUE TITLE
SignalR custom routing doesn't work

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#9778]
Trying to add custom route to my SignalR Hub but doesn't work as expected.
I tried both the attribute method and Manual Registration / Mapping
Hub is inherited from `AbpHub`

Related doc => https://docs.abp.io/en/abp/latest/SignalR-Integration

![image](https://user-images.githubusercontent.com/9526587/128700858-019a2cd9-1eaf-4937-9181-3a91582ebfa1.png)

![image](https://user-images.githubusercontent.com/9526587/128701207-141fa6fe-3c68-4ed9-9900-91339a50048d.png)

Conventional method works
![image](https://user-images.githubusercontent.com/9526587/128701873-0eb0a127-a12c-4554-b8c0-16992b32e028.png)

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.SignalR/Volo/Abp/AspNetCore/SignalR/HubRouteAttribute.cs#L27-L35

This is expected,  If you customize the route, the `/signalr-hubs/` prefix will not be added.

![image](https://user-images.githubusercontent.com/16813853/128799906-68d78151-08e7-46b6-9065-4cda2c17eb44.png)

The route should be `/my-messaging/route` Instead of `/signalr-hubs/my-messaging/route`
