### ISSUE TITLE
Action column (DataGridEntityActionsColumn) switch sides on condition

### ISSUE THREAD

**Issue by puschie286** [abpframework/abp#9931]
DataGrid EntityActionsColumn is on the right side of the table if you wrap it in condition and change this condition. after reload the page ( or if the condition is true on first visit ) the column is on the left side ( like expected ).

Repoduce: 
You can use the BookStore and wrap https://github.com/abpframework/abp-samples/blob/567e1583668b52f8b0202cc67958a9dc0fd7ca4f/BookStore-Blazor-EfCore/src/Acme.BookStore.Blazor/Pages/Books.razor#L37-L51
with @if( HasUpdatePermission || HasDeletePermission )
then follow steps:
1. login with user only 'BookStore.Books' permission ( no sub )
2. view book page -> no action column should be shown
3. add user permission for 'BookStore.Books.Edit'
4. view book page again ( without reload ) -> action column should be shown on right side
5. reload page -> action column should be shown on left side

Framework: 4.4 + Blazor Server

**Comment by EngincanV** [comment]
Hi @puschie286, I could not reproduce your problem (I've tried a lot of times but it was always in the expected position). But as I understand, you don't want to view the **Actions** button if there is not any permission granted (i assume you've added the if condition for that reason), instead of wrapping `DataGridEntityActionsColumn` you can use the **Displayable** property of it.

```razor
 <DataGridEntityActionsColumn 
      TItem="BookDto" @ref="@EntityActionsColumn" 
      Displayable="@(HasUpdatePermission || HasDeletePermission)">
      
      ...

</DataGridEntityActionsColumn>
```

**Comment by puschie286** [comment]
thanks, now its working like intended :)
