### ISSUE TITLE
Localization does not work after publishing.

### ISSUE THREAD

**Issue by wmhiness** [abpframework/abp#9989]
.net5.0版本的 Volo.Abp 发布到服务器之后多语言失效 找不到，在开发模式是没问题的

**Comment by maliming** [comment]
If you're creating a bug/problem report, please include followings:

* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

Please **write in English**.
